{
 "title": "bk-nodemgr-file",
 "description": "bk-nodemgr-file service metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "bcs_cluster_id", "label": "bcs_cluster_id", "query": "label_values(bcs_cluster_id)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values({bcs_cluster_id=~\"$bcs_cluster_id\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "http server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(server_file_basic_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "basic service"
    },
    {
     "expr": "sum (rate(server_file_download_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "download service"
    }
   ]
  },
  {
   "title": "PV",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (server_file_basic_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "basic service"
    },
    {
     "expr": "sum (server_file_download_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "download service"
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(server_file_basic_request_uv_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "basic service"
    },
    {
     "expr": "sum(server_file_download_request_uv_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "download service"
    }
   ]
  },
  {
   "title": "Basic Service Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_basic_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Basic Service Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_basic_request_duration_sum{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])) / sum by (uri) (rate(server_file_basic_request_duration_count{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Basic Service Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_basic_request_body{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{uri}}-IN"
    },
    {
     "expr": "sum by (uri) (rate(server_file_basic_response_body{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{uri}}-OUT"
    }
   ]
  },
  {
   "title": "Download Service Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_download_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Download Service Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_download_request_duration_sum{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])) / sum by (uri) (rate(server_file_download_request_duration_count{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Download Service Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_download_request_body{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{uri}}-IN"
    },
    {
     "expr": "sum by (uri) (rate(server_file_download_response_body{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{uri}}-OUT"
    }
   ]
  },
  {
   "title": "Non-200 HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (uri, code) (rate(server_file_basic_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\", code!=\"200\"}[30s]))",
     "legendFormat": "[basic]{{uri}}-{{code}}"
    },
    {
     "expr": "sum by (uri, code) (rate(server_file_download_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\", code!=\"200\"}[30s]))",
     "legendFormat": "[download]{{uri}}-{{code}}"
    }
   ]
  },
  {
   "title": "Slow Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(server_file_basic_slow_request{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "[basic]{{uri}}"
    },
    {
     "expr": "sum by (uri) (rate(server_file_download_slow_request{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "[download]{{uri}}"
    }
   ]
  },
  { "title": "http client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "BK-REPO Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(client_bkrepo_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "[{{method}}]{{uri}}"
    }
   ]
  },
  {
   "title": "BK-REPO Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(client_bkrepo_request_duration_sum{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])) / sum by (uri, method) (rate(client_bkrepo_request_duration_count{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "[{{method}}]]{{uri}}"
    }
   ]
  },
  {
   "title": "BK-REPO Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(client_bkrepo_request_body{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "[{{method}}]{{uri}}-IN"
    },
    {
     "expr": "sum by (uri, method) (rate(client_bkrepo_response_body{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "[{{method}}]{{uri}}-OUT"
    }
   ]
  },
  {
   "title": "Non-200 HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (uri, code) (rate(client_bkrepo_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\", code!=\"200\"}[30s]))",
     "legendFormat": "[basic]{{uri}}-{{code}}"
    }
   ]
  },
  {
   "title": "Slow Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(client_bkrepo_slow_request{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "[basic]{{uri}}"
    }
   ]
  },
  {
   "title": "system info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 430 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 430 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 430 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 430 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 806 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"} - go_memstats_frees_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "live objs"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 806 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 806 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 806 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 814 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 814 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "mongodb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "DB operation count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 431 },
     "targets": [
      {
       "expr": "rate(mongodb_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{table}}-{{operation}}"
      }
     ]
    },
    {
     "title": "DB operation duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 431 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (table, operation) (rate(mongodb_request_duration_sum{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])) / sum by (table, operation) (rate(mongodb_request_duration_count{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "{{table}}-{{operation}}"
      }
     ]
    },
    {
     "title": "DB operation success rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 439 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (table, operation) (rate(mongodb_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\", success=\"true\"}[30s]) ) / sum by (table, operation) (rate(mongodb_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
       "legendFormat": "{{table}}-{{operation}}"
      }
     ]
    },
    {
     "title": "DB operation slow request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 439 },
     "targets": [
      {
       "expr": "rate(mongodb_slow_request{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{table}}-{{operation}}"
      }
     ]
    },
    {
     "title": "DB operation request data length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 447 },
     "targets": [
      {
       "expr": "rate(mongodb_request_data_length{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{table}}-{{operation}}"
      }
     ]
    },
    {
     "title": "DB operation response data length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 447 },
     "targets": [
      {
       "expr": "rate(mongodb_response_data_length{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{table}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis operation count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 592 },
     "targets": [
      {
       "expr": "rate(redis_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Redis operation duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 592 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(redis_request_duration_sum{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])) / sum by (operation) (rate(redis_request_duration_count{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Redis operation success rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(redis_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\", success=\"true\"}[30s]) ) / sum by (operation) (rate(redis_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Redis operation slow request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 600 },
     "targets": [
      {
       "expr": "rate(redis_slow_request{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Redis operation request data size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 608 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(redis_request_data_size{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Redis operation response data size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 608 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(redis_response_data_size{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage operation count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 617 },
     "targets": [
      {
       "expr": "rate(storage_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{name}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Storage operation duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 617 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (name, operation) (rate(storage_request_duration_sum{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m])) / sum by (name, operation) (rate(storage_request_duration_count{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[1m]))",
       "legendFormat": "{{name}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Storage operation success rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 625 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (name, operation) (rate(storage_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\", success=\"true\"}[30s]) ) / sum by (name, operation) (rate(storage_request_total{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s]))",
       "legendFormat": "{{name}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Storage operation slow request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 625 },
     "targets": [
      {
       "expr": "rate(storage_slow_request{bcs_cluster_id=~\"$bcs_cluster_id\",namespace=~\"$namespace\"}[30s])",
       "legendFormat": "{{name}}-{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}