apiVersion: v2
appVersion: v3.0.1-alpha.76
name: mock-server
description: Mock server for bk-nodemgr testing, provides mock APIs for CMDB and BKRepo.
type: application
version: v3.0.1-alpha.76
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
