version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: false
  allow-serial-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file
  path-prefix: ""
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - lll
    - maintidx
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 20
      package-average: 0
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 120
      statements: -1
      ignore-comments: true
    gocognit:
      min-complexity: 20
    goconst:
      match-constant: true
      min-len: 2
      min-occurrences: 3
      numbers: true
      min: 2
      max: 2
      ignore-calls: true
    gocyclo:
      min-complexity: 20
    godot:
      scope: declarations
      exclude:
        - '^fixme:'
        - '^todo:'
      capital: false
      period: true
    gosec:
      excludes:
        - G101
        - G102
        - G115
      severity: medium
      confidence: medium
      config:
        G104:
          fmt:
            - Fscanf
        G111:
          pattern: custom\.Dir\(\)
        G301: "0750"
        G302: "0600"
        G306: "0600"
        global:
          '#nosec': '#my-custom-nosec'
          audit: true
          nosec: false
          show-ignored: true
      concurrency: 6
    importas:
      alias:
        - pkg: errors
          alias: ""
        - pkg: go.etcd.io/etcd/client/v3
          alias: clientv3
        - pkg: github.com/TencentBlueKing/bk-gse-sdk/go/service/server-api
          alias: serverapi
        - pkg: github.com/TencentBlueKing/bk-gse-sdk/go/service/agent-message
          alias: agentmessage
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/proto/application/api/v3
          alias: protoApplication
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/proto/backend/api/v3
          alias: protoBackend
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/proto/backend/callback
          alias: protoCallback
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/proto/file/api/v3
          alias: protoFile
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/router/api-v3/auth
          alias: authRouter
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/auth/provider
          alias: authProvider
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/application/storage/tenant
          alias: tenantStorage
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/proto/relay
          alias: protoRelay
        - pkg: github.com/testcontainers/testcontainers-go
          alias: tc
        - pkg: go.mongodb.org/mongo-driver/mongo/options
          alias: mongoOptions
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/topo
          alias: topoStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/operinstdata
          alias: operinstdataStorage
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/package-workflow
          alias: packageworkflow
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/node
          alias: nodeStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/plugin
          alias: pluginStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/workflow
          alias: workflowStg
        - pkg: github.com/RichardKnop/machinery/v2/backends/iface
          alias: backendIface
        - pkg: github.com/RichardKnop/machinery/v2/backends/redis
          alias: backendRedis
        - pkg: github.com/RichardKnop/machinery/v2/brokers/iface
          alias: brokerIface
        - pkg: github.com/RichardKnop/machinery/v2/brokers/redis
          alias: brokerRedis
        - pkg: github.com/RichardKnop/machinery/v2/config
          alias: machineryConfig
        - pkg: github.com/RichardKnop/machinery/v2/log
          alias: machineryLog
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/header
          alias: restheader
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/base
          alias: daoBase
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/file/storage/packageevent
          alias: packageEventStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/file/storage/topo
          alias: storageTopo
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/file/storage/release
          alias: storageRelease
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/file/storage/upload
          alias: storageUpload
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/filex/iface
          alias: fileiface
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/globalsettings
          alias: globalsettingsStorage
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/operation
          alias: storageOperation
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/client
          alias: restclient
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/server
          alias: restserver
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/contextx
          alias: contextx
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/errf
          alias: resterrf
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/discovery
          alias: restdiscovery
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/rest/metrics
          alias: restmetrics
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/thirdparty/apigw/client
          alias: apigwclient
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/thirdparty/apigw/server
          alias: apigwserver
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/thirdparty/apigw/header
          alias: apigwheader
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/application/router/api-v3
          alias: applicationapiv3
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/router/api-v3
          alias: backendapiv3
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/file/router/api-v3
          alias: fileapiv3
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/relay/router/api-v3
          alias: relayapiv3
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/thirdparty/bksaas/header
          alias: bksaasheader
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/thirdparty/bksaas/bklogin
          alias: bksaasbklogin
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/workflow/operation
          alias: workoper
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/trigger
          alias: daoTrigger
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo
          alias: daomongo
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/plugin-workflow
          alias: pluginworkflow
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/plugin-deployment
          alias: plugindeployment
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/node/utils
          alias: nodeUtils
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/plugin/utils
          alias: pluginUtils
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/pluginv2
          alias: pluginv2
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/pluginv2/utils
          alias: pluginV2Utils
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/syncdata/utils
          alias: syncDataUtils
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/scheduled-workflow
          alias: scheduledworkflow
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/format/platform
          alias: platfmt
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/format/configfile
          alias: cffmt
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/process
          alias: daoProcess
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/plugin
          alias: daoPlugin
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/packageevent
          alias: daoPackageEvent
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/deploypolicy
          alias: daoDeployPolicy
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/node-workflow
          alias: daoNodeWorkflow
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/node-deployment
          alias: daoNodeDeployment
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/operation
          alias: daoOperation
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/tenant
          alias: tenantStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/release
          alias: releaseStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/configpolicy-event
          alias: daoConfigPolicyEvent
        - pkg: go.opentelemetry.io/contrib/instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo
          alias: otelmongo
        - pkg: go.opentelemetry.io/otel/sdk/trace
          alias: sdkTrace
        - pkg: go.opentelemetry.io/otel/semconv/v1.17.0
          alias: semconv
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/iface
          alias: managerIface
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/dpmgr
          alias: dpmgr
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/cipher
          alias: cipherStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/cipher
          alias: daoCipher
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/deploypolicy/utils
          alias: deployPolicyUtils
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/process-config
          alias: daoProcessConfig
        - pkg: github.com/patrickmn/go-cache
          alias: gocache
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/router/api-v3/iam/v3
          alias: iamv3
        - pkg: github.com/TencentBlueKing/bk-nodemgr/tools/cmd/installer/plugin/flag
          alias: pluginFlag
        - pkg: github.com/TencentBlueKing/bk-nodemgr/tools/cmd/installer/pluginv2/flag
          alias: pluginV2Flag
        - pkg: github.com/TencentBlueKing/bk-nodemgr/tools/cmd/installer/node/flag
          alias: nodeFlag
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/globalsettings
          alias: pkgglobalsettings
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/process-v2
          alias: daoProcessV2
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/process-v2-config
          alias: daoProcessV2Config
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/storage/pkg
          alias: pkgStg
        - pkg: github.com/TencentBlueKing/bk-nodemgr/pkg/dao/mongo/package-deployment
          alias: packagedeployment
        - pkg: github.com/TencentBlueKing/bk-nodemgr/internal/backend/manager/workflowdef/pkg/utils
          alias: pkgUtils
      no-unaliased: false
      no-extra-aliases: true
    interfacebloat:
      max: 10
    lll:
      line-length: 150
      tab-width: 1
    nlreturn:
      block-size: 2
    varnamelen:
      max-distance: 6
      min-name-length: 2
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-names:
        - r
        - "n"
        - err
        - p
        - f
        - x
        - k
        - v
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - c echo.Context
        - t testing.T
        - f *foo.Bar
        - e error
        - i int
        - const C
        - T any
        - m map[string]int
        - r recover
        - p pool
        - r gin.Router
        - r Router
        - h *handler
        - h handler
        - h *Handler
        - r *Request
        - r *Result
        - c *Config
        - d *Discovery
        - c *cli
        - m *manager
        - o *Operation
        - e *engine
        - t *Trigger
        - s *scheduler
        - m *Manager
        - d *dao
        - d Dao
        - w *Watcher
        - s *storage
        - s *Storage
        - p *ProviderDefault
        - m *operMgr
        - g *Group
        - t *Transfer
        - m *clientMessager
        - m *serverMessager
        - c Context
        - o *Option
        - c TLSConfig
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    rules:
      - linters:
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - forbidigo
        path-except: _test\.go
      - linters:
          - gosec
        path: internal/hmac/
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - lll
        source: '^//go:generate '
      - path: (.+)\.go$
        text: abcdef
      - linters:
          - cyclop
          - goconst
        path: (.+)_test\.go
    paths:
      - .*\.pb\.go$
      - front/*
      - docs/*
      - install/*
      - .github/*
      - proto/*
      - pkg/blog/*
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: master
  whole-files: true
  new: false
  fix: false
severity:
  default: warn
  rules:
    - linters:
        - dupl
      severity: info
