apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mock-server.fullname" . }}-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  mock_conf.yaml: |
    basicServer: {{ .Values.config.basicServer | toYaml | nindent 6 }}

    log: {{ .Values.config.log | toYaml | nindent 6 }}

    cmdbConfig: {{ .Values.config.cmdbConfig | toYaml | nindent 6 }}

    bkrepoConfig: {{ .Values.config.bkrepoConfig | toYaml | nindent 6 }}

    {{- if .Values.config.mockData }}
    mockData: {{ .Values.config.mockData | toYaml | nindent 6 }}
    {{- end }}
