// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: globalsettings.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GlobalSetting describes a global setting.
type GlobalSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   string                 `protobuf:"bytes,1,opt,name=setting_name,json=settingName,proto3" json:"setting_name"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalSetting) Reset() {
	*x = GlobalSetting{}
	mi := &file_globalsettings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSetting) ProtoMessage() {}

func (x *GlobalSetting) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSetting.ProtoReflect.Descriptor instead.
func (*GlobalSetting) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalSetting) GetSettingName() string {
	if x != nil {
		return x.SettingName
	}
	return ""
}

func (x *GlobalSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ListGlobalSettingsReq describes the HTTP request body when list global
// settings.
type ListGlobalSettingsReq struct {
	state                  protoimpl.MessageState                 `protogen:"open.v1"`
	Page                   *Page                                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	OnlyCount              bool                                   `protobuf:"varint,2,opt,name=only_count,json=onlyCount,proto3" json:"only_count"`
	ExactIncludeConditions *ListGlobalSettingsReq_ExactConditions `protobuf:"bytes,3,opt,name=exact_include_conditions,json=exactIncludeConditions,proto3" json:"exact_include_conditions"`
	FuzzyIncludeConditions *ListGlobalSettingsReq_FuzzyConditions `protobuf:"bytes,4,opt,name=fuzzy_include_conditions,json=fuzzyIncludeConditions,proto3" json:"fuzzy_include_conditions"`
	ExactExcludeConditions *ListGlobalSettingsReq_ExactConditions `protobuf:"bytes,5,opt,name=exact_exclude_conditions,json=exactExcludeConditions,proto3" json:"exact_exclude_conditions"`
	FuzzyExcludeConditions *ListGlobalSettingsReq_FuzzyConditions `protobuf:"bytes,6,opt,name=fuzzy_exclude_conditions,json=fuzzyExcludeConditions,proto3" json:"fuzzy_exclude_conditions"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListGlobalSettingsReq) Reset() {
	*x = ListGlobalSettingsReq{}
	mi := &file_globalsettings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsReq) ProtoMessage() {}

func (x *ListGlobalSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsReq.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsReq) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{1}
}

func (x *ListGlobalSettingsReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListGlobalSettingsReq) GetOnlyCount() bool {
	if x != nil {
		return x.OnlyCount
	}
	return false
}

func (x *ListGlobalSettingsReq) GetExactIncludeConditions() *ListGlobalSettingsReq_ExactConditions {
	if x != nil {
		return x.ExactIncludeConditions
	}
	return nil
}

func (x *ListGlobalSettingsReq) GetFuzzyIncludeConditions() *ListGlobalSettingsReq_FuzzyConditions {
	if x != nil {
		return x.FuzzyIncludeConditions
	}
	return nil
}

func (x *ListGlobalSettingsReq) GetExactExcludeConditions() *ListGlobalSettingsReq_ExactConditions {
	if x != nil {
		return x.ExactExcludeConditions
	}
	return nil
}

func (x *ListGlobalSettingsReq) GetFuzzyExcludeConditions() *ListGlobalSettingsReq_FuzzyConditions {
	if x != nil {
		return x.FuzzyExcludeConditions
	}
	return nil
}

// ListGlobalSettingsResp describes the HTTP response body when list global
// settings.
type ListGlobalSettingsResp struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                        `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Error         *ListGlobalSettingsResp_Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Data          *ListGlobalSettingsResp_Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalSettingsResp) Reset() {
	*x = ListGlobalSettingsResp{}
	mi := &file_globalsettings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsResp) ProtoMessage() {}

func (x *ListGlobalSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsResp.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsResp) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{2}
}

func (x *ListGlobalSettingsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListGlobalSettingsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListGlobalSettingsResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListGlobalSettingsResp) GetError() *ListGlobalSettingsResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ListGlobalSettingsResp) GetData() *ListGlobalSettingsResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetGlobalSettingReq describes the HTTP request body when get a global
// setting.
type GetGlobalSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   string                 `protobuf:"bytes,1,opt,name=setting_name,json=settingName,proto3" json:"setting_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalSettingReq) Reset() {
	*x = GetGlobalSettingReq{}
	mi := &file_globalsettings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalSettingReq) ProtoMessage() {}

func (x *GetGlobalSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalSettingReq.ProtoReflect.Descriptor instead.
func (*GetGlobalSettingReq) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{3}
}

func (x *GetGlobalSettingReq) GetSettingName() string {
	if x != nil {
		return x.SettingName
	}
	return ""
}

// GetGlobalSettingResp describes the HTTP response body when get a global
// setting.
type GetGlobalSettingResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          int32                       `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                      `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Error         *GetGlobalSettingResp_Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Data          *GetGlobalSettingResp_Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalSettingResp) Reset() {
	*x = GetGlobalSettingResp{}
	mi := &file_globalsettings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalSettingResp) ProtoMessage() {}

func (x *GetGlobalSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalSettingResp.ProtoReflect.Descriptor instead.
func (*GetGlobalSettingResp) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{4}
}

func (x *GetGlobalSettingResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGlobalSettingResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGlobalSettingResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetGlobalSettingResp) GetError() *GetGlobalSettingResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetGlobalSettingResp) GetData() *GetGlobalSettingResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpsertGlobalSettingReq describes the HTTP request body when upsert global
// settings.
type UpsertGlobalSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*GlobalSetting       `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGlobalSettingsReq) Reset() {
	*x = UpsertGlobalSettingsReq{}
	mi := &file_globalsettings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGlobalSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGlobalSettingsReq) ProtoMessage() {}

func (x *UpsertGlobalSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGlobalSettingsReq.ProtoReflect.Descriptor instead.
func (*UpsertGlobalSettingsReq) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertGlobalSettingsReq) GetSettings() []*GlobalSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

// UpsertGlobalSettingResp describes the HTTP response body when upsert global
// settings.
type UpsertGlobalSettingsResp struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                          `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Error         *UpsertGlobalSettingsResp_Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Data          *UpsertGlobalSettingsResp_Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGlobalSettingsResp) Reset() {
	*x = UpsertGlobalSettingsResp{}
	mi := &file_globalsettings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGlobalSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGlobalSettingsResp) ProtoMessage() {}

func (x *UpsertGlobalSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGlobalSettingsResp.ProtoReflect.Descriptor instead.
func (*UpsertGlobalSettingsResp) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertGlobalSettingsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpsertGlobalSettingsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertGlobalSettingsResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpsertGlobalSettingsResp) GetError() *UpsertGlobalSettingsResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *UpsertGlobalSettingsResp) GetData() *UpsertGlobalSettingsResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteGlobalSettingReq describes the HTTP request body when delete global
// settings.
type DeleteGlobalSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   []string               `protobuf:"bytes,1,rep,name=setting_name,json=settingName,proto3" json:"setting_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalSettingsReq) Reset() {
	*x = DeleteGlobalSettingsReq{}
	mi := &file_globalsettings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalSettingsReq) ProtoMessage() {}

func (x *DeleteGlobalSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalSettingsReq.ProtoReflect.Descriptor instead.
func (*DeleteGlobalSettingsReq) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGlobalSettingsReq) GetSettingName() []string {
	if x != nil {
		return x.SettingName
	}
	return nil
}

// DeleteGlobalSettingResp describes the HTTP response body when delete global
// settings.
type DeleteGlobalSettingsResp struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                          `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Error         *DeleteGlobalSettingsResp_Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Data          *DeleteGlobalSettingsResp_Data  `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalSettingsResp) Reset() {
	*x = DeleteGlobalSettingsResp{}
	mi := &file_globalsettings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalSettingsResp) ProtoMessage() {}

func (x *DeleteGlobalSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalSettingsResp.ProtoReflect.Descriptor instead.
func (*DeleteGlobalSettingsResp) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGlobalSettingsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteGlobalSettingsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteGlobalSettingsResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteGlobalSettingsResp) GetError() *DeleteGlobalSettingsResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DeleteGlobalSettingsResp) GetData() *DeleteGlobalSettingsResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListGlobalSettingsReq_ExactConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   []string               `protobuf:"bytes,1,rep,name=setting_name,json=settingName,proto3" json:"setting_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalSettingsReq_ExactConditions) Reset() {
	*x = ListGlobalSettingsReq_ExactConditions{}
	mi := &file_globalsettings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsReq_ExactConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsReq_ExactConditions) ProtoMessage() {}

func (x *ListGlobalSettingsReq_ExactConditions) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsReq_ExactConditions.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsReq_ExactConditions) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListGlobalSettingsReq_ExactConditions) GetSettingName() []string {
	if x != nil {
		return x.SettingName
	}
	return nil
}

type ListGlobalSettingsReq_FuzzyConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   []string               `protobuf:"bytes,1,rep,name=setting_name,json=settingName,proto3" json:"setting_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalSettingsReq_FuzzyConditions) Reset() {
	*x = ListGlobalSettingsReq_FuzzyConditions{}
	mi := &file_globalsettings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsReq_FuzzyConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsReq_FuzzyConditions) ProtoMessage() {}

func (x *ListGlobalSettingsReq_FuzzyConditions) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsReq_FuzzyConditions.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsReq_FuzzyConditions) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListGlobalSettingsReq_FuzzyConditions) GetSettingName() []string {
	if x != nil {
		return x.SettingName
	}
	return nil
}

type ListGlobalSettingsResp_Error struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	System        string                                  `protobuf:"bytes,1,opt,name=system,proto3" json:"system"`
	Message       string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Details       []*ListGlobalSettingsResp_Error_Details `protobuf:"bytes,3,rep,name=details,proto3" json:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalSettingsResp_Error) Reset() {
	*x = ListGlobalSettingsResp_Error{}
	mi := &file_globalsettings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsResp_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsResp_Error) ProtoMessage() {}

func (x *ListGlobalSettingsResp_Error) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsResp_Error.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsResp_Error) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListGlobalSettingsResp_Error) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *ListGlobalSettingsResp_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListGlobalSettingsResp_Error) GetDetails() []*ListGlobalSettingsResp_Error_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type ListGlobalSettingsResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Items         []*GlobalSetting       `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalSettingsResp_Data) Reset() {
	*x = ListGlobalSettingsResp_Data{}
	mi := &file_globalsettings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsResp_Data) ProtoMessage() {}

func (x *ListGlobalSettingsResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsResp_Data.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsResp_Data) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListGlobalSettingsResp_Data) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListGlobalSettingsResp_Data) GetItems() []*GlobalSetting {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListGlobalSettingsResp_Error_Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalSettingsResp_Error_Details) Reset() {
	*x = ListGlobalSettingsResp_Error_Details{}
	mi := &file_globalsettings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalSettingsResp_Error_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalSettingsResp_Error_Details) ProtoMessage() {}

func (x *ListGlobalSettingsResp_Error_Details) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalSettingsResp_Error_Details.ProtoReflect.Descriptor instead.
func (*ListGlobalSettingsResp_Error_Details) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ListGlobalSettingsResp_Error_Details) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ListGlobalSettingsResp_Error_Details) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGlobalSettingResp_Error struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	System        string                                `protobuf:"bytes,1,opt,name=system,proto3" json:"system"`
	Message       string                                `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Details       []*GetGlobalSettingResp_Error_Details `protobuf:"bytes,3,rep,name=details,proto3" json:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalSettingResp_Error) Reset() {
	*x = GetGlobalSettingResp_Error{}
	mi := &file_globalsettings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalSettingResp_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalSettingResp_Error) ProtoMessage() {}

func (x *GetGlobalSettingResp_Error) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalSettingResp_Error.ProtoReflect.Descriptor instead.
func (*GetGlobalSettingResp_Error) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetGlobalSettingResp_Error) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *GetGlobalSettingResp_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGlobalSettingResp_Error) GetDetails() []*GetGlobalSettingResp_Error_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetGlobalSettingResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalSettingResp_Data) Reset() {
	*x = GetGlobalSettingResp_Data{}
	mi := &file_globalsettings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalSettingResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalSettingResp_Data) ProtoMessage() {}

func (x *GetGlobalSettingResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalSettingResp_Data.ProtoReflect.Descriptor instead.
func (*GetGlobalSettingResp_Data) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetGlobalSettingResp_Data) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetGlobalSettingResp_Error_Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalSettingResp_Error_Details) Reset() {
	*x = GetGlobalSettingResp_Error_Details{}
	mi := &file_globalsettings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalSettingResp_Error_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalSettingResp_Error_Details) ProtoMessage() {}

func (x *GetGlobalSettingResp_Error_Details) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalSettingResp_Error_Details.ProtoReflect.Descriptor instead.
func (*GetGlobalSettingResp_Error_Details) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *GetGlobalSettingResp_Error_Details) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetGlobalSettingResp_Error_Details) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpsertGlobalSettingsResp_Error struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	System        string                                    `protobuf:"bytes,1,opt,name=system,proto3" json:"system"`
	Message       string                                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Details       []*UpsertGlobalSettingsResp_Error_Details `protobuf:"bytes,3,rep,name=details,proto3" json:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGlobalSettingsResp_Error) Reset() {
	*x = UpsertGlobalSettingsResp_Error{}
	mi := &file_globalsettings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGlobalSettingsResp_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGlobalSettingsResp_Error) ProtoMessage() {}

func (x *UpsertGlobalSettingsResp_Error) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGlobalSettingsResp_Error.ProtoReflect.Descriptor instead.
func (*UpsertGlobalSettingsResp_Error) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpsertGlobalSettingsResp_Error) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *UpsertGlobalSettingsResp_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpsertGlobalSettingsResp_Error) GetDetails() []*UpsertGlobalSettingsResp_Error_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type UpsertGlobalSettingsResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGlobalSettingsResp_Data) Reset() {
	*x = UpsertGlobalSettingsResp_Data{}
	mi := &file_globalsettings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGlobalSettingsResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGlobalSettingsResp_Data) ProtoMessage() {}

func (x *UpsertGlobalSettingsResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGlobalSettingsResp_Data.ProtoReflect.Descriptor instead.
func (*UpsertGlobalSettingsResp_Data) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{6, 1}
}

type UpsertGlobalSettingsResp_Error_Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGlobalSettingsResp_Error_Details) Reset() {
	*x = UpsertGlobalSettingsResp_Error_Details{}
	mi := &file_globalsettings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGlobalSettingsResp_Error_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGlobalSettingsResp_Error_Details) ProtoMessage() {}

func (x *UpsertGlobalSettingsResp_Error_Details) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGlobalSettingsResp_Error_Details.ProtoReflect.Descriptor instead.
func (*UpsertGlobalSettingsResp_Error_Details) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *UpsertGlobalSettingsResp_Error_Details) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpsertGlobalSettingsResp_Error_Details) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteGlobalSettingsResp_Error struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	System        string                                    `protobuf:"bytes,1,opt,name=system,proto3" json:"system"`
	Message       string                                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Details       []*DeleteGlobalSettingsResp_Error_Details `protobuf:"bytes,3,rep,name=details,proto3" json:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalSettingsResp_Error) Reset() {
	*x = DeleteGlobalSettingsResp_Error{}
	mi := &file_globalsettings_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalSettingsResp_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalSettingsResp_Error) ProtoMessage() {}

func (x *DeleteGlobalSettingsResp_Error) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalSettingsResp_Error.ProtoReflect.Descriptor instead.
func (*DeleteGlobalSettingsResp_Error) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DeleteGlobalSettingsResp_Error) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *DeleteGlobalSettingsResp_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteGlobalSettingsResp_Error) GetDetails() []*DeleteGlobalSettingsResp_Error_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type DeleteGlobalSettingsResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalSettingsResp_Data) Reset() {
	*x = DeleteGlobalSettingsResp_Data{}
	mi := &file_globalsettings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalSettingsResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalSettingsResp_Data) ProtoMessage() {}

func (x *DeleteGlobalSettingsResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalSettingsResp_Data.ProtoReflect.Descriptor instead.
func (*DeleteGlobalSettingsResp_Data) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{8, 1}
}

type DeleteGlobalSettingsResp_Error_Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalSettingsResp_Error_Details) Reset() {
	*x = DeleteGlobalSettingsResp_Error_Details{}
	mi := &file_globalsettings_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalSettingsResp_Error_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalSettingsResp_Error_Details) ProtoMessage() {}

func (x *DeleteGlobalSettingsResp_Error_Details) ProtoReflect() protoreflect.Message {
	mi := &file_globalsettings_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalSettingsResp_Error_Details.ProtoReflect.Descriptor instead.
func (*DeleteGlobalSettingsResp_Error_Details) Descriptor() ([]byte, []int) {
	return file_globalsettings_proto_rawDescGZIP(), []int{8, 0, 0}
}

func (x *DeleteGlobalSettingsResp_Error_Details) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteGlobalSettingsResp_Error_Details) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_globalsettings_proto protoreflect.FileDescriptor

var file_globalsettings_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x33, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0d, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0xd4, 0x04, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x33, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x79,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f, 0x6e,
	0x6c, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x63, 0x0a, 0x18, 0x65, 0x78, 0x61, 0x63, 0x74,
	0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x33, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x16, 0x65, 0x78, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x63, 0x0a, 0x18,
	0x66, 0x75, 0x7a, 0x7a, 0x79, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x76, 0x33, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x75, 0x7a, 0x7a, 0x79, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x16, 0x66, 0x75, 0x7a, 0x7a, 0x79,
	0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x63, 0x0a, 0x18, 0x65, 0x78, 0x61, 0x63, 0x74, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x33, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x45,
	0x78, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x16,
	0x65, 0x78, 0x61, 0x63, 0x74, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x63, 0x0a, 0x18, 0x66, 0x75, 0x7a, 0x7a, 0x79, 0x5f,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x33, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x2e, 0x46, 0x75, 0x7a, 0x7a, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x16, 0x66, 0x75, 0x7a, 0x7a, 0x79, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x34, 0x0a, 0x0f, 0x45,
	0x78, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d,
	0x65, 0x1a, 0x34, 0x0a, 0x0f, 0x46, 0x75, 0x7a, 0x7a, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd2, 0x03, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x36, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x76, 0x33, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x33, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xb6, 0x01, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x76, 0x33, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x37, 0x0a, 0x07,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x45, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x33, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x38, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xa1, 0x03, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x33,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x76, 0x33, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xb4, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x40, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x33, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x1a, 0x37, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1c, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x48, 0x0a, 0x17, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x33, 0x2e, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x9b, 0x03, 0x0a, 0x18, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x38,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x76, 0x33, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x33, 0x2e, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0xb8, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x76,
	0x33, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x1a, 0x37, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x06, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x3c, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x9b, 0x03, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x76, 0x33, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x33, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xb8, 0x01, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x76, 0x33, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x37, 0x0a,
	0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x43,
	0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65, 0x6e,
	0x63, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x75, 0x65, 0x4b, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6b, 0x2d,
	0x6e, 0x6f, 0x64, 0x65, 0x6d, 0x67, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_globalsettings_proto_rawDescOnce sync.Once
	file_globalsettings_proto_rawDescData []byte
)

func file_globalsettings_proto_rawDescGZIP() []byte {
	file_globalsettings_proto_rawDescOnce.Do(func() {
		file_globalsettings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_globalsettings_proto_rawDesc), len(file_globalsettings_proto_rawDesc)))
	})
	return file_globalsettings_proto_rawDescData
}

var file_globalsettings_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_globalsettings_proto_goTypes = []any{
	(*GlobalSetting)(nil),                          // 0: v3.GlobalSetting
	(*ListGlobalSettingsReq)(nil),                  // 1: v3.ListGlobalSettingsReq
	(*ListGlobalSettingsResp)(nil),                 // 2: v3.ListGlobalSettingsResp
	(*GetGlobalSettingReq)(nil),                    // 3: v3.GetGlobalSettingReq
	(*GetGlobalSettingResp)(nil),                   // 4: v3.GetGlobalSettingResp
	(*UpsertGlobalSettingsReq)(nil),                // 5: v3.UpsertGlobalSettingsReq
	(*UpsertGlobalSettingsResp)(nil),               // 6: v3.UpsertGlobalSettingsResp
	(*DeleteGlobalSettingsReq)(nil),                // 7: v3.DeleteGlobalSettingsReq
	(*DeleteGlobalSettingsResp)(nil),               // 8: v3.DeleteGlobalSettingsResp
	(*ListGlobalSettingsReq_ExactConditions)(nil),  // 9: v3.ListGlobalSettingsReq.ExactConditions
	(*ListGlobalSettingsReq_FuzzyConditions)(nil),  // 10: v3.ListGlobalSettingsReq.FuzzyConditions
	(*ListGlobalSettingsResp_Error)(nil),           // 11: v3.ListGlobalSettingsResp.Error
	(*ListGlobalSettingsResp_Data)(nil),            // 12: v3.ListGlobalSettingsResp.Data
	(*ListGlobalSettingsResp_Error_Details)(nil),   // 13: v3.ListGlobalSettingsResp.Error.Details
	(*GetGlobalSettingResp_Error)(nil),             // 14: v3.GetGlobalSettingResp.Error
	(*GetGlobalSettingResp_Data)(nil),              // 15: v3.GetGlobalSettingResp.Data
	(*GetGlobalSettingResp_Error_Details)(nil),     // 16: v3.GetGlobalSettingResp.Error.Details
	(*UpsertGlobalSettingsResp_Error)(nil),         // 17: v3.UpsertGlobalSettingsResp.Error
	(*UpsertGlobalSettingsResp_Data)(nil),          // 18: v3.UpsertGlobalSettingsResp.Data
	(*UpsertGlobalSettingsResp_Error_Details)(nil), // 19: v3.UpsertGlobalSettingsResp.Error.Details
	(*DeleteGlobalSettingsResp_Error)(nil),         // 20: v3.DeleteGlobalSettingsResp.Error
	(*DeleteGlobalSettingsResp_Data)(nil),          // 21: v3.DeleteGlobalSettingsResp.Data
	(*DeleteGlobalSettingsResp_Error_Details)(nil), // 22: v3.DeleteGlobalSettingsResp.Error.Details
	(*Page)(nil), // 23: v3.Page
}
var file_globalsettings_proto_depIdxs = []int32{
	23, // 0: v3.ListGlobalSettingsReq.page:type_name -> v3.Page
	9,  // 1: v3.ListGlobalSettingsReq.exact_include_conditions:type_name -> v3.ListGlobalSettingsReq.ExactConditions
	10, // 2: v3.ListGlobalSettingsReq.fuzzy_include_conditions:type_name -> v3.ListGlobalSettingsReq.FuzzyConditions
	9,  // 3: v3.ListGlobalSettingsReq.exact_exclude_conditions:type_name -> v3.ListGlobalSettingsReq.ExactConditions
	10, // 4: v3.ListGlobalSettingsReq.fuzzy_exclude_conditions:type_name -> v3.ListGlobalSettingsReq.FuzzyConditions
	11, // 5: v3.ListGlobalSettingsResp.error:type_name -> v3.ListGlobalSettingsResp.Error
	12, // 6: v3.ListGlobalSettingsResp.data:type_name -> v3.ListGlobalSettingsResp.Data
	14, // 7: v3.GetGlobalSettingResp.error:type_name -> v3.GetGlobalSettingResp.Error
	15, // 8: v3.GetGlobalSettingResp.data:type_name -> v3.GetGlobalSettingResp.Data
	0,  // 9: v3.UpsertGlobalSettingsReq.settings:type_name -> v3.GlobalSetting
	17, // 10: v3.UpsertGlobalSettingsResp.error:type_name -> v3.UpsertGlobalSettingsResp.Error
	18, // 11: v3.UpsertGlobalSettingsResp.data:type_name -> v3.UpsertGlobalSettingsResp.Data
	20, // 12: v3.DeleteGlobalSettingsResp.error:type_name -> v3.DeleteGlobalSettingsResp.Error
	21, // 13: v3.DeleteGlobalSettingsResp.data:type_name -> v3.DeleteGlobalSettingsResp.Data
	13, // 14: v3.ListGlobalSettingsResp.Error.details:type_name -> v3.ListGlobalSettingsResp.Error.Details
	0,  // 15: v3.ListGlobalSettingsResp.Data.items:type_name -> v3.GlobalSetting
	16, // 16: v3.GetGlobalSettingResp.Error.details:type_name -> v3.GetGlobalSettingResp.Error.Details
	19, // 17: v3.UpsertGlobalSettingsResp.Error.details:type_name -> v3.UpsertGlobalSettingsResp.Error.Details
	22, // 18: v3.DeleteGlobalSettingsResp.Error.details:type_name -> v3.DeleteGlobalSettingsResp.Error.Details
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_globalsettings_proto_init() }
func file_globalsettings_proto_init() {
	if File_globalsettings_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_globalsettings_proto_rawDesc), len(file_globalsettings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_globalsettings_proto_goTypes,
		DependencyIndexes: file_globalsettings_proto_depIdxs,
		MessageInfos:      file_globalsettings_proto_msgTypes,
	}.Build()
	File_globalsettings_proto = out.File
	file_globalsettings_proto_goTypes = nil
	file_globalsettings_proto_depIdxs = nil
}
