// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: plugin_official.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginOfficialInstallReq describes the plugin official install request.
type PluginOfficialInstallReq struct {
	state                       protoimpl.MessageState                    `protogen:"open.v1"`
	Plugin                      []*PluginOfficialInstallReq_Plugin        `protobuf:"bytes,1,rep,name=plugin,proto3" json:"plugin"`
	TargetVersion               []*PluginOfficialInstallReq_TargetVersion `protobuf:"bytes,2,rep,name=target_version,json=targetVersion,proto3" json:"target_version"`
	DisableDefaultTargetVersion bool                                      `protobuf:"varint,3,opt,name=disable_default_target_version,json=disableDefaultTargetVersion,proto3" json:"disable_default_target_version"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PluginOfficialInstallReq) Reset() {
	*x = PluginOfficialInstallReq{}
	mi := &file_plugin_official_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOfficialInstallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOfficialInstallReq) ProtoMessage() {}

func (x *PluginOfficialInstallReq) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_official_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOfficialInstallReq.ProtoReflect.Descriptor instead.
func (*PluginOfficialInstallReq) Descriptor() ([]byte, []int) {
	return file_plugin_official_proto_rawDescGZIP(), []int{0}
}

func (x *PluginOfficialInstallReq) GetPlugin() []*PluginOfficialInstallReq_Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

func (x *PluginOfficialInstallReq) GetTargetVersion() []*PluginOfficialInstallReq_TargetVersion {
	if x != nil {
		return x.TargetVersion
	}
	return nil
}

func (x *PluginOfficialInstallReq) GetDisableDefaultTargetVersion() bool {
	if x != nil {
		return x.DisableDefaultTargetVersion
	}
	return false
}

// PluginOfficialInstallResp describes the plugin official install response.
type PluginOfficialInstallResp struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                          `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Error         *Error                          `protobuf:"bytes,4,opt,name=error,proto3" json:"error"`
	Data          *PluginOfficialInstallResp_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOfficialInstallResp) Reset() {
	*x = PluginOfficialInstallResp{}
	mi := &file_plugin_official_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOfficialInstallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOfficialInstallResp) ProtoMessage() {}

func (x *PluginOfficialInstallResp) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_official_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOfficialInstallResp.ProtoReflect.Descriptor instead.
func (*PluginOfficialInstallResp) Descriptor() ([]byte, []int) {
	return file_plugin_official_proto_rawDescGZIP(), []int{1}
}

func (x *PluginOfficialInstallResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PluginOfficialInstallResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginOfficialInstallResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PluginOfficialInstallResp) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PluginOfficialInstallResp) GetData() *PluginOfficialInstallResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type PluginOfficialInstallReq_Plugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BkHostId      *int64                 `protobuf:"varint,1,opt,name=bk_host_id,json=bkHostId,proto3,oneof" json:"bk_host_id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOfficialInstallReq_Plugin) Reset() {
	*x = PluginOfficialInstallReq_Plugin{}
	mi := &file_plugin_official_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOfficialInstallReq_Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOfficialInstallReq_Plugin) ProtoMessage() {}

func (x *PluginOfficialInstallReq_Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_official_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOfficialInstallReq_Plugin.ProtoReflect.Descriptor instead.
func (*PluginOfficialInstallReq_Plugin) Descriptor() ([]byte, []int) {
	return file_plugin_official_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PluginOfficialInstallReq_Plugin) GetBkHostId() int64 {
	if x != nil && x.BkHostId != nil {
		return *x.BkHostId
	}
	return 0
}

func (x *PluginOfficialInstallReq_Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginOfficialInstallReq_Plugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PluginOfficialInstallReq_TargetVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	CpuArch       string                 `protobuf:"bytes,2,opt,name=cpu_arch,json=cpuArch,proto3" json:"cpu_arch"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOfficialInstallReq_TargetVersion) Reset() {
	*x = PluginOfficialInstallReq_TargetVersion{}
	mi := &file_plugin_official_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOfficialInstallReq_TargetVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOfficialInstallReq_TargetVersion) ProtoMessage() {}

func (x *PluginOfficialInstallReq_TargetVersion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_official_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOfficialInstallReq_TargetVersion.ProtoReflect.Descriptor instead.
func (*PluginOfficialInstallReq_TargetVersion) Descriptor() ([]byte, []int) {
	return file_plugin_official_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PluginOfficialInstallReq_TargetVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginOfficialInstallReq_TargetVersion) GetCpuArch() string {
	if x != nil {
		return x.CpuArch
	}
	return ""
}

func (x *PluginOfficialInstallReq_TargetVersion) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

type PluginOfficialInstallResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginOfficialInstallResp_Data) Reset() {
	*x = PluginOfficialInstallResp_Data{}
	mi := &file_plugin_official_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginOfficialInstallResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginOfficialInstallResp_Data) ProtoMessage() {}

func (x *PluginOfficialInstallResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_official_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginOfficialInstallResp_Data.ProtoReflect.Descriptor instead.
func (*PluginOfficialInstallResp_Data) Descriptor() ([]byte, []int) {
	return file_plugin_official_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PluginOfficialInstallResp_Data) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

var File_plugin_official_proto protoreflect.FileDescriptor

var file_plugin_official_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x33, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x03, 0x0a, 0x18, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x33, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x12, 0x51, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x76, 0x33, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x1e, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1b, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x68, 0x0a, 0x06, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0a, 0x62, 0x6b, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x62, 0x6b, 0x48, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x62, 0x6b, 0x5f, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x1a, 0x5d, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x70, 0x75, 0x41, 0x72, 0x63, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x22, 0xea, 0x01, 0x0a, 0x19, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x76,
	0x33, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x36,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x76,
	0x33, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x27, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x42,
	0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65,
	0x6e, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x75, 0x65, 0x4b, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6b,
	0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x6d, 0x67, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_plugin_official_proto_rawDescOnce sync.Once
	file_plugin_official_proto_rawDescData []byte
)

func file_plugin_official_proto_rawDescGZIP() []byte {
	file_plugin_official_proto_rawDescOnce.Do(func() {
		file_plugin_official_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_official_proto_rawDesc), len(file_plugin_official_proto_rawDesc)))
	})
	return file_plugin_official_proto_rawDescData
}

var file_plugin_official_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_official_proto_goTypes = []any{
	(*PluginOfficialInstallReq)(nil),               // 0: v3.PluginOfficialInstallReq
	(*PluginOfficialInstallResp)(nil),              // 1: v3.PluginOfficialInstallResp
	(*PluginOfficialInstallReq_Plugin)(nil),        // 2: v3.PluginOfficialInstallReq.Plugin
	(*PluginOfficialInstallReq_TargetVersion)(nil), // 3: v3.PluginOfficialInstallReq.TargetVersion
	(*PluginOfficialInstallResp_Data)(nil),         // 4: v3.PluginOfficialInstallResp.Data
	(*Error)(nil),                                  // 5: v3.Error
}
var file_plugin_official_proto_depIdxs = []int32{
	2, // 0: v3.PluginOfficialInstallReq.plugin:type_name -> v3.PluginOfficialInstallReq.Plugin
	3, // 1: v3.PluginOfficialInstallReq.target_version:type_name -> v3.PluginOfficialInstallReq.TargetVersion
	5, // 2: v3.PluginOfficialInstallResp.error:type_name -> v3.Error
	4, // 3: v3.PluginOfficialInstallResp.data:type_name -> v3.PluginOfficialInstallResp.Data
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_official_proto_init() }
func file_plugin_official_proto_init() {
	if File_plugin_official_proto != nil {
		return
	}
	file_common_proto_init()
	file_plugin_official_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_official_proto_rawDesc), len(file_plugin_official_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_official_proto_goTypes,
		DependencyIndexes: file_plugin_official_proto_depIdxs,
		MessageInfos:      file_plugin_official_proto_msgTypes,
	}.Build()
	File_plugin_official_proto = out.File
	file_plugin_official_proto_goTypes = nil
	file_plugin_official_proto_depIdxs = nil
}
