// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: schedule_workflow.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnableScheduleWorkflowReq describes the HTTP request body when enable
// schedule workflow.
type EnableScheduleWorkflowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableScheduleWorkflowReq) Reset() {
	*x = EnableScheduleWorkflowReq{}
	mi := &file_schedule_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableScheduleWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableScheduleWorkflowReq) ProtoMessage() {}

func (x *EnableScheduleWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableScheduleWorkflowReq.ProtoReflect.Descriptor instead.
func (*EnableScheduleWorkflowReq) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *EnableScheduleWorkflowReq) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

// EnableScheduleWorkflowResp describes the HTTP response body when enable
// schedule workflow.
type EnableScheduleWorkflowResp struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Code          int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                           `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *EnableScheduleWorkflowResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableScheduleWorkflowResp) Reset() {
	*x = EnableScheduleWorkflowResp{}
	mi := &file_schedule_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableScheduleWorkflowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableScheduleWorkflowResp) ProtoMessage() {}

func (x *EnableScheduleWorkflowResp) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableScheduleWorkflowResp.ProtoReflect.Descriptor instead.
func (*EnableScheduleWorkflowResp) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *EnableScheduleWorkflowResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EnableScheduleWorkflowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnableScheduleWorkflowResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnableScheduleWorkflowResp) GetData() *EnableScheduleWorkflowResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// DisableScheduleWorkflowReq describes the HTTP request body when disable
// schedule workflow.
type DisableScheduleWorkflowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableScheduleWorkflowReq) Reset() {
	*x = DisableScheduleWorkflowReq{}
	mi := &file_schedule_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableScheduleWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableScheduleWorkflowReq) ProtoMessage() {}

func (x *DisableScheduleWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableScheduleWorkflowReq.ProtoReflect.Descriptor instead.
func (*DisableScheduleWorkflowReq) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *DisableScheduleWorkflowReq) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

// DisableScheduleWorkflowResp describes the HTTP response body when disable
// schedule workflow.
type DisableScheduleWorkflowResp struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Code          int32                             `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                            `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *DisableScheduleWorkflowResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableScheduleWorkflowResp) Reset() {
	*x = DisableScheduleWorkflowResp{}
	mi := &file_schedule_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableScheduleWorkflowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableScheduleWorkflowResp) ProtoMessage() {}

func (x *DisableScheduleWorkflowResp) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableScheduleWorkflowResp.ProtoReflect.Descriptor instead.
func (*DisableScheduleWorkflowResp) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *DisableScheduleWorkflowResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DisableScheduleWorkflowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DisableScheduleWorkflowResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DisableScheduleWorkflowResp) GetData() *DisableScheduleWorkflowResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ScheduleWorkflowExactConditions describes the exact conditions of schedule
// workflow list request.
type ScheduleWorkflowExactConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    []string               `protobuf:"bytes,1,rep,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	WorkflowName  []string               `protobuf:"bytes,2,rep,name=workflow_name,json=workflowName,proto3" json:"workflow_name"`
	Operator      []string               `protobuf:"bytes,3,rep,name=operator,proto3" json:"operator"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkflowExactConditions) Reset() {
	*x = ScheduleWorkflowExactConditions{}
	mi := &file_schedule_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkflowExactConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkflowExactConditions) ProtoMessage() {}

func (x *ScheduleWorkflowExactConditions) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkflowExactConditions.ProtoReflect.Descriptor instead.
func (*ScheduleWorkflowExactConditions) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleWorkflowExactConditions) GetWorkflowId() []string {
	if x != nil {
		return x.WorkflowId
	}
	return nil
}

func (x *ScheduleWorkflowExactConditions) GetWorkflowName() []string {
	if x != nil {
		return x.WorkflowName
	}
	return nil
}

func (x *ScheduleWorkflowExactConditions) GetOperator() []string {
	if x != nil {
		return x.Operator
	}
	return nil
}

// ScheduleWorkflowFuzzyConditions describes the fuzzy conditions of schedule
// workflow list request.
type ScheduleWorkflowFuzzyConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkflowFuzzyConditions) Reset() {
	*x = ScheduleWorkflowFuzzyConditions{}
	mi := &file_schedule_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkflowFuzzyConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkflowFuzzyConditions) ProtoMessage() {}

func (x *ScheduleWorkflowFuzzyConditions) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkflowFuzzyConditions.ProtoReflect.Descriptor instead.
func (*ScheduleWorkflowFuzzyConditions) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{5}
}

// ListScheduleWorkflowReq describes the HTTP request body when list schedule
// workflow.
type ListScheduleWorkflowReq struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	Page                   *Page                            `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	OnlyCount              bool                             `protobuf:"varint,2,opt,name=only_count,json=onlyCount,proto3" json:"only_count"`
	ExactIncludeConditions *ScheduleWorkflowExactConditions `protobuf:"bytes,3,opt,name=exact_include_conditions,json=exactIncludeConditions,proto3" json:"exact_include_conditions"`
	FuzzyIncludeConditions *ScheduleWorkflowFuzzyConditions `protobuf:"bytes,4,opt,name=fuzzy_include_conditions,json=fuzzyIncludeConditions,proto3" json:"fuzzy_include_conditions"`
	OperateTimeRange       *TimeRange                       `protobuf:"bytes,5,opt,name=operate_time_range,json=operateTimeRange,proto3" json:"operate_time_range"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListScheduleWorkflowReq) Reset() {
	*x = ListScheduleWorkflowReq{}
	mi := &file_schedule_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleWorkflowReq) ProtoMessage() {}

func (x *ListScheduleWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleWorkflowReq.ProtoReflect.Descriptor instead.
func (*ListScheduleWorkflowReq) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *ListScheduleWorkflowReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListScheduleWorkflowReq) GetOnlyCount() bool {
	if x != nil {
		return x.OnlyCount
	}
	return false
}

func (x *ListScheduleWorkflowReq) GetExactIncludeConditions() *ScheduleWorkflowExactConditions {
	if x != nil {
		return x.ExactIncludeConditions
	}
	return nil
}

func (x *ListScheduleWorkflowReq) GetFuzzyIncludeConditions() *ScheduleWorkflowFuzzyConditions {
	if x != nil {
		return x.FuzzyIncludeConditions
	}
	return nil
}

func (x *ListScheduleWorkflowReq) GetOperateTimeRange() *TimeRange {
	if x != nil {
		return x.OperateTimeRange
	}
	return nil
}

// ScheduleWorkflow describes the schedule workflow
type ScheduleWorkflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    *string                `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3,oneof" json:"workflow_id"`
	WorkflowName  *string                `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3,oneof" json:"workflow_name"`
	TriggerId     *string                `protobuf:"bytes,3,opt,name=trigger_id,json=triggerId,proto3,oneof" json:"trigger_id"`
	Operator      *string                `protobuf:"bytes,4,opt,name=operator,proto3,oneof" json:"operator"`
	OperateTime   *int64                 `protobuf:"varint,5,opt,name=operate_time,json=operateTime,proto3,oneof" json:"operate_time"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkflow) Reset() {
	*x = ScheduleWorkflow{}
	mi := &file_schedule_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkflow) ProtoMessage() {}

func (x *ScheduleWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkflow.ProtoReflect.Descriptor instead.
func (*ScheduleWorkflow) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleWorkflow) GetWorkflowId() string {
	if x != nil && x.WorkflowId != nil {
		return *x.WorkflowId
	}
	return ""
}

func (x *ScheduleWorkflow) GetWorkflowName() string {
	if x != nil && x.WorkflowName != nil {
		return *x.WorkflowName
	}
	return ""
}

func (x *ScheduleWorkflow) GetTriggerId() string {
	if x != nil && x.TriggerId != nil {
		return *x.TriggerId
	}
	return ""
}

func (x *ScheduleWorkflow) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *ScheduleWorkflow) GetOperateTime() int64 {
	if x != nil && x.OperateTime != nil {
		return *x.OperateTime
	}
	return 0
}

// ListScheduleWorkflowResp describes the HTTP response body when list schedule
// workflow.
type ListScheduleWorkflowResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                         `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ListScheduleWorkflowResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleWorkflowResp) Reset() {
	*x = ListScheduleWorkflowResp{}
	mi := &file_schedule_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleWorkflowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleWorkflowResp) ProtoMessage() {}

func (x *ListScheduleWorkflowResp) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleWorkflowResp.ProtoReflect.Descriptor instead.
func (*ListScheduleWorkflowResp) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *ListScheduleWorkflowResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListScheduleWorkflowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListScheduleWorkflowResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListScheduleWorkflowResp) GetData() *ListScheduleWorkflowResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type EnableScheduleWorkflowResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableScheduleWorkflowResp_Data) Reset() {
	*x = EnableScheduleWorkflowResp_Data{}
	mi := &file_schedule_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableScheduleWorkflowResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableScheduleWorkflowResp_Data) ProtoMessage() {}

func (x *EnableScheduleWorkflowResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableScheduleWorkflowResp_Data.ProtoReflect.Descriptor instead.
func (*EnableScheduleWorkflowResp_Data) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{1, 0}
}

type DisableScheduleWorkflowResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableScheduleWorkflowResp_Data) Reset() {
	*x = DisableScheduleWorkflowResp_Data{}
	mi := &file_schedule_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableScheduleWorkflowResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableScheduleWorkflowResp_Data) ProtoMessage() {}

func (x *DisableScheduleWorkflowResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableScheduleWorkflowResp_Data.ProtoReflect.Descriptor instead.
func (*DisableScheduleWorkflowResp_Data) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{3, 0}
}

type ListScheduleWorkflowResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Items         []*ScheduleWorkflow    `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleWorkflowResp_Data) Reset() {
	*x = ListScheduleWorkflowResp_Data{}
	mi := &file_schedule_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleWorkflowResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleWorkflowResp_Data) ProtoMessage() {}

func (x *ListScheduleWorkflowResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_schedule_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleWorkflowResp_Data.ProtoReflect.Descriptor instead.
func (*ListScheduleWorkflowResp_Data) Descriptor() ([]byte, []int) {
	return file_schedule_workflow_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListScheduleWorkflowResp_Data) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListScheduleWorkflowResp_Data) GetItems() []*ScheduleWorkflow {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_schedule_workflow_proto protoreflect.FileDescriptor

const file_schedule_workflow_proto_rawDesc = "" +
	"\n" +
	"\x17schedule_workflow.proto\x12\x02v3\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"<\n" +
	"\x19EnableScheduleWorkflowReq\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xaa\x01\n" +
	"\x1aEnableScheduleWorkflowResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x127\n" +
	"\x04data\x18\x04 \x01(\v2#.v3.EnableScheduleWorkflowResp.DataR\x04data\x1a\x06\n" +
	"\x04Data\"=\n" +
	"\x1aDisableScheduleWorkflowReq\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xac\x01\n" +
	"\x1bDisableScheduleWorkflowResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x128\n" +
	"\x04data\x18\x04 \x01(\v2$.v3.DisableScheduleWorkflowResp.DataR\x04data\x1a\x06\n" +
	"\x04Data\"\x83\x01\n" +
	"\x1fScheduleWorkflowExactConditions\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x03(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_name\x18\x02 \x03(\tR\fworkflowName\x12\x1a\n" +
	"\boperator\x18\x03 \x03(\tR\boperator\"!\n" +
	"\x1fScheduleWorkflowFuzzyConditions\"\xd1\x02\n" +
	"\x17ListScheduleWorkflowReq\x12\x1c\n" +
	"\x04page\x18\x01 \x01(\v2\b.v3.PageR\x04page\x12\x1d\n" +
	"\n" +
	"only_count\x18\x02 \x01(\bR\tonlyCount\x12]\n" +
	"\x18exact_include_conditions\x18\x03 \x01(\v2#.v3.ScheduleWorkflowExactConditionsR\x16exactIncludeConditions\x12]\n" +
	"\x18fuzzy_include_conditions\x18\x04 \x01(\v2#.v3.ScheduleWorkflowFuzzyConditionsR\x16fuzzyIncludeConditions\x12;\n" +
	"\x12operate_time_range\x18\x05 \x01(\v2\r.v3.TimeRangeR\x10operateTimeRange\"\x9e\x02\n" +
	"\x10ScheduleWorkflow\x12$\n" +
	"\vworkflow_id\x18\x01 \x01(\tH\x00R\n" +
	"workflowId\x88\x01\x01\x12(\n" +
	"\rworkflow_name\x18\x02 \x01(\tH\x01R\fworkflowName\x88\x01\x01\x12\"\n" +
	"\n" +
	"trigger_id\x18\x03 \x01(\tH\x02R\ttriggerId\x88\x01\x01\x12\x1f\n" +
	"\boperator\x18\x04 \x01(\tH\x03R\boperator\x88\x01\x01\x12&\n" +
	"\foperate_time\x18\x05 \x01(\x03H\x04R\voperateTime\x88\x01\x01B\x0e\n" +
	"\f_workflow_idB\x10\n" +
	"\x0e_workflow_nameB\r\n" +
	"\v_trigger_idB\v\n" +
	"\t_operatorB\x0f\n" +
	"\r_operate_time\"\xe8\x01\n" +
	"\x18ListScheduleWorkflowResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x125\n" +
	"\x04data\x18\x04 \x01(\v2!.v3.ListScheduleWorkflowResp.DataR\x04data\x1aH\n" +
	"\x04Data\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.v3.ScheduleWorkflowR\x05items2\x9a\x03\n" +
	"\bSchedule\x12\x84\x01\n" +
	"\x16EnableScheduleWorkflow\x12\x1d.v3.EnableScheduleWorkflowReq\x1a\x1e.v3.EnableScheduleWorkflowResp\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v3/schedule/workflow/enable\x12\x88\x01\n" +
	"\x17DisableScheduleWorkflow\x12\x1e.v3.DisableScheduleWorkflowReq\x1a\x1f.v3.DisableScheduleWorkflowResp\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v3/schedule/workflow/disable\x12|\n" +
	"\x14ListScheduleWorkflow\x12\x1b.v3.ListScheduleWorkflowReq\x1a\x1c.v3.ListScheduleWorkflowResp\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v3/schedule/workflow/listBCZAgithub.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3b\x06proto3"

var (
	file_schedule_workflow_proto_rawDescOnce sync.Once
	file_schedule_workflow_proto_rawDescData []byte
)

func file_schedule_workflow_proto_rawDescGZIP() []byte {
	file_schedule_workflow_proto_rawDescOnce.Do(func() {
		file_schedule_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schedule_workflow_proto_rawDesc), len(file_schedule_workflow_proto_rawDesc)))
	})
	return file_schedule_workflow_proto_rawDescData
}

var file_schedule_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_schedule_workflow_proto_goTypes = []any{
	(*EnableScheduleWorkflowReq)(nil),        // 0: v3.EnableScheduleWorkflowReq
	(*EnableScheduleWorkflowResp)(nil),       // 1: v3.EnableScheduleWorkflowResp
	(*DisableScheduleWorkflowReq)(nil),       // 2: v3.DisableScheduleWorkflowReq
	(*DisableScheduleWorkflowResp)(nil),      // 3: v3.DisableScheduleWorkflowResp
	(*ScheduleWorkflowExactConditions)(nil),  // 4: v3.ScheduleWorkflowExactConditions
	(*ScheduleWorkflowFuzzyConditions)(nil),  // 5: v3.ScheduleWorkflowFuzzyConditions
	(*ListScheduleWorkflowReq)(nil),          // 6: v3.ListScheduleWorkflowReq
	(*ScheduleWorkflow)(nil),                 // 7: v3.ScheduleWorkflow
	(*ListScheduleWorkflowResp)(nil),         // 8: v3.ListScheduleWorkflowResp
	(*EnableScheduleWorkflowResp_Data)(nil),  // 9: v3.EnableScheduleWorkflowResp.Data
	(*DisableScheduleWorkflowResp_Data)(nil), // 10: v3.DisableScheduleWorkflowResp.Data
	(*ListScheduleWorkflowResp_Data)(nil),    // 11: v3.ListScheduleWorkflowResp.Data
	(*Page)(nil),                             // 12: v3.Page
	(*TimeRange)(nil),                        // 13: v3.TimeRange
}
var file_schedule_workflow_proto_depIdxs = []int32{
	9,  // 0: v3.EnableScheduleWorkflowResp.data:type_name -> v3.EnableScheduleWorkflowResp.Data
	10, // 1: v3.DisableScheduleWorkflowResp.data:type_name -> v3.DisableScheduleWorkflowResp.Data
	12, // 2: v3.ListScheduleWorkflowReq.page:type_name -> v3.Page
	4,  // 3: v3.ListScheduleWorkflowReq.exact_include_conditions:type_name -> v3.ScheduleWorkflowExactConditions
	5,  // 4: v3.ListScheduleWorkflowReq.fuzzy_include_conditions:type_name -> v3.ScheduleWorkflowFuzzyConditions
	13, // 5: v3.ListScheduleWorkflowReq.operate_time_range:type_name -> v3.TimeRange
	11, // 6: v3.ListScheduleWorkflowResp.data:type_name -> v3.ListScheduleWorkflowResp.Data
	7,  // 7: v3.ListScheduleWorkflowResp.Data.items:type_name -> v3.ScheduleWorkflow
	0,  // 8: v3.Schedule.EnableScheduleWorkflow:input_type -> v3.EnableScheduleWorkflowReq
	2,  // 9: v3.Schedule.DisableScheduleWorkflow:input_type -> v3.DisableScheduleWorkflowReq
	6,  // 10: v3.Schedule.ListScheduleWorkflow:input_type -> v3.ListScheduleWorkflowReq
	1,  // 11: v3.Schedule.EnableScheduleWorkflow:output_type -> v3.EnableScheduleWorkflowResp
	3,  // 12: v3.Schedule.DisableScheduleWorkflow:output_type -> v3.DisableScheduleWorkflowResp
	8,  // 13: v3.Schedule.ListScheduleWorkflow:output_type -> v3.ListScheduleWorkflowResp
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_schedule_workflow_proto_init() }
func file_schedule_workflow_proto_init() {
	if File_schedule_workflow_proto != nil {
		return
	}
	file_common_proto_init()
	file_schedule_workflow_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schedule_workflow_proto_rawDesc), len(file_schedule_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schedule_workflow_proto_goTypes,
		DependencyIndexes: file_schedule_workflow_proto_depIdxs,
		MessageInfos:      file_schedule_workflow_proto_msgTypes,
	}.Build()
	File_schedule_workflow_proto = out.File
	file_schedule_workflow_proto_goTypes = nil
	file_schedule_workflow_proto_depIdxs = nil
}
