// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: workflow.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperationRetryReq describes the operation retry request.
type OperationRetryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id"`
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRetryReq) Reset() {
	*x = OperationRetryReq{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRetryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRetryReq) ProtoMessage() {}

func (x *OperationRetryReq) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRetryReq.ProtoReflect.Descriptor instead.
func (*OperationRetryReq) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRetryReq) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRetryReq) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

// OperationRetryResp describes the operation retry response.
type OperationRetryResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                   `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *OperationRetryResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRetryResp) Reset() {
	*x = OperationRetryResp{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRetryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRetryResp) ProtoMessage() {}

func (x *OperationRetryResp) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRetryResp.ProtoReflect.Descriptor instead.
func (*OperationRetryResp) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *OperationRetryResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperationRetryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationRetryResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OperationRetryResp) GetData() *OperationRetryResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type OperationRetryResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id"`
	ActionName    string                 `protobuf:"bytes,3,opt,name=action_name,json=actionName,proto3" json:"action_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRetryResp_Data) Reset() {
	*x = OperationRetryResp_Data{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRetryResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRetryResp_Data) ProtoMessage() {}

func (x *OperationRetryResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRetryResp_Data.ProtoReflect.Descriptor instead.
func (*OperationRetryResp_Data) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OperationRetryResp_Data) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *OperationRetryResp_Data) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRetryResp_Data) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\x02v3\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x11OperationRetryReq\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\"\xff\x01\n" +
	"\x12OperationRetryResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12/\n" +
	"\x04data\x18\x04 \x01(\v2\x1b.v3.OperationRetryResp.DataR\x04data\x1ak\n" +
	"\x04Data\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x1f\n" +
	"\vaction_name\x18\x03 \x01(\tR\n" +
	"actionNameBCZAgithub.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3b\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workflow_proto_goTypes = []any{
	(*OperationRetryReq)(nil),       // 0: v3.OperationRetryReq
	(*OperationRetryResp)(nil),      // 1: v3.OperationRetryResp
	(*OperationRetryResp_Data)(nil), // 2: v3.OperationRetryResp.Data
}
var file_workflow_proto_depIdxs = []int32{
	2, // 0: v3.OperationRetryResp.data:type_name -> v3.OperationRetryResp.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
