// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: workflow.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorflowOperationInstanceData describes the workflow operation instance data.
type WorflowOperationInstanceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationId               string                       `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id"`
	OperInstId                string                       `protobuf:"bytes,2,opt,name=oper_inst_id,json=operInstId,proto3" json:"oper_inst_id"`
	OperInstStatus            string                       `protobuf:"bytes,3,opt,name=oper_inst_status,json=operInstStatus,proto3" json:"oper_inst_status"`
	OperationDefName          string                       `protobuf:"bytes,4,opt,name=operation_def_name,json=operationDefName,proto3" json:"operation_def_name"`
	ParentOperationId         string                       `protobuf:"bytes,5,opt,name=parent_operation_id,json=parentOperationId,proto3" json:"parent_operation_id"`
	ActionNames               []string                     `protobuf:"bytes,6,rep,name=action_names,json=actionNames,proto3" json:"action_names"`
	LifeCycle                 *WorkflowLifeCycle           `protobuf:"bytes,7,opt,name=life_cycle,json=lifeCycle,proto3" json:"life_cycle"`
	LatestActionInstBriefData *WorkflowActionInstBriefData `protobuf:"bytes,8,opt,name=latest_action_inst_brief_data,json=latestActionInstBriefData,proto3" json:"latest_action_inst_brief_data"`
}

func (x *WorflowOperationInstanceData) Reset() {
	*x = WorflowOperationInstanceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorflowOperationInstanceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorflowOperationInstanceData) ProtoMessage() {}

func (x *WorflowOperationInstanceData) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorflowOperationInstanceData.ProtoReflect.Descriptor instead.
func (*WorflowOperationInstanceData) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorflowOperationInstanceData) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *WorflowOperationInstanceData) GetOperInstId() string {
	if x != nil {
		return x.OperInstId
	}
	return ""
}

func (x *WorflowOperationInstanceData) GetOperInstStatus() string {
	if x != nil {
		return x.OperInstStatus
	}
	return ""
}

func (x *WorflowOperationInstanceData) GetOperationDefName() string {
	if x != nil {
		return x.OperationDefName
	}
	return ""
}

func (x *WorflowOperationInstanceData) GetParentOperationId() string {
	if x != nil {
		return x.ParentOperationId
	}
	return ""
}

func (x *WorflowOperationInstanceData) GetActionNames() []string {
	if x != nil {
		return x.ActionNames
	}
	return nil
}

func (x *WorflowOperationInstanceData) GetLifeCycle() *WorkflowLifeCycle {
	if x != nil {
		return x.LifeCycle
	}
	return nil
}

func (x *WorflowOperationInstanceData) GetLatestActionInstBriefData() *WorkflowActionInstBriefData {
	if x != nil {
		return x.LatestActionInstBriefData
	}
	return nil
}

// WorkflowLifeCycle describes the workflow life cycle.
type WorkflowLifeCycle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State      string `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
	CreateTime int64  `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	StartTime  int64  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time"`
	EndTime    int64  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time"`
	StopTime   int64  `protobuf:"varint,5,opt,name=stop_time,json=stopTime,proto3" json:"stop_time"`
}

func (x *WorkflowLifeCycle) Reset() {
	*x = WorkflowLifeCycle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowLifeCycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowLifeCycle) ProtoMessage() {}

func (x *WorkflowLifeCycle) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowLifeCycle.ProtoReflect.Descriptor instead.
func (*WorkflowLifeCycle) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowLifeCycle) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WorkflowLifeCycle) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *WorkflowLifeCycle) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *WorkflowLifeCycle) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *WorkflowLifeCycle) GetStopTime() int64 {
	if x != nil {
		return x.StopTime
	}
	return 0
}

// WorkflowActionInstBriefData describes the workflow action instance brief
// data.
type WorkflowActionInstBriefData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags"`
}

func (x *WorkflowActionInstBriefData) Reset() {
	*x = WorkflowActionInstBriefData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowActionInstBriefData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowActionInstBriefData) ProtoMessage() {}

func (x *WorkflowActionInstBriefData) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowActionInstBriefData.ProtoReflect.Descriptor instead.
func (*WorkflowActionInstBriefData) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowActionInstBriefData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowActionInstBriefData) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// SubWorkflowRef describes a child workflow reference surfaced in action logs.
type SubWorkflowRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkflowId     string `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	WorkflowDomain string `protobuf:"bytes,2,opt,name=workflow_domain,json=workflowDomain,proto3" json:"workflow_domain"`
}

func (x *SubWorkflowRef) Reset() {
	*x = SubWorkflowRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubWorkflowRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubWorkflowRef) ProtoMessage() {}

func (x *SubWorkflowRef) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubWorkflowRef.ProtoReflect.Descriptor instead.
func (*SubWorkflowRef) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *SubWorkflowRef) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SubWorkflowRef) GetWorkflowDomain() string {
	if x != nil {
		return x.WorkflowDomain
	}
	return ""
}

// WorkflowActionData describes the workflow action data.
type WorkflowActionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LifeCycle       *WorkflowLifeCycle     `protobuf:"bytes,1,opt,name=life_cycle,json=lifeCycle,proto3" json:"life_cycle"`
	Message         *WorkflowActionMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	DisplayNameZh   string                 `protobuf:"bytes,3,opt,name=display_name_zh,json=displayNameZh,proto3" json:"display_name_zh"` // Chinese display name
	DisplayNameEn   string                 `protobuf:"bytes,4,opt,name=display_name_en,json=displayNameEn,proto3" json:"display_name_en"` // English display name
	SubWorkflowRefs []*SubWorkflowRef      `protobuf:"bytes,5,rep,name=sub_workflow_refs,json=subWorkflowRefs,proto3" json:"sub_workflow_refs"`
}

func (x *WorkflowActionData) Reset() {
	*x = WorkflowActionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowActionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowActionData) ProtoMessage() {}

func (x *WorkflowActionData) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowActionData.ProtoReflect.Descriptor instead.
func (*WorkflowActionData) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowActionData) GetLifeCycle() *WorkflowLifeCycle {
	if x != nil {
		return x.LifeCycle
	}
	return nil
}

func (x *WorkflowActionData) GetMessage() *WorkflowActionMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkflowActionData) GetDisplayNameZh() string {
	if x != nil {
		return x.DisplayNameZh
	}
	return ""
}

func (x *WorkflowActionData) GetDisplayNameEn() string {
	if x != nil {
		return x.DisplayNameEn
	}
	return ""
}

func (x *WorkflowActionData) GetSubWorkflowRefs() []*SubWorkflowRef {
	if x != nil {
		return x.SubWorkflowRefs
	}
	return nil
}

// WorkflowActionMessage describes the workflow action message logs.
type WorkflowActionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*WorkflowActionMessage_Message `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs"`
}

func (x *WorkflowActionMessage) Reset() {
	*x = WorkflowActionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowActionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowActionMessage) ProtoMessage() {}

func (x *WorkflowActionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowActionMessage.ProtoReflect.Descriptor instead.
func (*WorkflowActionMessage) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowActionMessage) GetLogs() []*WorkflowActionMessage_Message {
	if x != nil {
		return x.Logs
	}
	return nil
}

// WorkflowOperationInstanceStatus describes the workflow operation instance
// status.
type WorkflowOperationInstanceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index               int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index"`
	OperationId         string `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id"`
	Status              string `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	TriggerId           string `protobuf:"bytes,4,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id"`
	OperationInstanceId string `protobuf:"bytes,5,opt,name=operation_instance_id,json=operationInstanceId,proto3" json:"operation_instance_id"`
}

func (x *WorkflowOperationInstanceStatus) Reset() {
	*x = WorkflowOperationInstanceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowOperationInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOperationInstanceStatus) ProtoMessage() {}

func (x *WorkflowOperationInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOperationInstanceStatus.ProtoReflect.Descriptor instead.
func (*WorkflowOperationInstanceStatus) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowOperationInstanceStatus) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WorkflowOperationInstanceStatus) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *WorkflowOperationInstanceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowOperationInstanceStatus) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *WorkflowOperationInstanceStatus) GetOperationInstanceId() string {
	if x != nil {
		return x.OperationInstanceId
	}
	return ""
}

type WorkflowActionMessage_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time   int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	Level  string `protobuf:"bytes,3,opt,name=level,proto3" json:"level"`
	TextZh string `protobuf:"bytes,4,opt,name=text_zh,json=textZh,proto3" json:"text_zh"` // Chinese log content
	TextEn string `protobuf:"bytes,5,opt,name=text_en,json=textEn,proto3" json:"text_en"` // English log content
}

func (x *WorkflowActionMessage_Message) Reset() {
	*x = WorkflowActionMessage_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowActionMessage_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowActionMessage_Message) ProtoMessage() {}

func (x *WorkflowActionMessage_Message) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowActionMessage_Message.ProtoReflect.Descriptor instead.
func (*WorkflowActionMessage_Message) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5, 0}
}

func (x *WorkflowActionMessage_Message) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *WorkflowActionMessage_Message) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *WorkflowActionMessage_Message) GetTextZh() string {
	if x != nil {
		return x.TextZh
	}
	return ""
}

func (x *WorkflowActionMessage_Message) GetTextEn() string {
	if x != nil {
		return x.TextEn
	}
	return ""
}

var File_workflow_proto protoreflect.FileDescriptor

var file_workflow_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x76, 0x33, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa7, 0x03, 0x0a, 0x1c, 0x57, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72,
	0x49, 0x6e, 0x73, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x65,
	0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x34, 0x0a, 0x0a, 0x6c, 0x69, 0x66, 0x65, 0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x33, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x66, 0x65, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x09, 0x6c, 0x69,
	0x66, 0x65, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x61, 0x0a, 0x1d, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x5f, 0x62, 0x72,
	0x69, 0x65, 0x66, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x76, 0x33, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x19, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73,
	0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x57,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x66, 0x65, 0x43, 0x79, 0x63, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x45,
	0x0a, 0x1b, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x73, 0x74, 0x42, 0x72, 0x69, 0x65, 0x66, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x5a, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x57, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x8f, 0x02, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x0a, 0x6c, 0x69, 0x66, 0x65,
	0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76,
	0x33, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x66, 0x65, 0x43, 0x79,
	0x63, 0x6c, 0x65, 0x52, 0x09, 0x6c, 0x69, 0x66, 0x65, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x33,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x76, 0x33, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x5a, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x45, 0x6e, 0x12, 0x3e, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x65, 0x66, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x76, 0x33, 0x2e, 0x53, 0x75, 0x62, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52,
	0x65, 0x66, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52,
	0x65, 0x66, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x15, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a,
	0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x33,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04,
	0x6c, 0x6f, 0x67, 0x73, 0x1a, 0x6b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x78,
	0x74, 0x5f, 0x7a, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x78, 0x74,
	0x5a, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x65, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x4a, 0x04, 0x08, 0x02, 0x10,
	0x03, 0x22, 0xc5, 0x01, 0x0a, 0x1f, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x42,
	0x6c, 0x75, 0x65, 0x4b, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6b, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x6d,
	0x67, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x33, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData = file_workflow_proto_rawDesc
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_workflow_proto_rawDescData)
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workflow_proto_goTypes = []interface{}{
	(*WorflowOperationInstanceData)(nil),    // 0: v3.WorflowOperationInstanceData
	(*WorkflowLifeCycle)(nil),               // 1: v3.WorkflowLifeCycle
	(*WorkflowActionInstBriefData)(nil),     // 2: v3.WorkflowActionInstBriefData
	(*SubWorkflowRef)(nil),                  // 3: v3.SubWorkflowRef
	(*WorkflowActionData)(nil),              // 4: v3.WorkflowActionData
	(*WorkflowActionMessage)(nil),           // 5: v3.WorkflowActionMessage
	(*WorkflowOperationInstanceStatus)(nil), // 6: v3.WorkflowOperationInstanceStatus
	(*WorkflowActionMessage_Message)(nil),   // 7: v3.WorkflowActionMessage.Message
}
var file_workflow_proto_depIdxs = []int32{
	1, // 0: v3.WorflowOperationInstanceData.life_cycle:type_name -> v3.WorkflowLifeCycle
	2, // 1: v3.WorflowOperationInstanceData.latest_action_inst_brief_data:type_name -> v3.WorkflowActionInstBriefData
	1, // 2: v3.WorkflowActionData.life_cycle:type_name -> v3.WorkflowLifeCycle
	5, // 3: v3.WorkflowActionData.message:type_name -> v3.WorkflowActionMessage
	3, // 4: v3.WorkflowActionData.sub_workflow_refs:type_name -> v3.SubWorkflowRef
	7, // 5: v3.WorkflowActionMessage.logs:type_name -> v3.WorkflowActionMessage.Message
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_workflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorflowOperationInstanceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowLifeCycle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowActionInstBriefData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubWorkflowRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowActionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowActionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowOperationInstanceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowActionMessage_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workflow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_rawDesc = nil
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
