syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/file/api/v3";

import "google/api/annotations.proto";

// DownloadAgentReq is the request for download agent pkg.
message DownloadAgentReq {
  string os_type = 1;
  string cpu_arch = 2;
  int64 generation = 3;
  string version = 4;
}

// DownloadProxyReq is the request for download proxy pkg.
message DownloadProxyReq {
  string os_type = 1;
  string cpu_arch = 2;
  int64 generation = 3;
  string version = 4;
}

// DownloadPluginReq is the request for download plugin.
message DownloadPluginReq {
  string os_type = 1;
  string cpu_arch = 2;
  string plugin_name = 3;
  string plugin_type = 4;
  string version = 5;
}

// FileChunk describes the file chunk data.
message FileChunk { bytes content = 1; }

// Download service.
service Download {
  // DownloadAgent provides downloading agent pkg.
  rpc DownloadAgent(DownloadAgentReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/download/agent"
      body : "*"
    };
  }

  // DownloadProxy provides downloading proxy pkg.
  rpc DownloadProxy(DownloadProxyReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/download/proxy"
      body : "*"
    };
  }

  // DownloadAgent provides downloading plugin.
  rpc DownloadPlugin(DownloadAgentReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/download/plugin"
      body : "*"
    };
  }
}
