syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/file/api/v3";

import "google/api/annotations.proto";

// DownloadAgentReq is the request for download agent pkg.
message DownloadAgentReq {
  string os_type = 1;
  string cpu_arch = 2;
  int64 generation = 3;
  string version = 4;
}

// DownloadProxyReq is the request for download proxy pkg.
message DownloadProxyReq {
  string os_type = 1;
  string cpu_arch = 2;
  int64 generation = 3;
  string version = 4;
}

// DownloadPluginReq is the request for download plugin.
message DownloadPluginReq {
  string os_type = 1;
  string cpu_arch = 2;
  string plugin_pkg_name = 3;
  string version = 4;
}

// DownloadInstallerReq is the request for download installer.
message DownloadInstallerReq {
  string os_type = 1;
  string cpu_arch = 2;
}

// DownloadCertReq is the request for download cert pkg.
message DownloadCertReq { int64 generation = 1; }

// DownloadBinToolReq is the request for download bintool pkg.
message DownloadBinToolReq { int64 generation = 1; }

// DownloadPluginBinToolReq is the request for download plugin bintool pkg.
message DownloadPluginBinToolReq {
  int64 generation = 1;
  string name = 2;
}

// FileChunk describes the file chunk data.
message FileChunk { bytes content = 1; }

// Download service.
service Download {
  // DownloadAgent provides downloading agent pkg.
  rpc DownloadAgent(DownloadAgentReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/agent"
      body : "*"
    };
  }

  // DownloadProxy provides downloading proxy pkg.
  rpc DownloadProxy(DownloadProxyReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/proxy"
      body : "*"
    };
  }

  // DownloadAgent provides downloading plugin.
  rpc DownloadPlugin(DownloadAgentReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/plugin"
      body : "*"
    };
  }

  // DownloadInstaller provides downloading installer.
  rpc DownloadInstaller(DownloadInstallerReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/installer"
      body : "*"
    };
  }

  // DownloadCert provides downloading cert.
  rpc DownloadCert(DownloadCertReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/cert"
      body : "*"
    };
  }

  // DownloadBinTool provides downloading bintool.
  rpc DownloadBinTool(DownloadBinToolReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/bintool"
      body : "*"
    };
  }

  // DownloadPluginBinTool provides downloading plugin bintool.
  rpc DownloadPluginBinTool(DownloadPluginBinToolReq)
      returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/download/plugin_bintool"
      body : "*"
    };
  }
}
