syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "google/api/annotations.proto";

// DownloadAgentReq is the request for download agent pkg.
message DownloadAgentReq {
  string os_type = 1;
  string cpu_arch = 2;
  int64 generation = 3;
  string version = 4;
}

// DownloadProxyReq is the request for download proxy pkg.
message DownloadProxyReq {
  string os_type = 1;
  string cpu_arch = 2;
  int64 generation = 3;
  string version = 4;
}

// FileChunk describes the file chunk data.
message FileChunk { bytes content = 1; }

// download service.
service Download {
  // DownloadAgent provides downloading agent pkg.
  rpc DownloadAgent(DownloadAgentReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/download/agent"
      body : "*"
    };
  }

  // DownloadProxy provides downloading proxy pkg.
  rpc DownloadProxy(DownloadProxyReq) returns (stream FileChunk) {
    option (google.api.http) = {
      post : "/download/proxy"
      body : "*"
    };
  }
}
