syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/file/api/v3";

import "common.proto";
import "google/api/annotations.proto";

// PublishReleaseAgentReq is the request for upload release agent pkg.
message PublishReleaseAgentReq { string upload_id = 1; }

// PublishReleaseAgentResp is the response for upload release agent pkg.
message PublishReleaseAgentResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseProxyReq is the request for upload release proxy pkg.
message PublishReleaseProxyReq { string upload_id = 1; }

// PublishReleaseProxyResp is the response for upload release proxy pkg.
message PublishReleaseProxyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseCertReq is the request for upload release cert pkg.
message PublishReleaseCertReq { string upload_id = 1; }

// PublishReleaseCertResp is the response for upload release cert pkg.
message PublishReleaseCertResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseBinToolReq is the request for upload release bintool pkg.
message PublishReleaseBinToolReq { string upload_id = 1; }

// PublishReleaseBinToolResp is the response for upload release bintool pkg.
message PublishReleaseBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// Publish service.
service Publish {
  // PublishReleaseAgent provides release agent publish.
  rpc PublishReleaseAgent(PublishReleaseAgentReq)
      returns (PublishReleaseAgentResp) {
    option (google.api.http) = {
      post : "/publish/release/agent"
      body : "*"
    };
  }

  // PublishReleaseServer provides release server publish.
  rpc PublishReleaseProxy(PublishReleaseProxyReq)
      returns (PublishReleaseProxyResp) {
    option (google.api.http) = {
      post : "/publish/release/server"
      body : "*"
    };
  }

  // PublishReleaseCert provides release cert publish.
  rpc PublishReleaseCert(PublishReleaseCertReq)
      returns (PublishReleaseCertResp) {
    option (google.api.http) = {
      post : "/publish/release/cert"
      body : "*"
    };
  }

  // PublishReleaseBinTool provides release bintool publish.
  rpc PublishReleaseBinTool(PublishReleaseBinToolReq)
      returns (PublishReleaseBinToolResp) {
    option (google.api.http) = {
      post : "/publish/release/bintool"
      body : "*"
    };
  }
}