syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/file/api/v3";

import "common.proto";
import "google/api/annotations.proto";

// PublishReleaseAgentReq is the request for upload release agent pkg.
message PublishReleaseAgentReq {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleaseAgentResp is the response for upload release agent pkg.
message PublishReleaseAgentResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseProxyReq is the request for upload release proxy pkg.
message PublishReleaseProxyReq {
  string upload_id = 1;

  // upload_origin_pkg_type indicates the origin category of the uploaded
  // package. only accepts "origin_server" and "origin_proxy", no default value.
  string upload_origin_pkg_type = 2;
  bool is_shared = 3;
}

// PublishReleaseProxyResp is the response for upload release proxy pkg.
message PublishReleaseProxyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseCertReq is the request for upload release cert pkg.
message PublishReleaseCertReq {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleaseCertResp is the response for upload release cert pkg.
message PublishReleaseCertResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseBinToolReq is the request for upload release bintool pkg.
message PublishReleaseBinToolReq {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleaseBinToolResp is the response for upload release bintool pkg.
message PublishReleaseBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleasePluginBinToolReq is the request for upload release plugin
// bintool pkg.
message PublishReleasePluginBinToolReq {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleasePluginBinToolResp is the response for upload release plugin
// bintool pkg.
message PublishReleasePluginBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleasePluginV2Req is the request for upload release
// plugin pkg.
message PublishReleasePluginV2Req {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleasePluginV2Resp is the response for upload release
// plugin pkg.
message PublishReleasePluginV2Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleaseExternalPluginV2Req is the request for upload release external
// plugin v2 pkg.
message PublishReleaseExternalPluginV2Req {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleaseExternalPluginV2Resp is the response for upload release
// external plugin v2 pkg.
message PublishReleaseExternalPluginV2Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// PublishReleasePluginV3Req is the request for upload release
// plugin pkg.
message PublishReleasePluginV3Req {
  string upload_id = 1;
  bool is_shared = 2;
}

// PublishReleasePluginV3Resp is the response for upload release
// plugin pkg.
message PublishReleasePluginV3Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// Publish service.
service Publish {
  // PublishReleaseAgent provides release agent publish.
  rpc PublishReleaseAgent(PublishReleaseAgentReq)
      returns (PublishReleaseAgentResp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/agent"
      body : "*"
    };
  }

  // PublishReleaseProxy publishes a proxy release from a proxy or server
  // package.
  rpc PublishReleaseProxy(PublishReleaseProxyReq)
      returns (PublishReleaseProxyResp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/proxy"
      body : "*"
    };
  }

  // PublishReleaseCert provides release cert publish.
  rpc PublishReleaseCert(PublishReleaseCertReq)
      returns (PublishReleaseCertResp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/cert"
      body : "*"
    };
  }

  // PublishReleaseBinTool provides release bintool publish.
  rpc PublishReleaseBinTool(PublishReleaseBinToolReq)
      returns (PublishReleaseBinToolResp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/bintool"
      body : "*"
    };
  }

  // PublishReleasePluginBinTool provides release plugin bintool publish.
  rpc PublishReleasePluginBinTool(PublishReleasePluginBinToolReq)
      returns (PublishReleasePluginBinToolResp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/plugin_bintool"
      body : "*"
    };
  }

  // PublishReleasePluginV2 provides release plugin v2 publish.
  rpc PublishReleasePluginV2(PublishReleasePluginV2Req)
      returns (PublishReleasePluginV2Resp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/v2/plugin"
      body : "*"
    };
  }

  // PublishReleaseExternalPluginV2 provides release external plugin v2 publish.
  rpc PublishReleaseExternalPluginV2(PublishReleaseExternalPluginV2Req)
      returns (PublishReleaseExternalPluginV2Resp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/v2/external_plugin"
      body : "*"
    };
  }

  // PublishReleasePluginV3 provides release plugin v3 publish.
  rpc PublishReleasePluginV3(PublishReleasePluginV3Req)
      returns (PublishReleasePluginV3Resp) {
    option (google.api.http) = {
      post : "/api/v3/publish/release/v3/plugin"
      body : "*"
    };
  }
}
