syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/file/api/v3";

import "common.proto";
import "google/api/annotations.proto";

// UploadOriginAgentReq is the request for upload origin agent pkg.
message UploadOriginAgentReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// UploadOriginAgentResp is the response for upload origin agent pkg.
message UploadOriginAgentResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    optional string changelog_en = 8;
    optional string changelog_zh = 9;
    repeated Platform platforms = 10;
  }
  Data data = 4;
}

// UploadOriginServerReq is the request for upload origin server pkg.
message UploadOriginServerReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// UploadOriginServerResp is the response for upload origin server pkg.
message UploadOriginServerResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    repeated Platform platforms = 8;
  }
  Data data = 4;
}

// UploadOriginProxyReq is the request for upload origin proxy pkg.
message UploadOriginProxyReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// UploadOriginProxyResp is the response for upload origin proxy pkg.
message UploadOriginProxyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    optional string changelog_en = 8;
    optional string changelog_zh = 9;
    repeated Platform platforms = 10;
  }
  Data data = 4;
}

// UploadOriginCertResp is the response for upload origin cert pkg.
message UploadOriginCertReq { bool overwrite = 1; }

// UploadOriginCertResp is the response for upload origin cert pkg.
message UploadOriginCertResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    repeated string cert_files = 7;
  }
  Data data = 4;
}

// UploadOriginBinToolReq is the request for upload origin bin tool pkg.
message UploadOriginBinToolReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// UploadOriginBinToolResp is the response for upload origin bin tool pkg.
message UploadOriginBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    repeated Platform agent_platforms = 7;
    repeated Platform proxy_platforms = 8;
  }
  Data data = 4;
}

// UploadOriginPluginBinToolReq is the request for upload origin plugin bin tool
// pkg.
message UploadOriginPluginBinToolReq { bool overwrite = 1; }

// UploadOriginPluginBinToolResp is the response for upload origin plugin bin
// tool pkg.
message UploadOriginPluginBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;

    message V2Info { repeated Platform platforms = 1; }
    optional V2Info v2 = 7;

    message V3Info { repeated Platform platforms = 1; }
    optional V3Info v3 = 8;
  }
  Data data = 4;
}

// UploadOriginPluginV2Req is the request for upload origin
// plugin pkg.
message UploadOriginPluginV2Req { bool overwrite = 1; }

// UploadOriginPluginV2Resp is the response for upload origin
// plugin pkg.
message UploadOriginPluginV2Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    optional string description = 8;
    optional string description_en = 9;
    optional string scenario = 10;
    optional string scenario_en = 11;
    optional string config_file = 12;
    optional string config_format = 13;
    optional string launch_node = 14;
    repeated Platform platforms = 15;
  }
  Data data = 4;
}

// UploadOriginExternalPluginV2Req is the request for upload external
// plugin pkg.
message UploadOriginExternalPluginV2Req { bool overwrite = 1; }

// UploadOriginExternalPluginV2Resp is the response for upload external
// plugin pkg.
message UploadOriginExternalPluginV2Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    optional string description = 8;
    optional string description_en = 9;
    optional string scenario = 10;
    optional string scenario_en = 11;
    optional string config_file = 12;
    optional string config_format = 13;
    optional string launch_node = 14;
    repeated Platform platforms = 15;
  }
  Data data = 4;
}

// UploadOriginPluginV3Req is the request for upload origin
// plugin pkg.
message UploadOriginPluginV3Req { bool overwrite = 1; }

// UploadOriginPluginV3Resp is the response for upload origin
// plugin pkg.
message UploadOriginPluginV3Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string plugin_pkg_name = 7;
    optional string version = 8;
    optional string description = 9;
    optional string description_en = 10;
    optional string scenario = 11;
    optional string scenario_en = 12;
    optional string launch_node = 13;
    optional string template_renderer = 14;
    repeated Platform platforms = 15;
  }
  Data data = 4;
}

// Upload service.
service Upload {
  // UploadOriginAgent provides origin agent upload.
  rpc UploadOriginAgent(UploadOriginAgentReq) returns (UploadOriginAgentResp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/agent"
      body : "*"
    };
  }

  // UploadOriginServer provides origin server upload.
  rpc UploadOriginServer(UploadOriginServerReq)
      returns (UploadOriginServerResp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/server"
      body : "*"
    };
  }

  // UploadOriginProxy provides origin proxy upload.
  rpc UploadOriginProxy(UploadOriginProxyReq) returns (UploadOriginProxyResp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/proxy"
      body : "*"
    };
  }

  // UploadOriginCert provides origin cert upload.
  rpc UploadOriginCert(UploadOriginCertReq) returns (UploadOriginCertResp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/cert"
      body : "*"
    };
  }

  // UploadOriginBinTool provides origin bintool upload.
  rpc UploadOriginBinTool(UploadOriginBinToolReq)
      returns (UploadOriginBinToolResp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/bintool"
      body : "*"
    };
  }

  // UploadOriginPluginBinToolV2 provides origin bintool upload.
  rpc UploadOriginPluginBinToolV2(UploadOriginPluginBinToolReq)
      returns (UploadOriginPluginBinToolResp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/plugin_bintool"
      body : "*"
    };
  }

  // UploadOriginPluginV2 provides origin plugin upload.
  rpc UploadOriginPluginV2(UploadOriginPluginV2Req)
      returns (UploadOriginPluginV2Resp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/v2/plugin"
      body : "*"
    };
  }

  // UploadOriginExternalPlugin provides origin external plugin upload.
  rpc UploadOriginExternalPlugin(UploadOriginExternalPluginV2Req)
      returns (UploadOriginExternalPluginV2Resp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/v2/external_plugin"
      body : "*"
    };
  }

  // UploadOriginPluginV3 provides origin plugin upload.
  rpc UploadOriginPluginV3(UploadOriginPluginV3Req)
      returns (UploadOriginPluginV3Resp) {
    option (google.api.http) = {
      post : "/api/v3/upload/origin/v3/plugin"
      body : "*"
    };
  }
}