{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bk-nodeman.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodeman-backend
    metric: nodeman-backend-metric
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: nodeman-backend
  ports:
    - name: service-http
      port: {{ .Values.backend.config.httpServer.port }}
      targetPort: service-http
    - name: callback-http
      port: {{ .Values.backend.config.callbackServer.port }}
      targetPort: callback-http
{{- end }}
