{{- if .Values.backend.enabled }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "bk-nodeman.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    values-hash: "{{ toYaml .Values.backend | sha256sum | trunc 63 }}"
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "bk-nodeman.replicaCount" ( dict "root" .Values "module" .Values.backend ) }}
  {{- if .Values.updateStrategy }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.updateStrategy.type) }}
    rollingUpdate: null
    {{- else }}
    rollingUpdate: {{ .Values.updateStrategy.rollingUpdate | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: nodeman-backend
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app: nodeman-backend
      {{- if .Values.backend.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.backend.podAnnotations "context" $) | nindent 8 }}
      {{- else if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "bk-nodeman.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.hostAliases }}
      # yamllint disable rule:indentation
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      # yamllint enable rule:indentation
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" (merge .Values.backend.nodeSelector .Values.nodeSelector) "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      {{- if .Values.backend.hostNetwork }}
                      - nodeman-backend
                      {{- else }}
                      - nodeman-no-affinity
                    {{- end }}
              topologyKey: kubernetes.io/hostname
              namespaces: []
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ template "bk-nodeman.fullname" . }}-backend
          {{- if len .Values.backend.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodeman.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - {{ .Values.common.binPath }}/bk-nodeman-backend
          args: 
            - -f 
            - {{ .Values.common.etcPath }}/backend_conf.yaml
          env:
            - name: NODEMAN-MODULE
              value: backend
          ports:
            - name: service-http
              containerPort: {{ .Values.backend.config.httpServer.port }}
            - name: callback-http
              containerPort: {{ .Values.backend.config.callbackServer.port }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: service-http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- else if .Values.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 10 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: service-http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- else if .Values.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: nodeman-cert
              mountPath: {{ .Values.common.certPath }}
            - name: nodeman-etc
              mountPath: {{ .Values.common.etcPath }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources: {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- end }}

      initContainers:
        - name: {{ template "bk-nodeman.fullname" . }}-backend-check-mongodb
          {{- if len .Values.backend.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodeman.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["sh", "-c"]
          args:
          - |
            /bin/sh <<'EOF'

            mongobin="mongo"

            # check mongodb.
            try_times=1
            ret=1
            sleep_time=1
            while [ ${ret} -ne 0 ]
            do
                {{- if .Values.mongodb.enabled }}
                ${mongobin} {{ template "bk-nodeman.fullname" . }}-mongodb-headless:{{ .Values.mongodb.service.port }}/{{ .Values.mongodb.auth.database }} -u {{ .Values.mongodb.auth.username }} -p {{ .Values.mongodb.auth.password }} --eval "db.runCommand({ping: 1})"
                {{- else }}
                ${mongobin} {{ .Values.externalMongodb.hosts }}/{{ .Values.externalMongodb.database }} -u {{ .Values.externalMongodb.username }} -p {{ .Values.externalMongodb.password }} --eval "db.runCommand({ping: 1})"
                {{- end }}

                ret=$?
                echo try to check ${try_times} times
                try_times=$((try_times+1))
                sleep ${sleep_time}
            done

            echo "check mongodb done"
            EOF
          resources: {{- toYaml .Values.initContainerResources | nindent 12 }}
        - name: {{ template "bk-nodeman.fullname" . }}-backend-check-redis
          {{- if len .Values.backend.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodeman.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["sh", "-c"]
          args:
          - |
            /bin/sh <<'EOF'

            redisbin="redis-cli"

            {{- if .Values.redis.enabled }}
            check_args="-h {{ template "bk-nodeman.fullname" . }}-redis-headless -p {{ .Values.redis.service.ports.redis }} -a {{ .Values.redis.password }} --no-auth-warning -c ping"
            {{- else }}
            {{- if eq .Values.externalRedis.username "default" }}
            {{- if eq .Values.externalRedis.type "sentinel" }}
            check_args="-h {{ .Values.externalRedis.host }} -p {{ .Values.externalRedis.port }} -a {{ .Values.externalRedis.sentinelPassword }} --no-auth-warning -c ping"
            {{- else }}
            check_args="-h {{ .Values.externalRedis.host }} -p {{ .Values.externalRedis.port }} -a {{ .Values.externalRedis.password }} --no-auth-warning -c ping"
            {{- end }}
            {{- else }}
            {{- if eq .Values.externalRedis.type "sentinel" }}
            check_args="-h {{ .Values.externalRedis.host }} -p {{ .Values.externalRedis.port }} --user {{ .Values.externalRedis.username }} -a {{ .Values.externalRedis.sentinelPassword }} --no-auth-warning -c ping"
            {{- else }}
            check_args="-h {{ .Values.externalRedis.host }} -p {{ .Values.externalRedis.port }} --user {{ .Values.externalRedis.username }} -a {{ .Values.externalRedis.password }} --no-auth-warning -c ping"
            {{- end }}
            {{- end }}
            {{- end }}

            # check redis.
            try_times=1
            ret=1
            sleep_time=1
            while [ ${ret} -ne 0 ]
            do
                ${redisbin} ${check_args}
                ret=$?
                echo try to check ${try_times} times
                try_times=$((try_times+1))
                sleep ${sleep_time}
            done

            echo "check redis done"
            EOF
          resources: {{- toYaml .Values.initContainerResources | nindent 12 }}
        - name: {{ template "bk-nodeman.fullname" . }}-backend-init
          {{- if len .Values.backend.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.backend.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodeman.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["sh", "-c"]
          args:
          - |
            /bin/sh <<'EOF'

            # for service api advertise ip, it may be ipv4 or ipv6 value which base on k8s node settings.
            ADVERTISE_IP=${POD_IP}

            # for agent schedule advertise ip, parsing ipv4 and ipv6 value which base on k8s node settings.
            ips=$(echo "${POD_IPS}" | sed 's/,/ /g')
            for ip in $ips; do
              echo "$ip" | grep -q : 2>/dev/null
              if [ $? -eq 0 ]; then
                ADVERTISE_IPV6=$ip
              else
                ADVERTISE_IPV4=$ip
              fi
            done

            # sed local config file.
            cp /tmp/backend_conf.yaml {{ .Values.common.etcPath }}/backend_conf.yaml
            sed -i "s/__ADVERTISE_IPV4__/${ADVERTISE_IPV4}/g" {{ .Values.common.etcPath }}/backend_conf.yaml
            sed -i "s/__ADVERTISE_IPV6__/${ADVERTISE_IPV6}/g" {{ .Values.common.etcPath }}/backend_conf.yaml
            
            echo "local module init done"
            EOF
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_IPS
            valueFrom:
              fieldRef:
                fieldPath: status.podIPs
          volumeMounts:
            - name: {{ template "bk-nodeman.fullname" . }}-backend-config
              mountPath: /tmp
            - name: nodeman-etc
              mountPath: {{ .Values.common.etcPath }}
          resources: {{- toYaml .Values.initContainerResources | nindent 10 }}
      hostNetwork: {{ .Values.backend.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: nodeman-cert
        configMap:
          name: {{ template "bk-nodeman.fullname" . }}-certs
      - name: {{ template "bk-nodeman.fullname" . }}-backend-config
        configMap:
          name: {{ template "bk-nodeman.fullname" . }}-backend-config
      - name: nodeman-etc
        emptyDir: {}
{{- end }}
