// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: configpolicy.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigPolicyExactConditions describes config policy exact conditions.
type ConfigPolicyExactConditions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId []int64                `protobuf:"varint,1,rep,packed,name=configpolicy_id,json=configpolicyId,proto3" json:"configpolicy_id"`
	BizId          []int64                `protobuf:"varint,2,rep,packed,name=biz_id,json=bizId,proto3" json:"biz_id"`
	NodeRole       []string               `protobuf:"bytes,3,rep,name=node_role,json=nodeRole,proto3" json:"node_role"`
	Enabled        []bool                 `protobuf:"varint,4,rep,packed,name=enabled,proto3" json:"enabled"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyExactConditions) Reset() {
	*x = ConfigPolicyExactConditions{}
	mi := &file_configpolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyExactConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyExactConditions) ProtoMessage() {}

func (x *ConfigPolicyExactConditions) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyExactConditions.ProtoReflect.Descriptor instead.
func (*ConfigPolicyExactConditions) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigPolicyExactConditions) GetConfigpolicyId() []int64 {
	if x != nil {
		return x.ConfigpolicyId
	}
	return nil
}

func (x *ConfigPolicyExactConditions) GetBizId() []int64 {
	if x != nil {
		return x.BizId
	}
	return nil
}

func (x *ConfigPolicyExactConditions) GetNodeRole() []string {
	if x != nil {
		return x.NodeRole
	}
	return nil
}

func (x *ConfigPolicyExactConditions) GetEnabled() []bool {
	if x != nil {
		return x.Enabled
	}
	return nil
}

// ConfigPolicyFuzzyConditions describes config policy fuzzy conditions.
type ConfigPolicyFuzzyConditions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyName []string               `protobuf:"bytes,1,rep,name=configpolicy_name,json=configpolicyName,proto3" json:"configpolicy_name"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigPolicyFuzzyConditions) Reset() {
	*x = ConfigPolicyFuzzyConditions{}
	mi := &file_configpolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyFuzzyConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyFuzzyConditions) ProtoMessage() {}

func (x *ConfigPolicyFuzzyConditions) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyFuzzyConditions.ProtoReflect.Descriptor instead.
func (*ConfigPolicyFuzzyConditions) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigPolicyFuzzyConditions) GetConfigpolicyName() []string {
	if x != nil {
		return x.ConfigpolicyName
	}
	return nil
}

// ConfigPolicyListReq describes HTTP request body when list config policy.
type ConfigPolicyListReq struct {
	state                  protoimpl.MessageState       `protogen:"open.v1"`
	Page                   *Page                        `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	OnlyCount              bool                         `protobuf:"varint,2,opt,name=only_count,json=onlyCount,proto3" json:"only_count"`
	ExactIncludeConditions *ConfigPolicyExactConditions `protobuf:"bytes,3,opt,name=exact_include_conditions,json=exactIncludeConditions,proto3" json:"exact_include_conditions"`
	FuzzyIncludeConditions *ConfigPolicyFuzzyConditions `protobuf:"bytes,4,opt,name=fuzzy_include_conditions,json=fuzzyIncludeConditions,proto3" json:"fuzzy_include_conditions"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigPolicyListReq) Reset() {
	*x = ConfigPolicyListReq{}
	mi := &file_configpolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyListReq) ProtoMessage() {}

func (x *ConfigPolicyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyListReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyListReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigPolicyListReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ConfigPolicyListReq) GetOnlyCount() bool {
	if x != nil {
		return x.OnlyCount
	}
	return false
}

func (x *ConfigPolicyListReq) GetExactIncludeConditions() *ConfigPolicyExactConditions {
	if x != nil {
		return x.ExactIncludeConditions
	}
	return nil
}

func (x *ConfigPolicyListReq) GetFuzzyIncludeConditions() *ConfigPolicyFuzzyConditions {
	if x != nil {
		return x.FuzzyIncludeConditions
	}
	return nil
}

// ConfigPolicyListResp describes HTTP response body when list config policy.
type ConfigPolicyListResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                     `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyListResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyListResp) Reset() {
	*x = ConfigPolicyListResp{}
	mi := &file_configpolicy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyListResp) ProtoMessage() {}

func (x *ConfigPolicyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyListResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyListResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigPolicyListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyListResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyListResp) GetData() *ConfigPolicyListResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyTemplateReq describes HTTP request body when get config policy
// template.
type ConfigPolicyTemplateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRole      string                 `protobuf:"bytes,1,opt,name=node_role,json=nodeRole,proto3" json:"node_role"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyTemplateReq) Reset() {
	*x = ConfigPolicyTemplateReq{}
	mi := &file_configpolicy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyTemplateReq) ProtoMessage() {}

func (x *ConfigPolicyTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyTemplateReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyTemplateReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigPolicyTemplateReq) GetNodeRole() string {
	if x != nil {
		return x.NodeRole
	}
	return ""
}

// ConfigPolicyTemplateResp describes HTTP response body when get config policy
// template.
type ConfigPolicyTemplateResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                         `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyTemplateResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyTemplateResp) Reset() {
	*x = ConfigPolicyTemplateResp{}
	mi := &file_configpolicy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyTemplateResp) ProtoMessage() {}

func (x *ConfigPolicyTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyTemplateResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyTemplateResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigPolicyTemplateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyTemplateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyTemplateResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyTemplateResp) GetData() *ConfigPolicyTemplateResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyGetReq describes HTTP request body when get config policy.
type ConfigPolicyGetReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId int64                  `protobuf:"varint,1,opt,name=configpolicy_id,json=configpolicyId,proto3" json:"configpolicy_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyGetReq) Reset() {
	*x = ConfigPolicyGetReq{}
	mi := &file_configpolicy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyGetReq) ProtoMessage() {}

func (x *ConfigPolicyGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyGetReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyGetReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigPolicyGetReq) GetConfigpolicyId() int64 {
	if x != nil {
		return x.ConfigpolicyId
	}
	return 0
}

// ConfigPolicyGetResp describes HTTP response body when get config policy.
type ConfigPolicyGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicy          `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyGetResp) Reset() {
	*x = ConfigPolicyGetResp{}
	mi := &file_configpolicy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyGetResp) ProtoMessage() {}

func (x *ConfigPolicyGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyGetResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyGetResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigPolicyGetResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyGetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyGetResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyGetResp) GetData() *ConfigPolicy {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyCreateReq describes HTTP request body when create config policy.
type ConfigPolicyCreateReq struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	ConfigpolicyName string                     `protobuf:"bytes,1,opt,name=configpolicy_name,json=configpolicyName,proto3" json:"configpolicy_name"`
	NodeRole         string                     `protobuf:"bytes,2,opt,name=node_role,json=nodeRole,proto3" json:"node_role"`
	BizId            []int64                    `protobuf:"varint,3,rep,packed,name=biz_id,json=bizId,proto3" json:"biz_id"`
	Remark           string                     `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark"`
	Scopes           []*ConfigPolicyScope       `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes"`
	Configs          []*ConfigPolicyConfigBlock `protobuf:"bytes,6,rep,name=configs,proto3" json:"configs"`
	Operator         string                     `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigPolicyCreateReq) Reset() {
	*x = ConfigPolicyCreateReq{}
	mi := &file_configpolicy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyCreateReq) ProtoMessage() {}

func (x *ConfigPolicyCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyCreateReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyCreateReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigPolicyCreateReq) GetConfigpolicyName() string {
	if x != nil {
		return x.ConfigpolicyName
	}
	return ""
}

func (x *ConfigPolicyCreateReq) GetNodeRole() string {
	if x != nil {
		return x.NodeRole
	}
	return ""
}

func (x *ConfigPolicyCreateReq) GetBizId() []int64 {
	if x != nil {
		return x.BizId
	}
	return nil
}

func (x *ConfigPolicyCreateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ConfigPolicyCreateReq) GetScopes() []*ConfigPolicyScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ConfigPolicyCreateReq) GetConfigs() []*ConfigPolicyConfigBlock {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ConfigPolicyCreateReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// ConfigPolicyCreateResp describes HTTP response body when create config
// policy.
type ConfigPolicyCreateResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                       `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyCreateResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyCreateResp) Reset() {
	*x = ConfigPolicyCreateResp{}
	mi := &file_configpolicy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyCreateResp) ProtoMessage() {}

func (x *ConfigPolicyCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyCreateResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyCreateResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigPolicyCreateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyCreateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyCreateResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyCreateResp) GetData() *ConfigPolicyCreateResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyUpdateReq describes HTTP request body when update config policy.
type ConfigPolicyUpdateReq struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	ConfigpolicyId   int64                      `protobuf:"varint,1,opt,name=configpolicy_id,json=configpolicyId,proto3" json:"configpolicy_id"`
	ConfigpolicyName string                     `protobuf:"bytes,2,opt,name=configpolicy_name,json=configpolicyName,proto3" json:"configpolicy_name"`
	NodeRole         string                     `protobuf:"bytes,3,opt,name=node_role,json=nodeRole,proto3" json:"node_role"`
	BizId            []int64                    `protobuf:"varint,4,rep,packed,name=biz_id,json=bizId,proto3" json:"biz_id"`
	Remark           string                     `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark"`
	Scopes           []*ConfigPolicyScope       `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes"`
	Configs          []*ConfigPolicyConfigBlock `protobuf:"bytes,7,rep,name=configs,proto3" json:"configs"`
	Enabled          bool                       `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled"`
	Operator         string                     `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigPolicyUpdateReq) Reset() {
	*x = ConfigPolicyUpdateReq{}
	mi := &file_configpolicy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyUpdateReq) ProtoMessage() {}

func (x *ConfigPolicyUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyUpdateReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyUpdateReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigPolicyUpdateReq) GetConfigpolicyId() int64 {
	if x != nil {
		return x.ConfigpolicyId
	}
	return 0
}

func (x *ConfigPolicyUpdateReq) GetConfigpolicyName() string {
	if x != nil {
		return x.ConfigpolicyName
	}
	return ""
}

func (x *ConfigPolicyUpdateReq) GetNodeRole() string {
	if x != nil {
		return x.NodeRole
	}
	return ""
}

func (x *ConfigPolicyUpdateReq) GetBizId() []int64 {
	if x != nil {
		return x.BizId
	}
	return nil
}

func (x *ConfigPolicyUpdateReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ConfigPolicyUpdateReq) GetScopes() []*ConfigPolicyScope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ConfigPolicyUpdateReq) GetConfigs() []*ConfigPolicyConfigBlock {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ConfigPolicyUpdateReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConfigPolicyUpdateReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// ConfigPolicyUpdateResp describes HTTP response body when update config
// policy.
type ConfigPolicyUpdateResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                       `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyUpdateResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyUpdateResp) Reset() {
	*x = ConfigPolicyUpdateResp{}
	mi := &file_configpolicy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyUpdateResp) ProtoMessage() {}

func (x *ConfigPolicyUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyUpdateResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyUpdateResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigPolicyUpdateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyUpdateResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyUpdateResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyUpdateResp) GetData() *ConfigPolicyUpdateResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyEnableReq describes HTTP request body when enable config policy.
type ConfigPolicyEnableReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId []int64                `protobuf:"varint,1,rep,packed,name=configpolicy_id,json=configpolicyId,proto3" json:"configpolicy_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyEnableReq) Reset() {
	*x = ConfigPolicyEnableReq{}
	mi := &file_configpolicy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyEnableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyEnableReq) ProtoMessage() {}

func (x *ConfigPolicyEnableReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyEnableReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyEnableReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigPolicyEnableReq) GetConfigpolicyId() []int64 {
	if x != nil {
		return x.ConfigpolicyId
	}
	return nil
}

// ConfigPolicyEnableResp describes HTTP response body when enable config
// policy.
type ConfigPolicyEnableResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                       `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyEnableResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyEnableResp) Reset() {
	*x = ConfigPolicyEnableResp{}
	mi := &file_configpolicy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyEnableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyEnableResp) ProtoMessage() {}

func (x *ConfigPolicyEnableResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyEnableResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyEnableResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigPolicyEnableResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyEnableResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyEnableResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyEnableResp) GetData() *ConfigPolicyEnableResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyDisableReq describes HTTP request body when disable config
// policy.
type ConfigPolicyDisableReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId []int64                `protobuf:"varint,1,rep,packed,name=configpolicy_id,json=configpolicyId,proto3" json:"configpolicy_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyDisableReq) Reset() {
	*x = ConfigPolicyDisableReq{}
	mi := &file_configpolicy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyDisableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyDisableReq) ProtoMessage() {}

func (x *ConfigPolicyDisableReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyDisableReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyDisableReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigPolicyDisableReq) GetConfigpolicyId() []int64 {
	if x != nil {
		return x.ConfigpolicyId
	}
	return nil
}

// ConfigPolicyDisableResp describes HTTP response body when disable config
// policy.
type ConfigPolicyDisableResp struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                        `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyDisableResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyDisableResp) Reset() {
	*x = ConfigPolicyDisableResp{}
	mi := &file_configpolicy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyDisableResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyDisableResp) ProtoMessage() {}

func (x *ConfigPolicyDisableResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyDisableResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyDisableResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigPolicyDisableResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyDisableResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyDisableResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyDisableResp) GetData() *ConfigPolicyDisableResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConfigPolicyDeleteReq describes HTTP request body when delete config policy.
type ConfigPolicyDeleteReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId []int64                `protobuf:"varint,1,rep,packed,name=configpolicy_id,json=configpolicyId,proto3" json:"configpolicy_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyDeleteReq) Reset() {
	*x = ConfigPolicyDeleteReq{}
	mi := &file_configpolicy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyDeleteReq) ProtoMessage() {}

func (x *ConfigPolicyDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyDeleteReq.ProtoReflect.Descriptor instead.
func (*ConfigPolicyDeleteReq) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigPolicyDeleteReq) GetConfigpolicyId() []int64 {
	if x != nil {
		return x.ConfigpolicyId
	}
	return nil
}

// ConfigPolicyDeleteResp describes HTTP response body when delete config
// policy.
type ConfigPolicyDeleteResp struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Code          int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                       `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *ConfigPolicyDeleteResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyDeleteResp) Reset() {
	*x = ConfigPolicyDeleteResp{}
	mi := &file_configpolicy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyDeleteResp) ProtoMessage() {}

func (x *ConfigPolicyDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyDeleteResp.ProtoReflect.Descriptor instead.
func (*ConfigPolicyDeleteResp) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigPolicyDeleteResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigPolicyDeleteResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPolicyDeleteResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPolicyDeleteResp) GetData() *ConfigPolicyDeleteResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConfigPolicyListResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Items         []*ConfigPolicy        `protobuf:"bytes,2,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyListResp_Data) Reset() {
	*x = ConfigPolicyListResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyListResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyListResp_Data) ProtoMessage() {}

func (x *ConfigPolicyListResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyListResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyListResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ConfigPolicyListResp_Data) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ConfigPolicyListResp_Data) GetItems() []*ConfigPolicy {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfigPolicyTemplateResp_Data struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Templates     []*ConfigPolicyConfigBlock `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyTemplateResp_Data) Reset() {
	*x = ConfigPolicyTemplateResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyTemplateResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyTemplateResp_Data) ProtoMessage() {}

func (x *ConfigPolicyTemplateResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyTemplateResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyTemplateResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ConfigPolicyTemplateResp_Data) GetTemplates() []*ConfigPolicyConfigBlock {
	if x != nil {
		return x.Templates
	}
	return nil
}

type ConfigPolicyCreateResp_Data struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId *int64                 `protobuf:"varint,1,opt,name=configpolicy_id,json=configpolicyId,proto3,oneof" json:"configpolicy_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyCreateResp_Data) Reset() {
	*x = ConfigPolicyCreateResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyCreateResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyCreateResp_Data) ProtoMessage() {}

func (x *ConfigPolicyCreateResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyCreateResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyCreateResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ConfigPolicyCreateResp_Data) GetConfigpolicyId() int64 {
	if x != nil && x.ConfigpolicyId != nil {
		return *x.ConfigpolicyId
	}
	return 0
}

type ConfigPolicyUpdateResp_Data struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConfigpolicyId *int64                 `protobuf:"varint,1,opt,name=configpolicy_id,json=configpolicyId,proto3,oneof" json:"configpolicy_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigPolicyUpdateResp_Data) Reset() {
	*x = ConfigPolicyUpdateResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyUpdateResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyUpdateResp_Data) ProtoMessage() {}

func (x *ConfigPolicyUpdateResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyUpdateResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyUpdateResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ConfigPolicyUpdateResp_Data) GetConfigpolicyId() int64 {
	if x != nil && x.ConfigpolicyId != nil {
		return *x.ConfigpolicyId
	}
	return 0
}

type ConfigPolicyEnableResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyEnableResp_Data) Reset() {
	*x = ConfigPolicyEnableResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyEnableResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyEnableResp_Data) ProtoMessage() {}

func (x *ConfigPolicyEnableResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyEnableResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyEnableResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{13, 0}
}

type ConfigPolicyDisableResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyDisableResp_Data) Reset() {
	*x = ConfigPolicyDisableResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyDisableResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyDisableResp_Data) ProtoMessage() {}

func (x *ConfigPolicyDisableResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyDisableResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyDisableResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{15, 0}
}

type ConfigPolicyDeleteResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPolicyDeleteResp_Data) Reset() {
	*x = ConfigPolicyDeleteResp_Data{}
	mi := &file_configpolicy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPolicyDeleteResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPolicyDeleteResp_Data) ProtoMessage() {}

func (x *ConfigPolicyDeleteResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_configpolicy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPolicyDeleteResp_Data.ProtoReflect.Descriptor instead.
func (*ConfigPolicyDeleteResp_Data) Descriptor() ([]byte, []int) {
	return file_configpolicy_proto_rawDescGZIP(), []int{17, 0}
}

var File_configpolicy_proto protoreflect.FileDescriptor

var file_configpolicy_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x33, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x45, 0x78, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x62,
	0x69, 0x7a, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x4a, 0x0a, 0x1b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x46, 0x75, 0x7a, 0x7a, 0x79,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x88, 0x02, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x76, 0x33, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x59, 0x0a, 0x18,
	0x65, 0x78, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x45, 0x78, 0x61, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x16, 0x65, 0x78, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x59, 0x0a, 0x18, 0x66, 0x75, 0x7a, 0x7a, 0x79,
	0x5f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x33, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x46, 0x75, 0x7a, 0x7a, 0x79,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x16, 0x66, 0x75, 0x7a, 0x7a,
	0x79, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0xdc, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x44, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x36, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x18, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x41, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x39, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x3d, 0x0a,
	0x12, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a,
	0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x92, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62,
	0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x62, 0x69, 0x7a,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x33, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x33, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xe4, 0x01, 0x0a,
	0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x48, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2c, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42,
	0x12, 0x0a, 0x10, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x5f, 0x69, 0x64, 0x22, 0xd5, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x05, 0x62, 0x69, 0x7a, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12,
	0x2d, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x12, 0x35,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xe4, 0x01, 0x0a, 0x16,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x48, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x2c, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x12,
	0x0a, 0x10, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x69, 0x64, 0x22, 0x40, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x49, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x33, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x16, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0xa4, 0x01, 0x0a,
	0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x33, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x06, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x40, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x0f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x33, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x33,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x06, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74,
	0x42, 0x6c, 0x75, 0x65, 0x4b, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6b, 0x2d, 0x6e, 0x6f, 0x64, 0x65,
	0x6d, 0x67, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_configpolicy_proto_rawDescOnce sync.Once
	file_configpolicy_proto_rawDescData []byte
)

func file_configpolicy_proto_rawDescGZIP() []byte {
	file_configpolicy_proto_rawDescOnce.Do(func() {
		file_configpolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configpolicy_proto_rawDesc), len(file_configpolicy_proto_rawDesc)))
	})
	return file_configpolicy_proto_rawDescData
}

var file_configpolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_configpolicy_proto_goTypes = []any{
	(*ConfigPolicyExactConditions)(nil),   // 0: v3.ConfigPolicyExactConditions
	(*ConfigPolicyFuzzyConditions)(nil),   // 1: v3.ConfigPolicyFuzzyConditions
	(*ConfigPolicyListReq)(nil),           // 2: v3.ConfigPolicyListReq
	(*ConfigPolicyListResp)(nil),          // 3: v3.ConfigPolicyListResp
	(*ConfigPolicyTemplateReq)(nil),       // 4: v3.ConfigPolicyTemplateReq
	(*ConfigPolicyTemplateResp)(nil),      // 5: v3.ConfigPolicyTemplateResp
	(*ConfigPolicyGetReq)(nil),            // 6: v3.ConfigPolicyGetReq
	(*ConfigPolicyGetResp)(nil),           // 7: v3.ConfigPolicyGetResp
	(*ConfigPolicyCreateReq)(nil),         // 8: v3.ConfigPolicyCreateReq
	(*ConfigPolicyCreateResp)(nil),        // 9: v3.ConfigPolicyCreateResp
	(*ConfigPolicyUpdateReq)(nil),         // 10: v3.ConfigPolicyUpdateReq
	(*ConfigPolicyUpdateResp)(nil),        // 11: v3.ConfigPolicyUpdateResp
	(*ConfigPolicyEnableReq)(nil),         // 12: v3.ConfigPolicyEnableReq
	(*ConfigPolicyEnableResp)(nil),        // 13: v3.ConfigPolicyEnableResp
	(*ConfigPolicyDisableReq)(nil),        // 14: v3.ConfigPolicyDisableReq
	(*ConfigPolicyDisableResp)(nil),       // 15: v3.ConfigPolicyDisableResp
	(*ConfigPolicyDeleteReq)(nil),         // 16: v3.ConfigPolicyDeleteReq
	(*ConfigPolicyDeleteResp)(nil),        // 17: v3.ConfigPolicyDeleteResp
	(*ConfigPolicyListResp_Data)(nil),     // 18: v3.ConfigPolicyListResp.Data
	(*ConfigPolicyTemplateResp_Data)(nil), // 19: v3.ConfigPolicyTemplateResp.Data
	(*ConfigPolicyCreateResp_Data)(nil),   // 20: v3.ConfigPolicyCreateResp.Data
	(*ConfigPolicyUpdateResp_Data)(nil),   // 21: v3.ConfigPolicyUpdateResp.Data
	(*ConfigPolicyEnableResp_Data)(nil),   // 22: v3.ConfigPolicyEnableResp.Data
	(*ConfigPolicyDisableResp_Data)(nil),  // 23: v3.ConfigPolicyDisableResp.Data
	(*ConfigPolicyDeleteResp_Data)(nil),   // 24: v3.ConfigPolicyDeleteResp.Data
	(*Page)(nil),                          // 25: v3.Page
	(*ConfigPolicy)(nil),                  // 26: v3.ConfigPolicy
	(*ConfigPolicyScope)(nil),             // 27: v3.ConfigPolicyScope
	(*ConfigPolicyConfigBlock)(nil),       // 28: v3.ConfigPolicyConfigBlock
}
var file_configpolicy_proto_depIdxs = []int32{
	25, // 0: v3.ConfigPolicyListReq.page:type_name -> v3.Page
	0,  // 1: v3.ConfigPolicyListReq.exact_include_conditions:type_name -> v3.ConfigPolicyExactConditions
	1,  // 2: v3.ConfigPolicyListReq.fuzzy_include_conditions:type_name -> v3.ConfigPolicyFuzzyConditions
	18, // 3: v3.ConfigPolicyListResp.data:type_name -> v3.ConfigPolicyListResp.Data
	19, // 4: v3.ConfigPolicyTemplateResp.data:type_name -> v3.ConfigPolicyTemplateResp.Data
	26, // 5: v3.ConfigPolicyGetResp.data:type_name -> v3.ConfigPolicy
	27, // 6: v3.ConfigPolicyCreateReq.scopes:type_name -> v3.ConfigPolicyScope
	28, // 7: v3.ConfigPolicyCreateReq.configs:type_name -> v3.ConfigPolicyConfigBlock
	20, // 8: v3.ConfigPolicyCreateResp.data:type_name -> v3.ConfigPolicyCreateResp.Data
	27, // 9: v3.ConfigPolicyUpdateReq.scopes:type_name -> v3.ConfigPolicyScope
	28, // 10: v3.ConfigPolicyUpdateReq.configs:type_name -> v3.ConfigPolicyConfigBlock
	21, // 11: v3.ConfigPolicyUpdateResp.data:type_name -> v3.ConfigPolicyUpdateResp.Data
	22, // 12: v3.ConfigPolicyEnableResp.data:type_name -> v3.ConfigPolicyEnableResp.Data
	23, // 13: v3.ConfigPolicyDisableResp.data:type_name -> v3.ConfigPolicyDisableResp.Data
	24, // 14: v3.ConfigPolicyDeleteResp.data:type_name -> v3.ConfigPolicyDeleteResp.Data
	26, // 15: v3.ConfigPolicyListResp.Data.items:type_name -> v3.ConfigPolicy
	28, // 16: v3.ConfigPolicyTemplateResp.Data.templates:type_name -> v3.ConfigPolicyConfigBlock
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_configpolicy_proto_init() }
func file_configpolicy_proto_init() {
	if File_configpolicy_proto != nil {
		return
	}
	file_common_proto_init()
	file_configpolicy_proto_msgTypes[20].OneofWrappers = []any{}
	file_configpolicy_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configpolicy_proto_rawDesc), len(file_configpolicy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configpolicy_proto_goTypes,
		DependencyIndexes: file_configpolicy_proto_depIdxs,
		MessageInfos:      file_configpolicy_proto_msgTypes,
	}.Build()
	File_configpolicy_proto = out.File
	file_configpolicy_proto_goTypes = nil
	file_configpolicy_proto_depIdxs = nil
}
