// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: node_agent.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeAgentInstallReq describes the HTTP request body when install node agent.
type NodeAgentInstallReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BkAddressing    string                 `protobuf:"bytes,1,opt,name=bk_addressing,json=bkAddressing,proto3" json:"bk_addressing"`
	BkBizId         *int64                 `protobuf:"varint,2,opt,name=bk_biz_id,json=bkBizId,proto3,oneof" json:"bk_biz_id"`
	BkHostInnerip   string                 `protobuf:"bytes,3,opt,name=bk_host_innerip,json=bkHostInnerip,proto3" json:"bk_host_innerip"`
	BkHostInneripV6 string                 `protobuf:"bytes,4,opt,name=bk_host_innerip_v6,json=bkHostInneripV6,proto3" json:"bk_host_innerip_v6"`
	LoginIp         string                 `protobuf:"bytes,5,opt,name=login_ip,json=loginIp,proto3" json:"login_ip"`
	LoginPort       *int64                 `protobuf:"varint,6,opt,name=login_port,json=loginPort,proto3,oneof" json:"login_port"`
	LoginUser       string                 `protobuf:"bytes,7,opt,name=login_user,json=loginUser,proto3" json:"login_user"`
	// support: auto, password, keyfile, none
	LoginMode       string `protobuf:"bytes,8,opt,name=login_mode,json=loginMode,proto3" json:"login_mode"`
	LoginPassword   string `protobuf:"bytes,9,opt,name=login_password,json=loginPassword,proto3" json:"login_password"`
	LoginKeyFile    []byte `protobuf:"bytes,10,opt,name=login_key_file,json=loginKeyFile,proto3" json:"login_key_file"`
	BkNetworkunitId *int64 `protobuf:"varint,11,opt,name=bk_networkunit_id,json=bkNetworkunitId,proto3,oneof" json:"bk_networkunit_id"`
	OsType          string `protobuf:"bytes,12,opt,name=os_type,json=osType,proto3" json:"os_type"`
	TargetVersion   string `protobuf:"bytes,13,opt,name=target_version,json=targetVersion,proto3" json:"target_version"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeAgentInstallReq) Reset() {
	*x = NodeAgentInstallReq{}
	mi := &file_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAgentInstallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAgentInstallReq) ProtoMessage() {}

func (x *NodeAgentInstallReq) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAgentInstallReq.ProtoReflect.Descriptor instead.
func (*NodeAgentInstallReq) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{0}
}

func (x *NodeAgentInstallReq) GetBkAddressing() string {
	if x != nil {
		return x.BkAddressing
	}
	return ""
}

func (x *NodeAgentInstallReq) GetBkBizId() int64 {
	if x != nil && x.BkBizId != nil {
		return *x.BkBizId
	}
	return 0
}

func (x *NodeAgentInstallReq) GetBkHostInnerip() string {
	if x != nil {
		return x.BkHostInnerip
	}
	return ""
}

func (x *NodeAgentInstallReq) GetBkHostInneripV6() string {
	if x != nil {
		return x.BkHostInneripV6
	}
	return ""
}

func (x *NodeAgentInstallReq) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *NodeAgentInstallReq) GetLoginPort() int64 {
	if x != nil && x.LoginPort != nil {
		return *x.LoginPort
	}
	return 0
}

func (x *NodeAgentInstallReq) GetLoginUser() string {
	if x != nil {
		return x.LoginUser
	}
	return ""
}

func (x *NodeAgentInstallReq) GetLoginMode() string {
	if x != nil {
		return x.LoginMode
	}
	return ""
}

func (x *NodeAgentInstallReq) GetLoginPassword() string {
	if x != nil {
		return x.LoginPassword
	}
	return ""
}

func (x *NodeAgentInstallReq) GetLoginKeyFile() []byte {
	if x != nil {
		return x.LoginKeyFile
	}
	return nil
}

func (x *NodeAgentInstallReq) GetBkNetworkunitId() int64 {
	if x != nil && x.BkNetworkunitId != nil {
		return *x.BkNetworkunitId
	}
	return 0
}

func (x *NodeAgentInstallReq) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *NodeAgentInstallReq) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

// NodeAgentInstallResp describes
type NodeAgentInstallResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int32                      `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	RequestId     string                     `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id"`
	Data          *NodeAgentInstallResp_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAgentInstallResp) Reset() {
	*x = NodeAgentInstallResp{}
	mi := &file_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAgentInstallResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAgentInstallResp) ProtoMessage() {}

func (x *NodeAgentInstallResp) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAgentInstallResp.ProtoReflect.Descriptor instead.
func (*NodeAgentInstallResp) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *NodeAgentInstallResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NodeAgentInstallResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeAgentInstallResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NodeAgentInstallResp) GetData() *NodeAgentInstallResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type NodeAgentInstallResp_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAgentInstallResp_Data) Reset() {
	*x = NodeAgentInstallResp_Data{}
	mi := &file_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAgentInstallResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAgentInstallResp_Data) ProtoMessage() {}

func (x *NodeAgentInstallResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAgentInstallResp_Data.ProtoReflect.Descriptor instead.
func (*NodeAgentInstallResp_Data) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NodeAgentInstallResp_Data) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

var File_node_agent_proto protoreflect.FileDescriptor

const file_node_agent_proto_rawDesc = "" +
	"\n" +
	"\x10node_agent.proto\x12\x02v3\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\"\x9e\x04\n" +
	"\x13NodeAgentInstallReq\x12#\n" +
	"\rbk_addressing\x18\x01 \x01(\tR\fbkAddressing\x12\x1f\n" +
	"\tbk_biz_id\x18\x02 \x01(\x03H\x00R\abkBizId\x88\x01\x01\x12&\n" +
	"\x0fbk_host_innerip\x18\x03 \x01(\tR\rbkHostInnerip\x12+\n" +
	"\x12bk_host_innerip_v6\x18\x04 \x01(\tR\x0fbkHostInneripV6\x12\x19\n" +
	"\blogin_ip\x18\x05 \x01(\tR\aloginIp\x12\"\n" +
	"\n" +
	"login_port\x18\x06 \x01(\x03H\x01R\tloginPort\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"login_user\x18\a \x01(\tR\tloginUser\x12\x1d\n" +
	"\n" +
	"login_mode\x18\b \x01(\tR\tloginMode\x12%\n" +
	"\x0elogin_password\x18\t \x01(\tR\rloginPassword\x12$\n" +
	"\x0elogin_key_file\x18\n" +
	" \x01(\fR\floginKeyFile\x12/\n" +
	"\x11bk_networkunit_id\x18\v \x01(\x03H\x02R\x0fbkNetworkunitId\x88\x01\x01\x12\x17\n" +
	"\aos_type\x18\f \x01(\tR\x06osType\x12%\n" +
	"\x0etarget_version\x18\r \x01(\tR\rtargetVersionB\f\n" +
	"\n" +
	"_bk_biz_idB\r\n" +
	"\v_login_portB\x14\n" +
	"\x12_bk_networkunit_id\"\xbf\x01\n" +
	"\x14NodeAgentInstallResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x121\n" +
	"\x04data\x18\x04 \x01(\v2\x1d.v3.NodeAgentInstallResp.DataR\x04data\x1a'\n" +
	"\x04Data\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId2y\n" +
	"\tNodeAgent\x12l\n" +
	"\x10NodeAgentInstall\x12\x17.v3.NodeAgentInstallReq\x1a\x18.v3.NodeAgentInstallResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v3/node_agent/installBGZEgithub.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3b\x06proto3"

var (
	file_node_agent_proto_rawDescOnce sync.Once
	file_node_agent_proto_rawDescData []byte
)

func file_node_agent_proto_rawDescGZIP() []byte {
	file_node_agent_proto_rawDescOnce.Do(func() {
		file_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)))
	})
	return file_node_agent_proto_rawDescData
}

var file_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_agent_proto_goTypes = []any{
	(*NodeAgentInstallReq)(nil),       // 0: v3.NodeAgentInstallReq
	(*NodeAgentInstallResp)(nil),      // 1: v3.NodeAgentInstallResp
	(*NodeAgentInstallResp_Data)(nil), // 2: v3.NodeAgentInstallResp.Data
}
var file_node_agent_proto_depIdxs = []int32{
	2, // 0: v3.NodeAgentInstallResp.data:type_name -> v3.NodeAgentInstallResp.Data
	0, // 1: v3.NodeAgent.NodeAgentInstall:input_type -> v3.NodeAgentInstallReq
	1, // 2: v3.NodeAgent.NodeAgentInstall:output_type -> v3.NodeAgentInstallResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_agent_proto_init() }
func file_node_agent_proto_init() {
	if File_node_agent_proto != nil {
		return
	}
	file_common_proto_init()
	file_node_agent_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_agent_proto_goTypes,
		DependencyIndexes: file_node_agent_proto_depIdxs,
		MessageInfos:      file_node_agent_proto_msgTypes,
	}.Build()
	File_node_agent_proto = out.File
	file_node_agent_proto_goTypes = nil
	file_node_agent_proto_depIdxs = nil
}
