syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

// Page describes the generaic conditions when paging query.
message Page {
  int32 offset = 1;
  int32 limit = 2;
}

// Business describes the business informations.
message Business {
  optional string tenant_id = 1;
  optional int64 bk_biz_id = 2;
  optional string bk_biz_name = 3;
}

// NetworkArea describes the network area informations.
message NetworkArea {
  optional string tenant_id = 1;
  optional int64 bk_networkarea_id = 2;
  optional string bk_networkarea_name = 3;
  optional string cloud_vendor = 4;
}

// Link describes the network unit link points target.
message Link {
  int64 bk_networkarea_id = 1;
  int64 bk_networkunit_id = 2;
  int64 accesspoint_id = 3;
}

// Links describes the network unit links.
message Links {
  Link cluster = 1;
  Link file = 2;
  Link data = 3;
}

// Endpoints describes the links real address.
message Endpoints {
  repeated string cluster = 1;
  repeated string file = 2;
  repeated string data = 3;
}

// CustomInstallerRuntime describes the custom installer runtime config.
message CustomInstallerRuntime { string base_work_dir = 1; }

// CustomGSERuntime describes the custom gse runtime config.
message CustomGSERuntime {
  string base_deploy_dir = 1;
  string data_ipc = 2;
  string plugin_ipc = 3;
  string extra_config_dir = 4;
  string log_dir = 5;
}

// CustomPluginRuntime describes the custom plugin runtime config.
message CustomPluginRuntime {
  string base_deploy_dir = 1;
  string log_dir = 2;
  string data_dir = 3;
  string run_dir = 4;
}

// CustomDeployConfig describes the deploy config for host deployment.
message CustomDeployConfig {
  CustomInstallerRuntime installer_runtime = 1;
  CustomGSERuntime gse_runtime = 2;
  CustomPluginRuntime plugin_runtime = 3;
}

// AccessPoint describes the access point informations.
message AccessPoint {
  optional string tenant_id = 1;
  optional int64 accesspoint_id = 2;
  optional string accesspoint_name = 3;
  optional int64 bk_networkarea_id = 4;

  Endpoints endpoints = 5;
}

// NetworkUnit describes the network unit informations.
message NetworkUnit {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated AccessPoint accesspoints = 5;
  optional Links links = 6;
  optional bool is_direct = 7;
  Endpoints direct_endpoints = 8;
  optional int64 generation = 9;
  map<string, CustomDeployConfig> custom_deploy_config = 10;
}

// NetworkUnitBrief describes the network unit brief informations.
// only contains the access point ids.
message NetworkUnitBrief {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated int64 accesspoints = 5;
  optional Links links = 6;
  optional bool is_direct = 7;
  Endpoints direct_endpoints = 8;
  optional int64 generation = 9;
  map<string, CustomDeployConfig> custom_deploy_config = 10;
}

// HostState describes the host state informations. Usually contains
// agent-related things.
message HostState {
  optional string node_role = 1;
  optional string node_status = 2;
  optional string node_version = 3;
  optional string bk_agent_id = 4;
  optional int64 node_generation = 5;
  repeated string proxy_tags = 6;
}

// HostInfo describes the host info informations. Usually contains static
// configs.
message HostInfo {
  optional int64 bk_biz_id = 1;
  optional int64 bk_networkarea_id = 2;
  optional int64 bk_networkunit_id = 3;
  optional string bk_host_name = 4;
  optional string dept_name = 5;
  repeated string bk_host_innerip_list = 6;
  repeated string bk_host_innerip_v6_list = 7;
  repeated string bk_host_outerip_list = 8;
  repeated string bk_host_outerip_v6_list = 9;
  optional string bk_mac = 10;
  optional string os_type = 11;
  optional string cpu_arch = 12;
  optional string bk_networkarea_name = 13;
  optional string bk_networkunit_name = 14;
  optional string login_ip = 15;
  optional int64 login_port = 16;
  optional string login_user = 17;
  optional string login_mode = 18;
  optional bool login_credit_valid = 19;
  optional string export_ip = 20;
  optional string export_ip_v6 = 21;
  optional string advertise_ip = 22;
  optional string advertise_ip_v6 = 23;
  optional int64 relay_callback_port = 24;
  optional int64 relay_download_port = 25;
}

// Host describes the host informations.
message Host {
  optional string tenant_id = 1;
  optional int64 bk_host_id = 2;
  HostInfo info = 3;
  HostState state = 4;
  optional uint64 create_at = 5;
  optional uint64 updated_at = 6;
}

// NetworkUnitGraph describes the graph networkunit informations.
message NetworkUnitGraph {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated int64 accesspoints = 5;
}

// LinkGraph describes the graph link informations between networkunits.
message LinkGraph {
  optional int64 source_networkunit_id = 1;
  optional int64 target_networkunit_id = 2;
  optional int64 target_accesspoint_id = 3;
  repeated string channel = 4;
}

// TopoEvent describes the topo event.
message TopoEvent {
  optional string tenant_id = 1;
  optional string type = 2;
  optional int64 bk_networkarea_id = 3;
  optional string bk_networkarea_name = 4;
  optional int64 bk_networkunit_id = 5;
  optional string bk_networkunit_name = 6;
  optional int64 accesspoint_id = 7;
  optional string accesspoint_name = 8;
  optional int64 operate_time = 9;
  optional string operator = 10;
}

// TimeRange describes the time range.
message TimeRange {
  int64 start_timestamp_sec = 1;
  int64 end_timestamp_sec = 2;
}

// Release describes the release.
message Release {
  optional string name = 1;
  optional int64 generation = 2;
  optional string release_type = 3;
  optional string os_type = 4;
  optional string cpu_arch = 5;
  optional string version = 6;
  optional string file_name = 7;
  repeated string labels = 8;
  optional bool enabled = 9;
  optional bool as_default = 10;
  optional string md5 = 11;
  optional uint64 updated_at = 12;
  optional string operator = 13;
}

message ReleaseAgent {
  Release release = 1;
  optional string change_log_en = 2;
  optional string change_log_zh = 3;
}
message ReleaseProxy {
  Release release = 1;
  optional string change_log_en = 2;
  optional string change_log_zh = 3;
}

// ReleasePlugin describes the release plugin.
message ReleasePlugin { Release release = 1; }

// ReleaseCert describes the release cert.
message ReleaseCert { Release release = 1; }

// ReleaseBinTool describes the release bin tool.
message ReleaseBinTool { Release release = 1; }

// ReleasePluginBinTool describes the release plugin bin tool.
message ReleasePluginBinTool { Release release = 1; }

// Platform describes the platform informations.
message Platform {
  string os_type = 1;
  string cpu_arch = 2;
}

message TargetVersion {
  string version = 1;
  string cpu_arch = 2;
  string os_type = 3;
}

// PackageEvent describes the package event.
message PackageEvent {
  optional string name = 1;
  optional string event_type = 2;
  optional int64 generation = 3;
  optional string release_type = 4;
  optional string os_type = 5;
  optional string cpu_arch = 6;
  optional string version = 7;
  optional int64 operate_time = 8;
  optional string operator = 9;
}

// ConfigPolicyScope describes the config policy scope.
message ConfigPolicyScope {
  optional int64 bk_networkarea_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string os_type = 3;
  optional string cpu_arch = 4;
}

// ConfigPolicyConfig describes the config policy config.
message ConfigPolicyConfigItem {
  optional string id = 1;
  optional bool enabled = 2;
  optional string name_en = 3;
  optional string name_zh = 4;
  optional string remark_en = 5;
  optional string remark_zh = 6;
  optional string key = 7;
  optional int64 type = 8;
  optional string value_string = 9;
  optional int64 value_int = 10;
  optional bool value_bool = 11;
  repeated string value_string_select = 12;
  repeated int64 value_int_select = 13;
}

// ConfigPolicyConfigBlock describes the config policy config block.
message ConfigPolicyConfigBlock {
  optional string id = 1;
  optional string title_en = 2;
  optional string title_zh = 3;
  repeated ConfigPolicyConfigItem items = 4;
}

// ConfigPolocy decribes the config policy.
message ConfigPolicy {
  optional string tenant_id = 1;
  optional int64 configpolicy_id = 2;
  optional string configpolicy_name = 3;
  optional string type = 4;
  optional int64 bk_biz_id = 5;
  optional string remark = 6;
  repeated ConfigPolicyScope scopes = 7;
  repeated ConfigPolicyConfigBlock configs = 8;
  optional bool enabled = 9;
  optional int64 updated_time = 10;
  optional string operator = 11;
  optional int64 version = 12;
  optional int64 priority = 13;
  repeated int64 target_host_ids = 14;
}

// ConfigPolicyEvent describes the config policy event.
message ConfigPolicyEvent {
  optional string tenant_id = 1;
  optional int64 configpolicy_id = 2;
  optional string configpolicy_name = 3;
  optional string configpolicy_type = 4;
  optional string type = 5;
  optional int64 version = 6;
  optional int64 operate_time = 7;
  optional string operator = 8;
  optional int64 bk_biz_id = 9;
}

// ProcessInfo describes the process information.
message ProcessInfo {
  optional int32 pid = 1;
  optional string version = 2;
  optional string agent_id = 3;
  optional bool auto_start = 4;
  optional string status = 5;
}

// ProcessIdentity describes the process identity.
message ProcessIdentity {
  optional string name = 1;
  optional string setup_path = 2;
  optional string pid_path = 3;
  optional string config_path = 4;
  optional string log_path = 5;
  optional string user = 6;
}

// ProcessController describes the process controller.
message ProcessController {
  optional string start_cmd = 1;
  optional string stop_cmd = 2;
  optional string restart_cmd = 3;
  optional string reload_cmd = 4;
  optional string kill_cmd = 5;
  optional string version_cmd = 6;
  optional string health_cmd = 7;
}

// ProcessResource describes the process resource.
message ProcessResource {
  optional double cpu_limit_percent = 1;
  optional double mem_limit_percent = 2;
}

// ProcessMonitorPolicy describes the process monitor policy.
message ProcessMonitorPolicy {
  optional string restart_type = 1;
  optional int64 start_check_seconds = 2;
  optional int64 stop_check_seconds = 3;
  optional int64 operate_timeout_seconds = 4;
}

message Process {
  optional string tenant_id = 1;
  optional int64 bk_host_id = 2;
  optional string plugin_name = 3;
  optional string plugin_pkg_name = 4;
  optional string plugin_group = 5;
  optional Platform platform = 6;
  optional int64 generation = 7;
  optional ProcessInfo process_info = 8;
  optional ProcessIdentity process_identity = 9;
  optional ProcessController process_controller = 10;
  optional ProcessResource process_resource = 11;
  optional ProcessMonitorPolicy process_monitor_policy = 12;
}

message Plugin {
  optional string tenant_id = 1;
  optional string name = 2;
  optional string group = 3;
  optional string pkg_name = 4;
  optional string memo = 5;
}

message Error {
  string system = 1;
  string message = 2;
  message Details {
    string code = 1;
    string message = 2;
  }
  repeated Details details = 3;
}

message RelatedResourceType {
  string system_id = 1;
  string type = 2;
  string type_name = 3;
}

message Action {
  string id = 1;
  string name = 2;
  repeated RelatedResourceType related_resource_types = 3;
}

message Permission {
  string system = 1;
  string system_name = 2;
  string apply_url = 3;
  repeated Action actions = 4;
}
