syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// NodeWorkflowInfo describes the node workflow information.
message NodeWorkflowInfo {
  optional string workflow_id = 1;
  optional string trigger_id = 2;
  optional string type = 3;
  repeated int64 bk_biz_id = 4;
  optional string operator = 5;
  optional int64 operate_time = 6;
  optional int64 finish_time = 7;
  optional string status = 8;
  repeated string bk_biz_name = 9;
}

// NodeWorkflowExactConditions describes the exact conditions of node workflow
// list request.
message NodeWorkflowExactConditions {
  repeated string workflow_id = 1;
  repeated string type = 2;
  repeated int64 bk_biz_id = 3;
  repeated string status = 4;
  repeated string operator = 5;
}

// NodeWorkflowFuzzyConditions describes the fuzzy conditions of node workflow
// list request.
message NodeWorkflowFuzzyConditions {}

// NodeWorkflowListReq describes the node workflow list request.
message NodeWorkflowListReq {
  Page page = 1;
  bool only_count = 2;

  NodeWorkflowExactConditions exact_include_conditions = 3;
  NodeWorkflowFuzzyConditions fuzzy_include_conditions = 4;
  TimeRange operate_time_range = 5;
}

// NodeWorkflowListResp describes the node workflow list response.
message NodeWorkflowListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated NodeWorkflowInfo items = 2;
  }
  Data data = 5;
}

// NodeWorkflowStatisticReq describes the node workflow statistic request.
message NodeWorkflowStatisticsReq { repeated string workflow_id = 1; }

// NodeWorkflowStatisticResp describes the node workflow statistic response.
message NodeWorkflowStatisticsResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message StatisticsInfo {
    optional string workflow_id = 1;
    optional int64 total_count = 2;
    optional int64 init_count = 3;
    optional int64 launched_count = 4;
    optional int64 running_count = 5;
    optional int64 success_count = 6;
    optional int64 failed_count = 7;
    optional int64 timeout_count = 8;
    optional int64 terminated_count = 9;
  }
  message Data { repeated StatisticsInfo items = 1; }
  Data data = 5;
}

// NodeWorkflowDistinctReq describes the node workflow distinct request.
message NodeWorkflowDistinctReq {
  NodeWorkflowExactConditions exact_include_conditions = 1;
  NodeWorkflowFuzzyConditions fuzzy_include_conditions = 2;
}

// NodeWorkflowDistinctResp describes the node workflow distinct response.
message NodeWorkflowDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    repeated string type = 1;
    repeated int64 bk_biz_id = 2;
    repeated string operator = 3;
    repeated string status = 4;
  }
  Data data = 5;
}

message NodeWorkflowOperationParam {
  int64 bk_networkarea_id = 1;
  int64 bk_networkunit_id = 2;
  string bk_host_inner = 3;
  string bk_host_innerip_v6 = 4;
  string node_version = 5;
  int64 bk_biz_id = 6;
  string operator = 7;
}

message NodeWorkflowOperation {
  string operation_id = 1;
  repeated string instance_ids = 2;
  NodeWorkflowOperationParam param = 3;
  NodeWorkflowOperationStatus status = 4;
}

message NodeWorkflowOperationStatus {
  string state = 1;
  int64 total_time_second = 2;
}

message Lifecycle {
  string state = 1;
  int64 operate_time = 2;
  int64 finish_time = 3;
}

// NodeWorflowOperationInstance describes the node operation instance.
message NodeWorflowOperationInstance {
  string operation_id = 1;
  string oper_inst_id = 2;
  string oper_inst_status = 3;
  string bk_host_innerip = 4;
  string bk_networkunit_id = 5;
  string bk_biz_id = 6;
  string node_version = 7;

  message Action {
    string action_name = 1;
    string action_status = 2;
    int64 cost_time_sec = 3;
  }
  repeated Action action = 8;
}

message NodeWorflowOperationInstanceData {
  string operation_id = 1;
  string oper_inst_id = 2;
  string oper_inst_status = 3;
  string operation_def_name = 4;
  string parent_operation_id = 5;
  repeated string action_names = 6;
}

// NodeWorkflowOperationExactConditions describes the exact conditions of node
// workflow operation list request.
message NodeWorkflowOperationExactConditions {
  string workflow_id = 1;
  repeated string node_version = 2;
  repeated string bk_host_innerip = 3;
  repeated string bk_host_innerip_v6 = 4;
  repeated int64 bk_biz_id = 5;
  repeated int64 bk_networkarea_id = 6;
  repeated string state = 7;
}

// NodeWorkflowOperationFuzzyConditions describes the fuzzy conditions of node
// workflow list request.
message NodeWorkflowOperationFuzzyConditions {}

// NodeWorkflowOperationListReq describes the node operation list
// request.
message NodeWorkflowOperationListReq {
  bool only_count = 1;
  Page page = 2;
  NodeWorkflowOperationExactConditions exact_include_conditions = 3;
  NodeWorkflowOperationFuzzyConditions fuzzy_include_conditions = 4;
}

// NodeWorkflowOperationListResp describes the node operation list by
message NodeWorkflowOperationListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    repeated NodeWorkflowOperation operations = 1;
    int64 total_count = 2;
  }
  Data data = 5;
}

// NodeWorkflowOperationInstanceListReq describes the node operation instance
// list by operation-id request.
message NodeWorkflowOperationInstanceListReq {
  bool only_count = 1;
  string operation_id = 2;
}

// NodeWorkflowOperationInstanceListResp describes the node operation instance
// list by operation-id response.
message NodeWorkflowOperationInstanceListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated NodeWorflowOperationInstanceData oper_inst_data = 2;
  }
  Data data = 5;
}

// NodeWorkflowInstanceStatusExactConditions describes the exact conditions of
// node workflow
message NodeWorkflowInstanceStatusExactConditions {
  repeated string trigger_id = 1;
}

// NodeWorkflowInstanceStatusFuzzyConditions describes the fuzzy conditions of
// node workflow list request.
message NodeWorkflowInstanceStatusFuzzyConditions {}

// NodeWorkflowOperationInstanceStatusListReq ...
message NodeWorkflowOperationInstanceListStatusReq {
  Page page = 1;
  NodeWorkflowInstanceStatusExactConditions exact_include_conditions = 3;
  NodeWorkflowInstanceStatusFuzzyConditions fuzzy_include_conditions = 4;
}

message NodeWorkflowOperationInstanceStatus {
  int64 index = 1;
  string instance_id = 2;
  string status = 3;
  string trigger_id = 4;
}

message NodeWorkflowOperationInstanceListStatusResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data { repeated NodeWorkflowOperationInstanceStatus items = 1; }
  Data data = 5;
}

// NodeWorkflowOperationInstanceLogGetReq describes the node operation instance

message NodeWorkflowOperationInstanceLogGetReq { string oper_inst_id = 1; }

// NodeWorkflowOperationInstanceLogGetResp describes the node operation action
// instance log
message NodeWorkflowOperationInstanceLogGetResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    map<string, NodeWorkflowActionData> oper_inst_logs = 2;
  }
  Data data = 5;
}

message LifeCycle {
  string state = 1;
  int64 create_time = 2;
  int64 start_time = 3;
  int64 end_time = 4;
}

message NodeWorkflowActionMessage {
  message Message {
    int64 time = 1;
    string text = 2;
    string level = 3;
  }
  repeated Message logs = 1;
}

message NodeWorkflowActionData {
  LifeCycle life_cycle = 1;
  NodeWorkflowActionMessage message = 2;
}

// NodeWorkflowOperationRetryReq
message NodeWorkflowOperationRetryReq {
  string workflow_id = 1;
  string retry_mod = 2;
  repeated string operation_id = 3;
}

// NodeWorkflowOperationRetryResp
message NodeWorkflowOperationRetryResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

service NodeWorkflow {
  // NodeWorkflowList provides node workflow list.
  rpc NodeWorkflowList(NodeWorkflowListReq) returns (NodeWorkflowListResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/list"
      body : "*"
    };
  }

  // NodeWorkflowStatistics provides node workflow statistics.
  rpc NodeWorkflowStatistics(NodeWorkflowStatisticsReq)
      returns (NodeWorkflowStatisticsResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/statistics"
      body : "*"
    };
  }

  // NodeWorkflowDistinct provides node workflow distinct.
  rpc NodeWorkflowDistinct(NodeWorkflowDistinctReq)
      returns (NodeWorkflowDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/distinct"
      body : "*"
    };
  }

  // NodeWorkflowOperationList provides node workflow operation list.
  rpc NodeWorkflowOperationList(NodeWorkflowOperationListReq)
      returns (NodeWorkflowOperationListResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/operation/list"
      body : "*"
    };
  }

  // NodeWorkflowOperationInstanceList provides node workflow operation instance
  // list.
  rpc NodeWorkflowOperationInstanceList(NodeWorkflowOperationInstanceListReq)
      returns (NodeWorkflowOperationInstanceListResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/operation/instance/list"
      body : "*"
    };
  }

  // NodeWorkflowOperationInstanceLogGet provides node operation instance log
  // get.
  rpc NodeWorkflowOperationInstanceLogGet(
      NodeWorkflowOperationInstanceLogGetReq)
      returns (NodeWorkflowOperationInstanceLogGetResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/operation/instance/log/get"
      body : "*"
    };
  }

  // NodeWorkflowOperationRetry retry node operation.
  rpc NodeWorkflowOperationRetry(NodeWorkflowOperationRetryReq)
      returns (NodeWorkflowOperationRetryResp) {
    option (google.api.http) = {
      post : "/api/v3/node/workflow/operation/retry"
      body : "*"
    };
  }
}
