syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// NodeProxyInstallHost describes the node proxy install host.
message NodeProxyInstallHost {
  int64 bk_biz_id = 1;
  int64 bk_networkunit_id = 2;
  optional int64 bk_host_id = 3;
  string bk_addressing = 4;
  string bk_host_innerip = 5;
  string bk_host_innerip_v6 = 6;
  string os_type = 7;
  string login_ip = 8;
  int64 login_port = 9;
  string login_user = 10;
  // support: password_vault, password, keyfile
  string login_mode = 11;
  string login_password = 12;
  string login_key_file = 13;
  string export_ip = 14;
  string export_ip_v6 = 15;
  string advertise_ip = 16;
  string advertise_ip_v6 = 17;
  bool re_register = 18;
  repeated string proxy_tags = 19;
  int64 proxy_install_origin_unit_id = 20;
  // credit expired interval in seconds, default is 86400 (24 hours)
  int64 credit_expired_interval_sec = 21;
  int64 relay_download_port = 22;
  int64 relay_callback_port = 23;
  string cpu_arch = 24;
}

// NodeProxyInstallReq describes the node proxy install request.
message NodeProxyInstallReq {
  repeated NodeProxyInstallHost host = 1;
  repeated TargetVersion target_version = 2;
  bool is_manual = 3;
  bool is_offline = 4;
}

// NodeProxyInstallResp describes the node proxy install response.
message NodeProxyInstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

message NodeProxyUpgradeHost {
  int64 bk_host_id = 1;
  bool force = 2;
  int64 graceful_restart_timeout_sec = 3;
}

// NodeProxyUpgradeReq describes the node proxy upgrade request.
message NodeProxyUpgradeReq {
  repeated NodeProxyUpgradeHost host = 1;
  repeated TargetVersion target_version = 2;
}

// NodeProxyUpgradeResp describes the node proxy upgrade response.
message NodeProxyUpgradeResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

message NodeProxyReconfigHost {
  int64 bk_host_id = 1;
  bool force = 2;
  int64 graceful_restart_timeout_sec = 3;
}
// NodeProxyReconfigReq describes the node proxy reconfig request.
message NodeProxyReconfigReq { repeated NodeProxyReconfigHost host = 1; }

// NodeProxyReconfigResp describes the node proxy reconfig response.
message NodeProxyReconfigResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

message NodeProxyRestartHost {
  int64 bk_host_id = 1;
  bool force = 2;
  int64 graceful_restart_timeout_sec = 3;
}
// NodeProxyRestartReq describes the node proxy restart request.
message NodeProxyRestartReq { repeated NodeProxyRestartHost host = 1; }

// NodeProxyRestartResp describes the node proxy restart response.
message NodeProxyRestartResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// NodeProxyUpdateHost describes the node proxy update host.
message NodeProxyUpdateHost {
  int64 bk_host_id = 1;
  string login_ip = 2;
  int64 login_port = 3;
  string login_user = 4;
  // support: password_vault, password, keyfile
  string login_mode = 5;
  string login_password = 6;
  string login_key_file = 7;
  string export_ip = 8;
  string export_ip_v6 = 9;
  string advertise_ip = 10;
  string advertise_ip_v6 = 11;
  repeated string proxy_tags = 12;
  int64 relay_download_port = 13;
  int64 relay_callback_port = 14;
}

message NodeProxyUninstallHost { int64 bk_host_id = 1; }

// NodeProxyUninstallReq describes the node proxy uninstall request.
message NodeProxyUninstallReq { repeated NodeProxyUninstallHost host = 1; }

// NodeProxyUninstallResp describes the node proxy uninstall response.
message NodeProxyUninstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// NodeProxyUpdateReq describes the node proxy update request.
message NodeProxyUpdateReq { repeated NodeProxyUpdateHost Host = 1; }

// NodeProxyUpdateResp describes the node proxy update response.
message NodeProxyUpdateResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// ProxyInstallCheckInfo describes the node proxy install check parameter.
message ProxyInstallCheckInfo {
  optional int64 bk_biz_id = 1;
  optional int64 bk_host_id = 2;
  repeated string bk_host_innerip_list = 3;
  repeated string bk_host_innerip_v6_list = 4;
  optional int64 bk_networkunit_id = 5;
}

// NodeProxyInstallCheckReq describes the node proxy install check request.
message NodeProxyInstallCheckReq { repeated ProxyInstallCheckInfo host = 1; }

// NodeProxyInstallCheckResp describes the response for node proxy installation
// check.
message NodeProxyInstallCheckResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { repeated NodeProxyInstallCheckResult results = 1; }
  Data data = 5;
}

// NodeProxyInstallCheckMatchedItem describes the matched item for proxy node.
message NodeProxyInstallCheckMatchedItem {
  optional int64 bk_host_id = 1;
  optional int64 bk_biz_id = 2;
  optional int64 bk_networkarea_id = 3;
  optional int64 bk_networkunit_id = 4;
  string os_type = 5;
  string node_role = 6;
  repeated string bk_host_innerip_list = 7;
  repeated string bk_host_innerip_v6_list = 8;
}

// NodeProxyInstallCheckResult describes the check result for node proxy
// installation.
message NodeProxyInstallCheckResult {
  string status = 1;
  NodeProxyInstallCheckMatchedItem matched = 2;
  string message_en = 3;
  string message_zh = 4;
  string category = 5;
}

service NodeProxy {
  // NodeProxyInstall installs node proxy.
  rpc NodeProxyInstall(NodeProxyInstallReq) returns (NodeProxyInstallResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/install"
      body : "*"
    };
  }

  // NodeProxyUpgrade upgrades node proxy.
  rpc NodeProxyUpgrade(NodeProxyUpgradeReq) returns (NodeProxyUpgradeResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/upgrade"
      body : "*"
    };
  }

  // NodeProxyRestart restarts node proxy.
  rpc NodeProxyRestart(NodeProxyRestartReq) returns (NodeProxyRestartResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/restart"
      body : "*"
    };
  }

  // NodeProxyReconfig reconfigs node proxy.
  rpc NodeProxyReconfig(NodeProxyReconfigReq) returns (NodeProxyReconfigResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/reconfig"
      body : "*"
    };
  }

  // NodeProxyUpdate updates node proxy.
  rpc NodeProxyUpdate(NodeProxyUpdateReq) returns (NodeProxyUpdateResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/update"
      body : "*"
    };
  }

  // NodeProxyUninstall uninstall node proxy.
  rpc NodeProxyUninstall(NodeProxyUninstallReq)
      returns (NodeProxyUninstallResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/uninstall"
      body : "*"
    };
  }

  // NodeProxyInstallCheck checks node proxy install.
  rpc NodeProxyInstallCheck(NodeProxyInstallCheckReq)
      returns (NodeProxyInstallCheckResp) {
    option (google.api.http) = {
      post : "/api/v3/node/proxy/install_check"
      body : "*"
    };
  }
}