syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// PackageUploadOriginAgentReq is the request for upload origin agent pkg.
message PackageUploadOriginAgentReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// PackageUploadOriginAgentResp is the response for upload origin agent pkg.
message PackageUploadOriginAgentResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    optional string change_log_en = 8;
    optional string change_log_zh = 9;
    repeated Platform platforms = 10;
  }
  Data data = 5;
}

// PackageUploadOriginServerReq is the request for upload origin server pkg.
message PackageUploadOriginServerReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// PackageUploadOriginServerResp is the response for upload origin server pkg.
message PackageUploadOriginServerResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    optional string version = 7;
    repeated Platform platforms = 8;
    optional string change_log_en = 9;
    optional string change_log_zh = 10;
  }
  Data data = 5;
}

// PackageUploadOriginCertResp is the response for upload origin cert pkg.
message PackageUploadOriginCertReq { bool overwrite = 1; }

// PackageUploadOriginCertResp is the response for upload origin cert pkg.
message PackageUploadOriginCertResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    repeated string cert_files = 7;
  }
  Data data = 5;
}

// PackageUploadOriginBinToolReq is the request for upload origin bin tool pkg.
message PackageUploadOriginBinToolReq {
  int64 generation = 1;
  bool overwrite = 2;
}

// PackageUploadOriginBinToolResp is the response for upload origin bin tool
// pkg.
message PackageUploadOriginBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    optional string upload_id = 1;
    optional bool existed = 2;
    optional bool generated = 3;
    optional string name = 4;
    optional int64 size = 5;
    optional string md5 = 6;
    repeated Platform agent_platforms = 7;
    repeated Platform proxy_platforms = 8;
  }
  Data data = 5;
}

// PackagePublishReleaseAgentReq is the request for upload release agent pkg.
message PackagePublishReleaseAgentReq { string upload_id = 1; }

// PackagePublishReleaseAgentResp is the response for upload release agent pkg.
message PackagePublishReleaseAgentResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackagePublishReleaseProxyReq is the request for upload release proxy pkg.
message PackagePublishReleaseProxyReq { string upload_id = 1; }

// PackagePublishReleaseProxyResp is the response for upload release proxy pkg.
message PackagePublishReleaseProxyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackagePublishReleaseCertReq is the request for upload release cert pkg.
message PackagePublishReleaseCertReq { string upload_id = 1; }

// PackagePublishReleaseCertResp is the response for upload release cert pkg.
message PackagePublishReleaseCertResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackagePublishReleaseBinToolReq is the request for upload release bintool
// pkg.
message PackagePublishReleaseBinToolReq { string upload_id = 1; }

// PackagePublishReleaseBinToolResp is the response for upload release bintool
// pkg.
message PackagePublishReleaseBinToolResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseExactConditions describes release exact conditions.
message PackageReleaseExactConditions {
  repeated int64 generation = 1;
  repeated string release_type = 2;
  repeated Platform platform = 3;
  repeated string version = 4;
  repeated bool as_default = 5;
  repeated bool enabled = 6;
}

// PackageReleaseListReq describes the HTTP request body when list package
// release.
message PackageReleaseListReq {
  Page page = 1;
  string release_type = 2;
  int64 generation = 3;
  bool only_count = 4;

  PackageReleaseExactConditions exact_include_conditions = 5;
}

// PackageReleaseListResp describes the HTTP response body when list package
// release.
message PackageReleaseListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated Release items = 2;
  }
  Data data = 5;
}

// PackageReleaseSetLabelsReq describes the HTTP request body when set labels.
message PackageReleaseSetLabelsReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
  repeated string labels = 5;
}

// PackageReleaseSetLabelsResp describes the HTTP response body when set
// labels.
message PackageReleaseSetLabelsResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseSetLabelsManyIdentity describes the HTTP request body.
message PackageReleaseSetLabelsManyIdentity {
  int64 generation = 1;
  Platform platform = 2;
  string version = 3;
}
// PackageReleaseSetLabelsManyReq describes the HTTP request body when set many
// labels.
message PackageReleaseSetLabelsManyReq {
  string release_type = 1;
  repeated PackageReleaseSetLabelsManyIdentity identify = 2;
  repeated string labels = 3;
}

// PackageReleaseSetLabelsManyResp describes the HTTP response body when set
// many labels.
message PackageReleaseSetLabelsManyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseEnableReq describes the HTTP request body when enable package
// release.
message PackageReleaseEnableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseEnableResp describes the HTTP response body when enable package
// release.
message PackageReleaseEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseDisableReq describes the HTTP request body when disable package
// release.
message PackageReleaseDisableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseDisableResp describes the HTTP response body when disable
// package release.
message PackageReleaseDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseSetAsDefaultReq describes the HTTP request body when set
// default package release.
message PackageReleaseSetAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseSetAsDefaultResp describes the HTTP response body when set
// default package release.
message PackageReleaseSetAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseCancelAsDefaultReq describes the HTTP request body when cancel
// default package release.
message PackageReleaseCancelAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseCancelAsDefaultResp describes the HTTP response body when
// cancel default package release.
message PackageReleaseCancelAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseDeleteReq describes the HTTP request body when delete release.
message PackageReleaseDeleteReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseDeleteResp describes the HTTP response body when delete
// release.
message PackageReleaseDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// CountRequestItem describes  the HTTP request body when count release
// deployed_host.
message CountRequestItem {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseDeployedHostCountReq describes the HTTP request body when count
// deployed host.
message PackageReleaseDeployedHostCountReq {
  repeated CountRequestItem request_items = 1;
}

// PackageReleaseDeployedHostCountResp describes the HTTP response body when
// count deployed host.
message PackageReleaseDeployedHostCountResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated int64 items = 2;
  }
  Data data = 5;
}

// PackageReleaseAgentDownloadReq is the request for download agent pkg.
message PackageReleaseAgentDownloadReq {
  int64 generation = 1;
  Platform platform = 2;
  string version = 3;
}

// PackageReleaseProxyDownloadReq is the request for download proxy pkg.
message PackageReleaseProxyDownloadReq {
  int64 generation = 1;
  Platform platform = 2;
  string version = 3;
}

// FileChunk describes the file chunk data.
message FileChunk { bytes content = 1; }

// PackageEventExactConditions describes the conditions when list event.
message PackageEventExactConditions {
  repeated int64 generation = 1;
  repeated string os_type = 2;
  repeated string cpu_arch = 3;
  repeated string release_type = 4;
  repeated string operator = 5;
  repeated string event_type = 6;
  repeated string version = 7;
}

// PackageEventFuzzyConditions describes the conditions when list event
message PackageEventFuzzyConditions {}

// PackageEventListReq describes the HTTP request body when list event in
// Package service.
message PackageEventListReq {
  Page page = 1;
  bool only_count = 2;

  PackageEventExactConditions exact_include_conditions = 3;
  PackageEventFuzzyConditions fuzzy_include_conditions = 4;
  TimeRange operate_time_range = 5;
}

// PackageEventListResp describes the HTTP response body when list event in
// Package service.
message PackageEventListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated PackageEvent items = 2;
  }
  Data data = 5;
}

// PackageEventDistinctReq describes the HTTP request body when distinct
// packageevent in package service.
message PackageEventDistinctReq {
  PackageEventExactConditions exact_include_conditions = 1;
  PackageEventFuzzyConditions fuzzy_include_conditions = 2;
  TimeRange operate_time_range = 3;
}

// PackageEventDistinctResp describes the HTTP response body when distinct
// packageevent in package service.
message PackageEventDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    repeated string release_type = 1;
    repeated string event_type = 2;
    repeated string os_type = 3;
    repeated string cpu_arch = 4;
    repeated string version = 5;
    repeated string operator = 6;
  }
  Data data = 5;
}

service Package {
  // UploadOriginAgent provides origin agent upload.
  rpc UploadOriginAgent(PackageUploadOriginAgentReq)
      returns (PackageUploadOriginAgentResp) {
    option (google.api.http) = {
      post : "/api/v3/package/upload/origin/agent"
      body : "*"
    };
  }

  // UploadOriginServer provides origin server upload.
  rpc UploadOriginServer(PackageUploadOriginServerReq)
      returns (PackageUploadOriginServerResp) {
    option (google.api.http) = {
      post : "/api/v3/package/upload/origin/server"
      body : "*"
    };
  }

  // UploadOriginCert provides origin cert upload.
  rpc UploadOriginCert(PackageUploadOriginCertReq)
      returns (PackageUploadOriginCertResp) {
    option (google.api.http) = {
      post : "/api/v3/package/upload/origin/cert"
      body : "*"
    };
  }

  // UploadOriginBinTool provides origin bintool upload.
  rpc UploadOriginBinTool(PackageUploadOriginBinToolReq)
      returns (PackageUploadOriginBinToolResp) {
    option (google.api.http) = {
      post : "/api/v3/package/upload/origin/bintool"
      body : "*"
    };
  }

  // PublishReleaseAgent provides release agent publish.
  rpc PublishReleaseAgent(PackagePublishReleaseAgentReq)
      returns (PackagePublishReleaseAgentResp) {
    option (google.api.http) = {
      post : "/api/v3/package/publish/release/agent"
      body : "*"
    };
  }

  // PublishReleaseServer provides release server publish.
  rpc PublishReleaseProxy(PackagePublishReleaseProxyReq)
      returns (PackagePublishReleaseProxyResp) {
    option (google.api.http) = {
      post : "/api/v3/package/publish/release/proxy"
      body : "*"
    };
  }

  // PublishReleaseCert provides release cert publish.
  rpc PublishReleaseCert(PackagePublishReleaseCertReq)
      returns (PackagePublishReleaseCertResp) {
    option (google.api.http) = {
      post : "/api/v3/package/publish/release/cert"
      body : "*"
    };
  }

  // PublishReleaseBinTool provides release bintool publish.
  rpc PublishReleaseBinTool(PackagePublishReleaseBinToolReq)
      returns (PackagePublishReleaseBinToolResp) {
    option (google.api.http) = {
      post : "/api/v3/package/publish/release/bintool"
      body : "*"
    };
  }

  // ListRelease lists releases.
  rpc ListRelease(PackageReleaseListReq) returns (PackageReleaseListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/list"
      body : "*"
    };
  }

  // SetReleaseLabels sets release labels.
  rpc SetReleaseLabels(PackageReleaseSetLabelsReq)
      returns (PackageReleaseSetLabelsResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_labels"
      body : "*"
    };
  }

  // SetReleaseLabeslMany sets many release labels.
  rpc SetReleaseLabelsMany(PackageReleaseSetLabelsManyReq)
      returns (PackageReleaseSetLabelsManyResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_labels_many"
      body : "*"
    };
  }

  // EnableRelease enables release.
  rpc EnableRelease(PackageReleaseEnableReq)
      returns (PackageReleaseEnableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/enable"
      body : "*"
    };
  }

  // DisableRelease disables release.
  rpc DisableRelease(PackageReleaseDisableReq)
      returns (PackageReleaseDisableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/disable"
      body : "*"
    };
  }

  // SetAsDefaultRelease sets release as default.
  rpc SetAsDefaultRelease(PackageReleaseSetAsDefaultReq)
      returns (PackageReleaseSetAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_as_default"
      body : "*"
    };
  }

  // CancelAsDefaultRelease cancels release as default.
  rpc CancelAsDefaultRelease(PackageReleaseCancelAsDefaultReq)
      returns (PackageReleaseCancelAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/cancel_as_default"
      body : "*"
    };
  }

  // DeleteRelease deletes release.
  rpc DeleteRelease(PackageReleaseDeleteReq)
      returns (PackageReleaseDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/delete"
      body : "*"
    };
  }

  // DeployedHostCount count deployed host.
  rpc DeployedHostCount(PackageReleaseDeployedHostCountReq)
      returns (PackageReleaseDeployedHostCountResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/deployed_host/count"
      body : "*"
    };
  }

  // DownloadAgent download release agent package.
  rpc DownloadAgent(PackageReleaseAgentDownloadReq) returns (FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/download"
      body : "*"
    };
  }

  // DownloadProxy download release proxy package.
  rpc DownloadProxy(PackageReleaseProxyDownloadReq) returns (FileChunk) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/download"
      body : "*"
    };
  }

  // PackageEventList provides package event listing.
  rpc PackageEventList(PackageEventListReq) returns (PackageEventListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/event/list"
      body : "*"
    };
  }

  // PackageEventDistinct provides package event distincting.
  rpc PackageEventDistinct(PackageEventDistinctReq)
      returns (PackageEventDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/package/event/distinct"
      body : "*"
    };
  }
}