syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

import "common.proto";

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

// PluginInstallReq describes the plugin install request.
message PluginInstallReq {
  message Plugin {
    optional int64 bk_host_id = 1;
    string plugin_name = 2;
    string version = 3;
    repeated string config_name = 4;
    optional google.protobuf.Struct custom_config_context = 5;
  }

  repeated Plugin plugin = 1;
}

// PluginInstallResp describes the plugin install response.
message PluginInstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginApplySubConfigReq describes the plugin apply sub-configuration
// request.
message PluginApplySubConfigReq {
  message Plugin {
    optional int64 bk_host_id = 1;
    string plugin_name = 2;
    string version = 3;
    repeated string config_name = 4;
    optional google.protobuf.Struct custom_config_context = 5;
  }

  repeated Plugin plugin = 1;
}

// PluginApplySubConfigResp describes the plugin apply sub-configuration
// response.
message PluginApplySubConfigResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginListReq describes the plugin list request.
message PluginListReq {
  Page page = 1;
  bool only_count = 2;

  message ExactConditions {
    repeated string name = 1;
    repeated string group = 2;
  }
  ExactConditions exact_include_conditions = 3;

  message FuzzyConditions {
    repeated string name = 1;
    repeated string pkg_name = 2;
  }
  FuzzyConditions fuzzy_include_conditions = 4;
}

// PluginListResp describes the plugin list response.
message PluginListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Plugin {
    optional string tenant_id = 1;
    optional string name = 2;
    optional string group = 3;
    optional string pkg_name = 4;
  }

  message Data {
    int64 total = 1;
    repeated Plugin items = 2;
  }
  Data data = 5;
}

service Plugin {
  // InstallPlugin installs a plugin on specified hosts.
  rpc InstallPlugin(PluginInstallReq) returns (PluginInstallResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/install"
      body : "*"
    };
  }

  // ApplyPluginSubConfig apply sub-configuration for a plugin on specified
  // hosts.
  rpc ApplyPluginSubConfig(PluginApplySubConfigReq)
      returns (PluginApplySubConfigResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/apply_subconfig"
      body : "*"
    };
  }

  // ListPlugins lists plugins based on the given conditions.
  rpc ListPlugins(PluginListReq) returns (PluginListResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/list"
      body : "*"
    };
  }
}