syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

import "common.proto";

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

// PluginInstallReq describes the plugin install request.
message PluginInstallReq {
  message DeploymentSpec {
    optional ProcessResource resource = 1;
    optional ProcessMonitorPolicy monitor_policy = 2;
  }

  message InstallInfo {
    int64 bk_host_id = 1;
    string plugin_name = 2;
    string version = 3;
    repeated string config_template_name = 4;
    optional google.protobuf.Struct custom_config_context = 5;
    optional DeploymentSpec custom_spec = 6;
  }

  repeated InstallInfo plugin = 1;
}

// PluginInstallResp describes the plugin install response.
message PluginInstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginUpgradeReq describes the plugin upgrade request.
message PluginUpgradeReq {
  message UpgradeInfo {
    int64 bk_host_id = 1;
    string plugin_name = 2;
    string version = 3;
    repeated string config_template_name = 4;
    optional google.protobuf.Struct custom_config_context = 5;
  }

  repeated UpgradeInfo plugin = 1;
}

// PluginUpgradeResp describes the plugin upgrade response.
message PluginUpgradeResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginUninstallReq describes the plugin uninstall request.
message PluginUninstallReq {
  message UninstallInfo {
    int64 bk_host_id = 1;
    string plugin_name = 2;
  }

  repeated UninstallInfo plugin = 1;
}

// PluginUninstallResp describes the plugin uninstall response.
message PluginUninstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginApplySubConfigReq describes the plugin apply sub-configuration
// request.
message PluginApplySubConfigReq {
  message ApplySubConfigInfo {
    int64 bk_host_id = 1;
    string plugin_name = 2;
    repeated string config_template_name = 3;
    optional google.protobuf.Struct custom_config_context = 4;
  }

  repeated ApplySubConfigInfo plugin = 1;
}

// PluginApplySubConfigResp describes the plugin apply sub-configuration
// response.
message PluginApplySubConfigResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

message PluginListExactConditions {
  repeated string name = 1;
  repeated string group = 2;
  repeated int64 visible_biz_ids = 3;
}

message PluginListFuzzyConditions {
  repeated string name = 1;
  repeated string pkg_name = 2;
}

// PluginListReq describes the plugin list request.
message PluginListReq {
  Page page = 1;
  bool only_count = 2;
  PluginListExactConditions exact_include_conditions = 3;
  PluginListFuzzyConditions fuzzy_include_conditions = 4;
}

// PluginListResp describes the plugin list response.
message PluginListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated Plugin items = 2;
  }
  Data data = 5;
}

// PluginSetMemoReq describes the plugin set memo request.
message PluginSetMemoReq {
  string plugin_name = 1;
  string memo = 2;
}

// PluginSetMemoResp describes the plugin set memo response.
message PluginSetMemoResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;
}

// PluginListPermittedOperationReq describes the plugin list permitted operation
// request.
message PluginListPermittedOperationReq { Page page = 1; }

// PluginListPermittedOperationResp describes the plugin list permitted
// operation response.
message PluginListPermittedOperationResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    message Operation {
      string name = 1;
      repeated string permission = 2;
    }
    repeated Operation operations = 1;
  }
  Data data = 5;
}

// PluginRestartReq describes the plugin restart request.
message PluginRestartReq {
  message RestartInfo {
    int64 bk_host_id = 1;
    string plugin_name = 2;
  }

  repeated RestartInfo plugin = 1;
}

// PluginRestartResp describes the plugin restart response.
message PluginRestartResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginStopReq describes the plugin stop request.
message PluginStopReq {
  message StopInfo {
    int64 bk_host_id = 1;
    string plugin_name = 2;
  }

  repeated StopInfo plugin = 1;
}

// PluginStopResp describes the plugin stop response.
message PluginStopResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

service PluginAPI {
  // InstallPlugin installs a plugin on specified hosts.
  rpc InstallPlugin(PluginInstallReq) returns (PluginInstallResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/install"
      body : "*"
    };
  }

  // UpgradePlugin upgrades a plugin on specified hosts.
  rpc UpgradePlugin(PluginUpgradeReq) returns (PluginUpgradeResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/upgrade"
      body : "*"
    };
  }

  // UninstallPlugin uninstalls a plugin on specified hosts.
  rpc UninstallPlugin(PluginUninstallReq) returns (PluginUninstallResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/uninstall"
      body : "*"
    };
  }

  // ApplyPluginSubConfig applies sub-configuration for a plugin on specified
  // hosts.
  rpc ApplyPluginSubConfig(PluginApplySubConfigReq)
      returns (PluginApplySubConfigResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/apply_subconfig"
      body : "*"
    };
  }

  // ListPlugins lists plugins based on the given conditions.
  rpc ListPlugins(PluginListReq) returns (PluginListResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/list"
      body : "*"
    };
  }

  // SetPluginMemo sets the memo for a plugin.
  rpc SetPluginMemo(PluginSetMemoReq) returns (PluginSetMemoResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/set_memo"
      body : "*"
    };
  }

  // ListPluginPermittedOperation lists the plugin operations that the user has
  // permission to perform.
  rpc ListPluginPermittedOperation(PluginListPermittedOperationReq)
      returns (PluginListPermittedOperationResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/list_permitted_operations"
      body : "*"
    };
  }

  // RestartPlugin restarts the plugin process on specified hosts.
  rpc RestartPlugin(PluginRestartReq) returns (PluginRestartResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/restart"
      body : "*"
    };
  }

  // StopPlugin stops the plugin process on specified hosts.
  rpc StopPlugin(PluginStopReq) returns (PluginStopResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/stop"
      body : "*"
    };
  }
}
