syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/application/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// ProcessListResp describes the process list response.
message ProcessListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated Process items = 2;
  }
  Data data = 5;
}

// GetProcessDistributionByHostIDReq describes the process statistics request.
message GetProcessDistributionByHostIDReq {
  ProcessExactConditions exact_include_conditions = 1;
  ProcessFuzzyConditions fuzzy_include_conditions = 2;
}

// GetProcessDistributionByHostIDResp describes the process statistics response.
message GetProcessDistributionByHostIDResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  map<int64, int64> data = 5;
}

// GetProcessDistributionByPluginNameReq describes the process statistics
// request.
message GetProcessDistributionByPluginNameReq {

  ProcessExactConditions exact_include_conditions = 1;
  ProcessFuzzyConditions fuzzy_include_conditions = 2;
}

// GetProcessDistributionByPluginNameResp describes the process statistics
// response.
message GetProcessDistributionByPluginNameResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  map<string, int64> data = 5;
}

service ProcessAPI {
  // ListProcesses lists the processes.
  rpc ListProcesses(ProcessListReq) returns (ProcessListResp) {
    option (google.api.http) = {
      post : "/api/v3/process/list"
      body : "*"
    };
  }

  // GetProcessDistributionByHostID describes the process statistics request.
  rpc GetProcessDistributionByHostID(GetProcessDistributionByHostIDReq)
      returns (GetProcessDistributionByHostIDResp) {
    option (google.api.http) = {
      post : "/api/v3/process/get_distribution_by_host_id"
      body : "*"
    };
  }

  // GetProcessDistributionByPluginName describes the process statistics
  // request.
  rpc GetProcessDistributionByPluginName(GetProcessDistributionByPluginNameReq)
      returns (GetProcessDistributionByPluginNameResp) {
    option (google.api.http) = {
      post : "/api/v3/process/get_distribution_by_plugin_name"
      body : "*"
    };
  }
}