/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CopyIp: typeof import('./components/copy-ip.vue')['default']
    CopyIpDropdown: typeof import('./components/copy-ip-dropdown.vue')['default']
    FlexRow: typeof import('./components/flex-row.vue')['default']
    InstallTable: typeof import('./components/install-table.vue')['default']
    InstallType: typeof import('./components/install-type.vue')['default']
    PageHeader: typeof import('./components/page-header.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Validate: typeof import('./components/validate.vue')['default']
    ValidateInput: typeof import('./components/validate-input.vue')['default']
  }
}
