/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChooseVersionDialog: typeof import('./components/choose-version-dialog.vue')['default']
    ConfigTemplate: typeof import('./components/config-template.vue')['default']
    CopyIp: typeof import('./components/copy-ip.vue')['default']
    CopyIpDropdown: typeof import('./components/copy-ip-dropdown.vue')['default']
    CreateTag: typeof import('./components/create-tag.vue')['default']
    FlexRow: typeof import('./components/flex-row.vue')['default']
    InstallTable: typeof import('./components/install-table.vue')['default']
    InstallType: typeof import('./components/install-type.vue')['default']
    PageHeader: typeof import('./components/page-header.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/settings.vue')['default']
    SlideDetail: typeof import('./components/slide-detail.vue')['default']
    Upload: typeof import('./components/upload.vue')['default']
    Validate: typeof import('./components/validate.vue')['default']
    ValidateInput: typeof import('./components/validate-input.vue')['default']
  }
}
