/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CopyIp: typeof import('./components/copy-ip.vue')['default']
    CopyProxyIp: typeof import('./components/copy-proxy-ip.vue')['default']
    DefaultTable: typeof import('./components/default-table.vue')['default']
    FlexRow: typeof import('./components/flex-row.vue')['default']
    PageHeader: typeof import('./components/page-header.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
