syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

// Page describes the generaic conditions when paging query.
message Page {
  int32 offset = 1;
  int32 limit = 2;
}

// Business describes the business informations.
message Business {
  optional string tenant_id = 1;
  optional int64 bk_biz_id = 2;
  optional string bk_biz_name = 3;
}

// NetworkArea describes the network area informations.
message NetworkArea {
  optional string tenant_id = 1;
  optional int64 bk_networkarea_id = 2;
  optional string bk_networkarea_name = 3;
  optional string bk_cloud_vendor = 4;
}

// Link describes the network unit link points target.
message Link { int64 accesspoint_id = 1; }

// Links describes the network unit links.
message Links {
  Link cluster = 1;
  Link file = 2;
  Link data = 3;
}

// AccessPoint describes the access point informations.
message AccessPoint {
  optional string tenant_id = 1;
  optional int64 accesspoint_id = 2;
  optional string accesspoint_name = 3;

  message Endpoints {
    repeated string cluster = 1;
    repeated string file = 2;
    repeated string data = 3;
  }
  Endpoints endpoints = 4;
}

// NetworkUnit describes the network unit informations.
message NetworkUnit {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated AccessPoint access_points = 5;
  optional Links links = 6;
}

// NetworkUnitBrief describes the network unit brief informations.
// only contains the access point ids.
message NetworkUnitBrief {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated int64 access_points = 5;
  optional Links links = 6;
}

// HostState describes the host state informations. Usually contains
// agent-related things.
message HostState {
  optional string node_role = 1;
  optional string node_status = 2;
  optional string node_version = 3;
  optional string bk_agent_id = 4;
}

// HostInfo describes the host info informations. Usually contains static
// configs.
message HostInfo {
  optional int64 bk_biz_id = 1;
  optional int64 bk_networkarea_id = 2;
  optional string bk_host_name = 3;
  optional string dept_name = 4;
  optional string bk_host_innerip = 5;
  optional string bk_host_innerip_v6 = 6;
  optional string bk_host_outerip = 7;
  optional string bk_host_outerip_v6 = 8;
  optional string bk_mac = 9;
  optional string bk_os_type = 10;
}

// Host describes the host informations.
message Host {
  optional string tenant_id = 1;
  optional int64 bk_host_id = 2;
  HostInfo info = 3;
  HostState state = 4;
  optional uint64 create_at = 5;
  optional uint64 updated_at = 6;
}