syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

// Page describes the generaic conditions when paging query.
message Page {
  int32 offset = 1;
  int32 limit = 2;
}

// Business describes the business informations.
message Business {
  optional string tenant_id = 1;
  optional int64 bk_biz_id = 2;
  optional string bk_biz_name = 3;
}

// NetworkArea describes the network area informations.
message NetworkArea {
  optional string tenant_id = 1;
  optional int64 bk_networkarea_id = 2;
  optional string bk_networkarea_name = 3;
  optional string cloud_vendor = 4;
}

// Link describes the network unit link points target.
message Link {
  int64 bk_networkarea_id = 1;
  int64 bk_networkunit_id = 2;
  int64 accesspoint_id = 3;
}

// Links describes the network unit links.
message Links {
  Link cluster = 1;
  Link file = 2;
  Link data = 3;
}

// Endpoints describes the links real address.
message Endpoints {
  repeated string cluster = 1;
  repeated string file = 2;
  repeated string data = 3;
}

// AccessPoint describes the access point informations.
message AccessPoint {
  optional string tenant_id = 1;
  optional int64 accesspoint_id = 2;
  optional string accesspoint_name = 3;
  optional int64 bk_networkarea_id = 4;
  Endpoints endpoints = 5;
}

// NetworkUnit describes the network unit informations.
message NetworkUnit {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated AccessPoint accesspoints = 5;
  optional Links links = 6;
  optional bool is_direct = 7;
  Endpoints direct_endpoints = 8;
}

// NetworkUnitBrief describes the network unit brief informations.
// only contains the access point ids.
message NetworkUnitBrief {
  optional string tenant_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string bk_networkunit_name = 3;
  optional int64 bk_networkarea_id = 4;
  repeated int64 accesspoints = 5;
  optional Links links = 6;
  optional bool is_direct = 7;
  Endpoints direct_endpoints = 8;
}

// HostState describes the host state informations. Usually contains
// agent-related things.
message HostState {
  optional string node_role = 1;
  optional string node_status = 2;
  optional string node_version = 3;
  optional string bk_agent_id = 4;
  optional int64 node_generation = 5;
  repeated string proxy_tags = 6;
}

// HostInfo describes the host info informations. Usually contains static
// configs.
message HostInfo {
  optional int64 bk_biz_id = 1;
  optional int64 bk_networkarea_id = 2;
  optional int64 bk_networkunit_id = 3;
  optional string bk_host_name = 4;
  optional string dept_name = 5;
  optional string bk_host_innerip = 6;
  optional string bk_host_innerip_v6 = 7;
  optional string bk_host_outerip = 8;
  optional string bk_host_outerip_v6 = 9;
  optional string bk_mac = 10;
  optional string os_type = 11;
  optional string cpu_arch = 12;
  optional string login_ip = 13;
  optional int64 login_port = 14;
  optional string login_user = 15;
  optional string export_ip = 16;
  optional string advertise_ip = 17;
}

// Host describes the host informations.
message Host {
  optional string tenant_id = 1;
  optional int64 bk_host_id = 2;
  HostInfo info = 3;
  HostState state = 4;
  optional uint64 create_at = 5;
  optional uint64 updated_at = 6;
}

// TopoEvent describes the topo event.
message TopoEvent {
  optional string tenant_id = 1;
  optional string type = 2;
  optional int64 bk_networkarea_id = 3;
  optional string bk_networkarea_name = 4;
  optional int64 bk_networkunit_id = 5;
  optional string bk_networkunit_name = 6;
  optional int64 accesspoint_id = 7;
  optional string accesspoint_name = 8;
  optional int64 operate_time = 9;
  optional string operator = 10;
}

// TimeRange describes the time range.
message TimeRange {
  int64 start_timestamp_sec = 1;
  int64 end_timestamp_sec = 2;
}

// Release describes the release.
message Release {
  optional int64 generation = 1;
  optional string release_type = 2;
  optional string os_type = 3;
  optional string cpu_arch = 4;
  optional string version = 5;
  optional string file_name = 6;
  repeated string labels = 7;
  optional bool enabled = 8;
  optional bool as_default = 9;
  optional string md5 = 10;
  optional uint64 updated_at = 11;
  optional string operator = 12;
}

// Platform describes the platform informations.
message Platform {
  string os_type = 1;
  string cpu_arch = 2;
}

// ConfigPolicyScope describes the config policy scope.
message ConfigPolicyScope {
  optional int64 bk_networkarea_id = 1;
  optional int64 bk_networkunit_id = 2;
  optional string os_type = 3;
  optional string cpu_arch = 4;
}

// ConfigPolocy decribes the config policy.
message ConfigPolicy {
  optional string tenant_id = 1;
  optional int64 configpolicy_id = 2;
  optional string configpolicy_name = 3;
  optional string node_role = 4;
  repeated int64 biz_id = 5;
  optional string remark = 6;
  repeated ConfigPolicyScope scopes = 7;
  map<string, string> configs_string = 8;
  map<string, int64> configs_int = 9;
  map<string, bool> configs_bool = 10;
  optional bool enabled = 11;
  optional int64 updated_time = 12;
  optional string operator = 13;
  optional int64 version = 14;
}

message TargetVersion {
  string version = 1;
  string cpu_arch = 2;
  string os_type = 3;
}

message Error {
  string system = 1;
  string message = 2;
  message Details {
    string code = 1;
    string message = 2;
  }
  repeated Details details = 3;
}