syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// ConfigPolicyExactConditions describes config policy exact conditions.
message ConfigPolicyExactConditions {
  repeated int64 configpolicy_id = 1;
  repeated int64 biz_id = 2;
  repeated string node_role = 3;
  repeated bool enabled = 4;
}

// ConfigPolicyFuzzyConditions describes config policy fuzzy conditions.
message ConfigPolicyFuzzyConditions { repeated string configpolicy_name = 1; }

// ConfigPolicyListReq describes HTTP request body when list config policy.
message ConfigPolicyListReq {
  Page page = 1;
  bool only_count = 2;

  ConfigPolicyExactConditions exact_include_conditions = 3;
  ConfigPolicyFuzzyConditions fuzzy_include_conditions = 4;
}

// ConfigPolicyListResp describes HTTP response body when list config policy.
message ConfigPolicyListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {
    int64 total = 1;
    repeated ConfigPolicy items = 2;
  }
  Data data = 4;
}

// ConfigPolicyGetReq describes HTTP request body when get config policy.
message ConfigPolicyGetReq { int64 configpolicy_id = 1; }

// ConfigPolicyGetResp describes HTTP response body when get config policy.
message ConfigPolicyGetResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  ConfigPolicy data = 4;
}

// ConfigPolicyCreateReq describes HTTP request body when create config policy.
message ConfigPolicyCreateReq {
  string configpolicy_name = 1;
  string node_role = 2;
  repeated int64 biz_id = 3;
  string remark = 4;
  repeated ConfigPolicyScope scopes = 5;
  map<string, string> configs_string = 6;
  map<string, int64> configs_int = 7;
  map<string, bool> configs_bool = 8;
  string operator = 9;
}

// ConfigPolicyCreateResp describes HTTP response body when create config
// policy.
message ConfigPolicyCreateResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data { optional int64 configpolicy_id = 1; }
  Data data = 4;
}

// ConfigPolicyUpdateReq describes HTTP request body when update config policy.
message ConfigPolicyUpdateReq {
  int64 configpolicy_id = 1;
  string configpolicy_name = 2;
  string node_role = 3;
  repeated int64 biz_id = 4;
  string remark = 5;
  repeated ConfigPolicyScope scopes = 6;
  map<string, string> configs_string = 7;
  map<string, int64> configs_int = 8;
  map<string, bool> configs_bool = 9;
  bool enabled = 10;
  string operator = 11;
}

// ConfigPolicyUpdateResp describes HTTP response body when update config
// policy.
message ConfigPolicyUpdateResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data { optional int64 configpolicy_id = 1; }
  Data data = 4;
}

// ConfigPolicyEnableReq describes HTTP request body when enable config policy.
message ConfigPolicyEnableReq { repeated int64 configpolicy_id = 1; }

// ConfigPolicyEnableResp describes HTTP response body when enable config
// policy.
message ConfigPolicyEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// ConfigPolicyDisableReq describes HTTP request body when disable config
// policy.
message ConfigPolicyDisableReq { repeated int64 configpolicy_id = 1; }

// ConfigPolicyDisableResp describes HTTP response body when disable config
// policy.
message ConfigPolicyDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}

// ConfigPolicyDeleteReq describes HTTP request body when delete config policy.
message ConfigPolicyDeleteReq { repeated int64 configpolicy_id = 1; }

// ConfigPolicyDeleteResp describes HTTP response body when delete config
// policy.
message ConfigPolicyDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;

  message Data {}
  Data data = 4;
}