syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// PackageReleaseExactConditions describes release exact conditions.
message PackageReleaseExactConditions {
  repeated Platform platform = 1;
  repeated string version = 2;
  repeated bool as_default = 3;
  repeated bool enabled = 4;
}

// PackageReleaseListReq describes the HTTP request body when list package
// release.
message PackageReleaseListReq {
  Page page = 1;
  string release_type = 2;
  int64 generation = 3;
  bool only_count = 4;

  PackageReleaseExactConditions exact_include_conditions = 5;
}

// PackageReleaseListResp describes the HTTP response body when list package
// release.
message PackageReleaseListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated Release items = 2;
  }
  Data data = 5;
}

// PackageReleaseAgentListReq describes the HTTP request body when list package
// release.
message PackageReleaseAgentListReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 5;
}

// PackageReleaseAgentListResp describes the HTTP response body when list
// package release.
message PackageReleaseAgentListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated ReleaseAgent items = 2;
  }
  Data data = 5;
}

// PackageReleaseProxyListReq describes the HTTP request body when list package
// release.
message PackageReleaseProxyListReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 5;
}

// PackageReleaseProxyListResp describes the HTTP response body when list
// package release.
message PackageReleaseProxyListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated ReleaseProxy items = 2;
  }
  Data data = 5;
}

// PackageReleaseDistinctReq describes the HTTP request body when distinct
// release.
message PackageReleaseDistinctReq {
  string release_type = 1;
  int64 generation = 2;
  PackageReleaseExactConditions exact_include_conditions = 3;

  message DistinctField {
    bool os_type = 1;
    bool cpu_arch = 2;
  }

  DistinctField distinctField = 4;
}

// PackageReleaseDistinctResp describes the HTTP response body when distinct
// release.
message PackageReleaseDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    repeated string os_type = 1;
    repeated string cpu_arch = 2;
  }
  Data data = 5;
}

// PackageReleaseSetLabelsReq describes the HTTP request body when set labels.
message PackageReleaseSetLabelsReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
  repeated string labels = 5;
}

// PackageReleaseSetLabelsResp describes the HTTP response body when set
// labels.
message PackageReleaseSetLabelsResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseSetLabelsManyReq describes the HTTP request body when set many
// labels.
message PackageReleaseSetLabelsManyReq {
  message Identity {
    int64 generation = 1;
    Platform platform = 2;
    string version = 3;
  }
  string release_type = 1;
  repeated Identity identify = 2;
  repeated string labels = 3;
}

// PackageReleaseSetLabelsManyResp describes the HTTP response body when set
// many labels.
message PackageReleaseSetLabelsManyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseEnableReq describes the HTTP request body when enable package
// release.
message PackageReleaseEnableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseEnableResp describes the HTTP response body when enable package
// release.
message PackageReleaseEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseDisableReq describes the HTTP request body when disable package
// release.
message PackageReleaseDisableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseDisableResp describes the HTTP response body when disable
// package release.
message PackageReleaseDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseSetAsDefaultReq describes the HTTP request body when set
// default package release.
message PackageReleaseSetAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseSetAsDefaultResp describes the HTTP response body when set
// default package release.
message PackageReleaseSetAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseCancelAsDefaultReq describes the HTTP request body when cancel
// default package release.
message PackageReleaseCancelAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseCancelAsDefaultResp describes the HTTP response body when
// cancel default package release.
message PackageReleaseCancelAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleaseDeleteReq describes the HTTP request body when delete release.
message PackageReleaseDeleteReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseDeleteResp describes the HTTP response body when delete
// release.
message PackageReleaseDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageEventExactConditions describes the conditions when list event.
message PackageEventExactConditions {
  repeated int64 generation = 1;
  repeated string os_type = 2;
  repeated string cpu_arch = 3;
  repeated string release_type = 4;
  repeated string operator = 5;
  repeated string event_type = 6;
  repeated string version = 7;
}

// PackageEventFuzzyConditions describes the conditions when list event
message PackageEventFuzzyConditions {}

// PackageEventListReq describes the HTTP request body when list event in
// Package service.
message PackageEventListReq {
  Page page = 1;
  bool only_count = 2;

  PackageEventExactConditions exact_include_conditions = 3;
  PackageEventFuzzyConditions fuzzy_include_conditions = 4;
  TimeRange operate_time_range = 5;
}

// PackageEventListResp describes the HTTP response body when list event in
// Package service.
message PackageEventListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated PackageEvent items = 2;
  }
  Data data = 5;
}

// PackageEventDistinctReq describes the HTTP request body when distinct
// packageevent in package service.
message PackageEventDistinctReq {
  PackageEventExactConditions exact_include_conditions = 1;
  PackageEventFuzzyConditions fuzzy_include_conditions = 2;
  TimeRange operate_time_range = 3;
}

// PackageEventDistinctResp describes the HTTP response body when distinct
// packageevent in package service.
message PackageEventDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    repeated string release_type = 1;
    repeated string event_type = 2;
    repeated string os_type = 3;
    repeated string cpu_arch = 4;
    repeated string version = 5;
    repeated string operator = 6;
  }
  Data data = 5;
}

// ReleasePlugin describes the package release plugin information.
message ReleasePlugin { Release release = 1; }

// PackageReleasePluginListReq describes the HTTP request body when list package
// release.
message PackageReleasePluginListReq {
  Page page = 1;
  int64 name = 2;
  int64 generation = 3;
  bool only_count = 4;

  PackageReleaseExactConditions exact_include_conditions = 5;
}

// PackageReleasePluginListResp describes the HTTP response body when list
// package release.
message PackageReleasePluginListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    int64 total = 1;
    repeated ReleasePlugin items = 2;
  }
  Data data = 5;
}

// PackageReleasePluginEnableReq describes the HTTP request body when enable
// package release.
message PackageReleasePluginEnableReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginEnableResp describes the HTTP response body when enable
// package release.
message PackageReleasePluginEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginDisableReq describes the HTTP request body when disable
// package release.
message PackageReleasePluginDisableReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginDisableResp describes the HTTP response body when disable
// package release.
message PackageReleasePluginDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginSetAsDefaultReq describes the HTTP request body when set
// default package release.
message PackageReleasePluginSetAsDefaultReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginSetAsDefaultResp describes the HTTP response body when
// set default package release.
message PackageReleasePluginSetAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginCancelAsDefaultReq describes the HTTP request body when
// cancel default package release.
message PackageReleasePluginCancelAsDefaultReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginCancelAsDefaultResp describes the HTTP response body when
// cancel default package release.
message PackageReleasePluginCancelAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginDeleteReq describes the HTTP request body when delete
// release.
message PackageReleasePluginDeleteReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginDeleteResp describes the HTTP response body when delete
// release.
message PackageReleasePluginDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {}
  Data data = 5;
}

service Package {
  // ListRelease lists releases.
  rpc ListRelease(PackageReleaseListReq) returns (PackageReleaseListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/list"
      body : "*"
    };
  }

  // PackageReleaseDistinct distincts releases.
  rpc DistinctRelease(PackageReleaseDistinctReq)
      returns (PackageReleaseDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/distinct"
      body : "*"
    };
  }

  // SetReleaseLabels sets release labels.
  rpc SetReleaseLabels(PackageReleaseSetLabelsReq)
      returns (PackageReleaseSetLabelsResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_labels"
      body : "*"
    };
  }

  // SetReleaseLabeslMany sets many release labels.
  rpc SetReleaseLabelsMany(PackageReleaseSetLabelsManyReq)
      returns (PackageReleaseSetLabelsManyResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_labels_many"
      body : "*"
    };
  }

  // EnableRelease enables release.
  rpc EnableRelease(PackageReleaseEnableReq)
      returns (PackageReleaseEnableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/enable"
      body : "*"
    };
  }

  // DisableRelease disables release.
  rpc DisableRelease(PackageReleaseDisableReq)
      returns (PackageReleaseDisableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/disable"
      body : "*"
    };
  }

  // SetAsDefaultRelease sets release as default.
  rpc SetAsDefaultRelease(PackageReleaseSetAsDefaultReq)
      returns (PackageReleaseSetAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_as_default"
      body : "*"
    };
  }

  // CancelAsDefaultRelease cancels release as default.
  rpc CancelAsDefaultRelease(PackageReleaseCancelAsDefaultReq)
      returns (PackageReleaseCancelAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/cancel_as_default"
      body : "*"
    };
  }

  // DeleteRelease deletes release.
  rpc DeleteRelease(PackageReleaseDeleteReq)
      returns (PackageReleaseDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/delete"
      body : "*"
    };
  }

  // PackageEventList provides package event listing.
  rpc PackageEventList(PackageEventListReq) returns (PackageEventListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/event/list"
      body : "*"
    };
  }

  // PackageEventDistinct provides package event distincting.
  rpc PackageEventDistinct(PackageEventDistinctReq)
      returns (PackageEventDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/package/event/distinct"
      body : "*"
    };
  }

  // ListReleasePlugin lists releases.
  rpc ListReleasePlugin(PackageReleasePluginListReq)
      returns (PackageReleasePluginListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release_plugin/list"
      body : "*"
    };
  }

  // EnableReleasePlugin enables release.
  rpc EnableReleasePlugin(PackageReleasePluginEnableReq)
      returns (PackageReleasePluginEnableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/enable"
      body : "*"
    };
  }

  // DisableReleasePlugin disables release.
  rpc DisableReleasePlugin(PackageReleasePluginDisableReq)
      returns (PackageReleasePluginDisableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/disable"
      body : "*"
    };
  }

  // SetAsDefaultReleasePlugin sets release as default.
  rpc SetAsDefaultReleasePlugin(PackageReleasePluginSetAsDefaultReq)
      returns (PackageReleasePluginSetAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/set_as_default"
      body : "*"
    };
  }

  // CancelAsDefaultReleasePlugin cancels release as default.
  rpc CancelAsDefaultReleasePlugin(PackageReleasePluginCancelAsDefaultReq)
      returns (PackageReleasePluginCancelAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/cancel_as_default"
      body : "*"
    };
  }

  // DeleteReleasePlugin deletes release.
  rpc DeleteReleasePlugin(PackageReleasePluginDeleteReq)
      returns (PackageReleaseDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/delete"
      body : "*"
    };
  }

  // ListReleaseAgent lists releases.
  rpc ListReleaseAgent(PackageReleaseAgentListReq)
      returns (PackageReleaseAgentListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release_agent/list"
      body : "*"
    };
  }

  // ListReleaseProxy lists releases.
  rpc ListReleaseProxy(PackageReleaseProxyListReq)
      returns (PackageReleaseProxyListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release_proxy/list"
      body : "*"
    };
  }
}