syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

// PackageReleaseExactConditions describes release exact conditions.
message PackageReleaseExactConditions {
  repeated Platform platform = 1;
  repeated string version = 2;
  repeated bool as_default = 3;
  repeated bool enabled = 4;
  repeated string name = 5;
  repeated string file_name = 6;
}

// PackageReleaseDistinctField describes the release distinct field.
message PackageReleaseDistinctField {
  bool os_type = 1;
  bool cpu_arch = 2;
}

// PackageReleaseDistinctData describes the release distinct data.
message PackageReleaseDistinctData {
  repeated string os_type = 1;
  repeated string cpu_arch = 2;
}

// PackageReleaseAgentListReq describes the HTTP request body when list agent
// release.
message PackageReleaseAgentListReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 4;
}

// PackageReleaseAgentListResp describes the HTTP response body when list agent
// release.
message PackageReleaseAgentListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleaseAgent items = 2;
  }
  Data data = 5;
}

// PackageReleaseAgentListBriefReq describes the HTTP request body when list
// agent release brief.
message PackageReleaseAgentListBriefReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 4;
}

// PackageReleaseAgentListBriefResp describes the HTTP response body when list
// agent release brief.
message PackageReleaseAgentListBriefResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleaseAgentBrief items = 2;
  }
  Data data = 5;
}

// PackageReleaseAgentDistinctReq describes the HTTP request body when distinct
// agent release.
message PackageReleaseAgentDistinctReq {
  int64 generation = 1;
  PackageReleaseExactConditions exact_include_conditions = 2;
  PackageReleaseDistinctField distinct_field = 3;
}

// PackageReleaseAgentDistinctResp describes the HTTP response body when
// distinct agent release.
message PackageReleaseAgentDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;
  PackageReleaseDistinctData data = 5;
}

// PackageReleaseAgentSetLabelsManyReq describes the HTTP request body when set
// many labels to agent release.
message PackageReleaseAgentSetLabelsManyReq {
  int64 generation = 1;
  PackageReleaseExactConditions exact_include_conditions = 2;
  repeated string labels = 3;
}

// PackageReleaseAgentSetLabelsManyResp describes the HTTP response body when
// set many labels to agent release.
message PackageReleaseAgentSetLabelsManyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseAgentEnableReq describes the HTTP request body when enable
// agent release.
message PackageReleaseAgentEnableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseAgentEnableResp describes the HTTP response body when enable
// agent release.
message PackageReleaseAgentEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseAgentDisableReq describes the HTTP request body when disable
// agent release.
message PackageReleaseAgentDisableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseAgentDisableResp describes the HTTP response body when disable
// agent release.
message PackageReleaseAgentDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseAgentSetAsDefaultReq describes the HTTP request body when set
// default agent release.
message PackageReleaseAgentSetAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseAgentSetAsDefaultResp describes the HTTP response body when set
// default agent release.
message PackageReleaseAgentSetAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseAgentCancelAsDefaultReq describes the HTTP request body when
// cancel default agent release.
message PackageReleaseAgentCancelAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseAgentCancelAsDefaultResp describes the HTTP response body when
// cancel default agent release.
message PackageReleaseAgentCancelAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseAgentDeleteReq describes the HTTP request body when delete
// agent release.
message PackageReleaseAgentDeleteReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseAgentDeleteResp describes the HTTP response body when delete
// agent release.
message PackageReleaseAgentDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseProxyListReq describes the HTTP request body when list proxy
// release.
message PackageReleaseProxyListReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 4;
}

// PackageReleaseProxyListResp describes the HTTP response body when list proxy
// release.
message PackageReleaseProxyListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleaseProxy items = 2;
  }
  Data data = 5;
}

// PackageReleaseProxyListBriefReq describes the HTTP request body when list
// proxy release brief.
message PackageReleaseProxyListBriefReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 4;
}

// PackageReleaseProxyListBriefResp describes the HTTP response body when list
// proxy release brief.
message PackageReleaseProxyListBriefResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleaseProxyBrief items = 2;
  }
  Data data = 5;
}

// PackageReleaseProxyDistinctReq describes the HTTP request body when distinct
// proxy release.
message PackageReleaseProxyDistinctReq {
  int64 generation = 1;
  PackageReleaseExactConditions exact_include_conditions = 2;
  PackageReleaseDistinctField distinct_field = 3;
}

// PackageReleaseProxyDistinctResp describes the HTTP response body when
// distinct proxy release.
message PackageReleaseProxyDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;
  PackageReleaseDistinctData data = 5;
}

// PackageReleaseProxySetLabelsManyReq describes the HTTP request body when set
// many labels to proxy release.
message PackageReleaseProxySetLabelsManyReq {
  int64 generation = 1;
  PackageReleaseExactConditions exact_include_conditions = 2;
  repeated string labels = 3;
}

// PackageReleaseProxySetLabelsManyResp describes the HTTP response body when
// set many labels to proxy release.
message PackageReleaseProxySetLabelsManyResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseProxyEnableReq describes the HTTP request body when enable
// proxy release.
message PackageReleaseProxyEnableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseProxyEnableResp describes the HTTP response body when enable
// proxy release.
message PackageReleaseProxyEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseProxyDisableReq describes the HTTP request body when disable
// proxy release.
message PackageReleaseProxyDisableReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseProxyDisableResp describes the HTTP response body when disable
// proxy release.
message PackageReleaseProxyDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseProxySetAsDefaultReq describes the HTTP request body when set
// default proxy release.
message PackageReleaseProxySetAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseProxySetAsDefaultResp describes the HTTP response body when set
// default proxy release.
message PackageReleaseProxySetAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseProxyCancelAsDefaultReq describes the HTTP request body when
// cancel default proxy release.
message PackageReleaseProxyCancelAsDefaultReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseProxyCancelAsDefaultResp describes the HTTP response body when
// cancel default proxy release.
message PackageReleaseProxyCancelAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseProxyDeleteReq describes the HTTP request body when delete
// proxy release.
message PackageReleaseProxyDeleteReq {
  int64 generation = 1;
  string release_type = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleaseProxyDeleteResp describes the HTTP response body when delete
// proxy release.
message PackageReleaseProxyDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginListBriefReq describes the HTTP request body when list
// plugin release brief.
message PackageReleasePluginListBriefReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 4;
}

// PackageReleasePluginListBriefResp describes the HTTP response body when list
// plugin release brief.
message PackageReleasePluginListBriefResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleasePluginBrief items = 2;
  }
  Data data = 5;
}

// PackageReleasePluginListReq describes the HTTP request body when list plugin
// release.
message PackageReleasePluginListReq {
  Page page = 1;
  int64 generation = 2;
  bool only_count = 3;

  PackageReleaseExactConditions exact_include_conditions = 4;
}

// PackageReleasePluginListResp describes the HTTP response body when list
// plugin release.
message PackageReleasePluginListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleasePlugin items = 2;
  }
  Data data = 5;
}

// PackageReleasePluginEnableReq describes the HTTP request body when enable
// plugin release.
message PackageReleasePluginEnableReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginEnableResp describes the HTTP response body when enable
// plugin release.
message PackageReleasePluginEnableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginDisableReq describes the HTTP request body when disable
// plugin release.
message PackageReleasePluginDisableReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginDisableResp describes the HTTP response body when disable
// plugin release.
message PackageReleasePluginDisableResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginSetAsDefaultReq describes the HTTP request body when set
// default plugin release.
message PackageReleasePluginSetAsDefaultReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginSetAsDefaultResp describes the HTTP response body when
// set default plugin release.
message PackageReleasePluginSetAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginCancelAsDefaultReq describes the HTTP request body when
// cancel default plugin release.
message PackageReleasePluginCancelAsDefaultReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginCancelAsDefaultResp describes the HTTP response body when
// cancel default plugin release.
message PackageReleasePluginCancelAsDefaultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginDeleteReq describes the HTTP request body when delete
// plugin release.
message PackageReleasePluginDeleteReq {
  int64 generation = 1;
  string name = 2;
  Platform platform = 3;
  string version = 4;
}

// PackageReleasePluginDeleteResp describes the HTTP response body when delete
// plugin release.
message PackageReleasePluginDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginGetConfigVariablesReq describes the HTTP request body
// when get config variables of plugin release.
message PackageReleasePluginGetConfigVariablesReq {
  int64 generation = 1;
  string name = 2;
  repeated Platform platforms = 3;
  string version = 4;
}

// ConfigVariables describes the config variables of plugin release.
message ConfigVariables {
  message Property {
    string title = 1;
    string type = 2;
    bool required = 3;
    google.protobuf.Value default = 4;
    string description = 5;
    string description_en = 6;
    map<string, Property> properties = 7;
  }

  string name = 1;
  string file_path = 2;
  string source_path = 3;
  bool is_main_config = 4;
  string source_content = 5;
  map<string, Property> variables = 6;
}

// PackageReleasePluginGetConfigVariablesResp describes the HTTP response body
// when get config variables of plugin release.
message PackageReleasePluginGetConfigVariablesResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message ConfigVariablesList { repeated ConfigVariables items = 1; }
  message Data { map<string, ConfigVariablesList> config_variables = 1; }
  Data data = 5;
}

// PackageReleaseCertListReq describes the HTTP request body when list cert
// release.
message PackageReleaseCertListReq { int64 generation = 1; }

// PackageReleaseCertListResp describes the HTTP response body when list cert
// release.
message PackageReleaseCertListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleaseCert items = 2;
  }
  Data data = 5;
}

// PackageReleaseCertDeleteReq describes the HTTP request body when delete
// cert release.
message PackageReleaseCertDeleteReq { int64 generation = 1; }

// PackageReleaseCertDeleteResp describes the HTTP response body when delete
// cert release.
message PackageReleaseCertDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleaseBinToolListReq describes the HTTP request body when list
// bintool release.
message PackageReleaseBinToolListReq { int64 generation = 1; }

// PackageReleaseBinToolListResp describes the HTTP response body when list
// bintool release.
message PackageReleaseBinToolListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleaseBinTool items = 2;
  }
  Data data = 5;
}

// PackageReleaseBinToolDeleteReq describes the HTTP request body when delete
// bintool release.
message PackageReleaseBinToolDeleteReq { int64 generation = 1; }

// PackageReleaseBinToolDeleteResp describes the HTTP response body when delete
// bintool release.
message PackageReleaseBinToolDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageReleasePluginBinToolListReq describes the HTTP request body when list
// plugin-bintool release.
message PackageReleasePluginBinToolListReq { int64 generation = 1; }

// PackageReleasePluginBinToolListResp describes the HTTP response body when
// list plugin-bintool release.
message PackageReleasePluginBinToolListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated ReleasePluginBinTool items = 2;
  }
  Data data = 5;
}

// PackageReleasePluginBinToolDeleteReq describes the HTTP request body when
// delete plugin-bintool release.
message PackageReleasePluginBinToolDeleteReq {
  int64 generation = 1;
  string name = 2;
}

// PackageReleasePluginBinToolDeleteResp describes the HTTP response body when
// delete plugin-bintool release.
message PackageReleasePluginBinToolDeleteResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {}
  Data data = 5;
}

// PackageEventExactConditions describes the conditions when list event.
message PackageEventExactConditions {
  repeated int64 generation = 1;
  repeated string os_type = 2;
  repeated string cpu_arch = 3;
  repeated string release_type = 4;
  repeated string operator = 5;
  repeated string event_type = 6;
  repeated string version = 7;
}

// PackageEventFuzzyConditions describes the conditions when list event
message PackageEventFuzzyConditions {}

// PackageEventListReq describes the HTTP request body when list event in
// Package service.
message PackageEventListReq {
  Page page = 1;
  bool only_count = 2;

  PackageEventExactConditions exact_include_conditions = 3;
  PackageEventFuzzyConditions fuzzy_include_conditions = 4;
  TimeRange operate_time_range = 5;
}

// PackageEventListResp describes the HTTP response body when list event in
// Package service.
message PackageEventListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    int64 total = 1;
    repeated PackageEvent items = 2;
  }
  Data data = 5;
}

// PackageEventDistinctReq describes the HTTP request body when distinct
// package event in package service.
message PackageEventDistinctReq {
  PackageEventExactConditions exact_include_conditions = 1;
  PackageEventFuzzyConditions fuzzy_include_conditions = 2;
  TimeRange operate_time_range = 3;
}

// PackageEventDistinctResp describes the HTTP response body when distinct
// package event in package service.
message PackageEventDistinctResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    repeated string release_type = 1;
    repeated string event_type = 2;
    repeated string os_type = 3;
    repeated string cpu_arch = 4;
    repeated string version = 5;
    repeated string operator = 6;
  }
  Data data = 5;
}

// PackageImportReq describes the HTTP request body when import package in
// package service.
message PackageImportReq {
    string file_name = 1;
    string download_url = 2;
    string md5 = 3;
}

// PackageImportResp describes the HTTP response body when import package in
// package service.
message PackageImportResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    string plugin_name = 1;
  }

  Data data = 5;
}

// Package defines the package service.
service Package {
  // ListReleaseAgent lists agent releases.
  rpc ListReleaseAgent(PackageReleaseAgentListReq)
      returns (PackageReleaseAgentListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/list"
      body : "*"
    };
  }

  // ListReleaseAgentBrief lists agent release briefs.
  rpc ListReleaseAgentBrief(PackageReleaseAgentListBriefReq)
      returns (PackageReleaseAgentListBriefResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/list/brief"
      body : "*"
    };
  }

  // DistinctReleaseAgent distincts agent releases.
  rpc DistinctReleaseAgent(PackageReleaseAgentDistinctReq)
      returns (PackageReleaseAgentDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/distinct"
      body : "*"
    };
  }

  // SetReleaseAgentLabelsMany sets many agent releases labels.
  rpc SetReleaseAgentLabelsMany(PackageReleaseAgentSetLabelsManyReq)
      returns (PackageReleaseAgentSetLabelsManyResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/set_labels_many"
      body : "*"
    };
  }

  // EnableReleaseAgent enables agent release.
  rpc EnableReleaseAgent(PackageReleaseAgentEnableReq)
      returns (PackageReleaseAgentEnableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/enable"
      body : "*"
    };
  }

  // DisableReleaseAgent disables agent release.
  rpc DisableReleaseAgent(PackageReleaseAgentDisableReq)
      returns (PackageReleaseAgentDisableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/disable"
      body : "*"
    };
  }

  // SetAsDefaultReleaseAgent sets agent release as default.
  rpc SetAsDefaultReleaseAgent(PackageReleaseAgentSetAsDefaultReq)
      returns (PackageReleaseAgentSetAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/set_as_default"
      body : "*"
    };
  }

  // CancelAsDefaultReleaseAgent cancels agent release as default.
  rpc CancelAsDefaultReleaseAgent(PackageReleaseAgentCancelAsDefaultReq)
      returns (PackageReleaseAgentCancelAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/cancel_as_default"
      body : "*"
    };
  }

  // DeleteReleaseAgent deletes agent release.
  rpc DeleteReleaseAgent(PackageReleaseAgentDeleteReq)
      returns (PackageReleaseAgentDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/agent/delete"
      body : "*"
    };
  }

  // ListReleaseProxy lists proxy releases.
  rpc ListReleaseProxy(PackageReleaseProxyListReq)
      returns (PackageReleaseProxyListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/list"
      body : "*"
    };
  }

  // ListReleaseProxyBrief lists proxy release briefs.
  rpc ListReleaseProxyBrief(PackageReleaseProxyListBriefReq)
      returns (PackageReleaseProxyListBriefResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/list/brief"
      body : "*"
    };
  }

  // DistinctReleaseProxy distincts proxy releases.
  rpc DistinctReleaseProxy(PackageReleaseProxyDistinctReq)
      returns (PackageReleaseProxyDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/distinct"
      body : "*"
    };
  }

  // SetReleaseProxyLabelsMany sets many proxy releases labels.
  rpc SetReleaseProxyLabelsMany(PackageReleaseProxySetLabelsManyReq)
      returns (PackageReleaseProxySetLabelsManyResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/set_labels_many"
      body : "*"
    };
  }

  // EnableReleaseProxy enables proxy release.
  rpc EnableReleaseProxy(PackageReleaseProxyEnableReq)
      returns (PackageReleaseProxyEnableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/enable"
      body : "*"
    };
  }

  // DisableReleaseProxy disables proxy release.
  rpc DisableReleaseProxy(PackageReleaseProxyDisableReq)
      returns (PackageReleaseProxyDisableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/disable"
      body : "*"
    };
  }

  // SetAsDefaultReleaseProxy sets proxy release as default.
  rpc SetAsDefaultReleaseProxy(PackageReleaseProxySetAsDefaultReq)
      returns (PackageReleaseProxySetAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/set_as_default"
      body : "*"
    };
  }

  // CancelAsDefaultReleaseProxy cancels proxy release as default.
  rpc CancelAsDefaultReleaseProxy(PackageReleaseProxyCancelAsDefaultReq)
      returns (PackageReleaseProxyCancelAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/cancel_as_default"
      body : "*"
    };
  }

  // DeleteReleaseProxy deletes proxy release.
  rpc DeleteReleaseProxy(PackageReleaseProxyDeleteReq)
      returns (PackageReleaseProxyDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/proxy/delete"
      body : "*"
    };
  }

  // ListReleasePlugin lists plugin releases.
  rpc ListReleasePlugin(PackageReleasePluginListReq)
      returns (PackageReleasePluginListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/list"
      body : "*"
    };
  }

  // ListReleasePluginBrief lists plugin release briefs.
  rpc ListReleasePluginBrief(PackageReleasePluginListBriefReq)
      returns (PackageReleasePluginListBriefResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/list/brief"
      body : "*"
    };
  }

  // EnableReleasePlugin enables plugin release.
  rpc EnableReleasePlugin(PackageReleasePluginEnableReq)
      returns (PackageReleasePluginEnableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/enable"
      body : "*"
    };
  }

  // DisableReleasePlugin disables plugin release.
  rpc DisableReleasePlugin(PackageReleasePluginDisableReq)
      returns (PackageReleasePluginDisableResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/disable"
      body : "*"
    };
  }

  // SetAsDefaultReleasePlugin sets plugin release as default.
  rpc SetAsDefaultReleasePlugin(PackageReleasePluginSetAsDefaultReq)
      returns (PackageReleasePluginSetAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/set_as_default"
      body : "*"
    };
  }

  // CancelAsDefaultReleasePlugin cancels plugin release as default.
  rpc CancelAsDefaultReleasePlugin(PackageReleasePluginCancelAsDefaultReq)
      returns (PackageReleasePluginCancelAsDefaultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/cancel_as_default"
      body : "*"
    };
  }

  // DeleteReleasePlugin deletes plugin release.
  rpc DeleteReleasePlugin(PackageReleasePluginDeleteReq)
      returns (PackageReleasePluginDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/delete"
      body : "*"
    };
  }

  // GetConfigVariablesReleasePlugin gets config variables of plugin release.
  rpc GetConfigVariablesReleasePlugin(PackageReleasePluginGetConfigVariablesReq)
      returns (PackageReleasePluginGetConfigVariablesResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin/get_config_variables"
      body : "*"
    };
  }

  // ListReleaseCert lists cert releases.
  rpc ListReleaseCert(PackageReleaseCertListReq)
      returns (PackageReleaseCertListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/cert/list"
      body : "*"
    };
  }

  // DeleteReleaseCert deletes cert release.
  rpc DeleteReleaseCert(PackageReleaseCertDeleteReq)
      returns (PackageReleaseCertDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/cert/delete"
      body : "*"
    };
  }

  // ListReleaseBinTool lists bintool releases.
  rpc ListReleaseBinTool(PackageReleaseBinToolListReq)
      returns (PackageReleaseBinToolListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/bintool/list"
      body : "*"
    };
  }

  // DeleteReleaseBinTool deletes bintool release.
  rpc DeleteReleaseBinTool(PackageReleaseBinToolDeleteReq)
      returns (PackageReleaseBinToolDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/bintool/delete"
      body : "*"
    };
  }

  // ListReleasePluginBinTool lists plugin-bintool releases.
  rpc ListReleasePluginBinTool(PackageReleasePluginBinToolListReq)
      returns (PackageReleasePluginBinToolListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin_bintool/list"
      body : "*"
    };
  }

  // DeleteReleasePluginBinTool deletes plugin-bintool release.
  rpc DeleteReleasePluginBinTool(PackageReleasePluginBinToolDeleteReq)
      returns (PackageReleasePluginBinToolDeleteResp) {
    option (google.api.http) = {
      post : "/api/v3/package/release/plugin_bintool/delete"
      body : "*"
    };
  }

  // PackageEventList provides package event listing.
  rpc PackageEventList(PackageEventListReq) returns (PackageEventListResp) {
    option (google.api.http) = {
      post : "/api/v3/package/event/list"
      body : "*"
    };
  }

  // PackageEventDistinct provides package event distincting.
  rpc PackageEventDistinct(PackageEventDistinctReq)
      returns (PackageEventDistinctResp) {
    option (google.api.http) = {
      post : "/api/v3/package/event/distinct"
      body : "*"
    };
  }

  // PackageImport provides package importing.
  rpc PackageImport(PackageImportReq) returns (PackageImportResp) {
    option (google.api.http) = {
      post : "/api/v3/package/import"
      body : "*"
    };
  }
}
