syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";
import "workflow.proto";

import "google/api/annotations.proto";

// PackageImportPluginV3PkgReq describes the HTTP request body when import
// plugin package in package service.
message PackageImportPluginV3PkgReq {
  string filename = 1;
  string download_url = 2;
  string md5 = 3;
}

// PackageImportPluginV3PkgResp describes the HTTP response body when import
// plugin package in package service.
message PackageImportPluginV3PkgResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }

  Data data = 5;
}

// PackageImportPluginV2PkgReq describes the HTTP request body when import
// plugin v2 package in package service.
message PackageImportPluginV2PkgReq {
  string filename = 1;
  string download_url = 2;
  string md5 = 3;
}

// PackageImportPluginV2PkgResp describes the HTTP response body when import
// plugin v2 package in package service.
message PackageImportPluginV2PkgResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }

  Data data = 5;
}

// PackageImportExternalPluginV2PkgReq describes the HTTP request body when
// import external plugin v2 package in package service.
message PackageImportExternalPluginV2PkgReq {
  string filename = 1;
  string download_url = 2;
  string md5 = 3;
}

// PackageImportExternalPluginV2PkgResp describes the HTTP response body when
// import external plugin v2 package in package service.
message PackageImportExternalPluginV2PkgResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }

  Data data = 5;
}

// PackageImportResultReq describes the package import result request.
message PackageImportResultReq { string workflow_id = 1; }

// PackageImportResultResp describes the package import result response.
message PackageImportResultResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data {
    string status = 1;
    bool is_finish = 4;
    repeated OperationResult operations = 5;
  }

  // OperationResult describes the execution result of one operation in the
  // package import workflow.
  message OperationResult {
    string operation_id = 1;
    string last_instance_id = 2;
    map<string, WorkflowActionData> oper_inst_logs = 3;
    WorkflowActionMessage extra_execution_logs = 4;
  }

  Data data = 5;
}

// PackageWorkflow defines the package workflow service.
service PackageWorkflow {
  // PackageImport provides package importing.
  rpc PackageImport(PackageImportPluginV3PkgReq)
      returns (PackageImportPluginV3PkgResp) {
    option (google.api.http) = {
      post : "/api/v3/package/workflow/import/v3/plugin"
      body : "*"
    };
  }

  // PackagePluginV2Import provides package plugin v2 importing.
  rpc PackagePluginV2Import(PackageImportPluginV2PkgReq)
      returns (PackageImportPluginV2PkgResp) {
    option (google.api.http) = {
      post : "/api/v3/package/workflow/import/v2/plugin"
      body : "*"
    };
  }

  // PackageExternalPluginV2Import provides package external plugin v2
  // importing.
  rpc PackageExternalPluginV2Import(PackageImportExternalPluginV2PkgReq)
      returns (PackageImportExternalPluginV2PkgResp) {
    option (google.api.http) = {
      post : "/api/v3/package/workflow/import/v2/external_plugin"
      body : "*"
    };
  }

  // PackageImportResult provides the package import result.
  rpc PackageImportResult(PackageImportResultReq)
      returns (PackageImportResultResp) {
    option (google.api.http) = {
      post : "/api/v3/package/workflow/import_result"
      body : "*"
    };
  }
}
