syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

// PluginOperateFullInfo describes the full information of a plugin operation,
// which
message PluginOperateFullInfo {
  int64 bk_host_id = 1;
  string plugin_name = 2;
  string version = 3;
  repeated string config_name = 4;
  optional google.protobuf.Struct custom_config_context = 5;
}

// PluginOperateBasicInfo describes the basic information of a plugin operation,
// which
message PluginOperateBasicInfo {
  int64 bk_host_id = 1;
  string plugin_name = 2;
}

// PluginInstallReq describes the plugin install request.
message PluginInstallReq { repeated PluginOperateFullInfo plugin = 1; }

// PluginInstallResp describes the plugin install response.
message PluginInstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginUpgradeReq describes the plugin upgrade request.
message PluginUpgradeReq { repeated PluginOperateFullInfo plugin = 1; }

// PluginUpgradeResp describes the plugin upgrade response.
message PluginUpgradeResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginUninstallReq describes the plugin uninstall request.
message PluginUninstallReq { repeated PluginOperateBasicInfo plugin = 1; }

// PluginUninstallResp describes the plugin uninstall response.
message PluginUninstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginApplySubConfigReq describes the plugin apply sub-configuration
// request.
message PluginApplySubConfigReq { repeated PluginOperateFullInfo plugin = 1; }

// PluginApplySubConfigResp describes the plugin apply sub-configuration
// response.
message PluginApplySubConfigResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginListReq describes the plugin list request.
message PluginListReq {
  Page page = 1;
  bool only_count = 2;

  message ExactConditions {
    repeated string name = 1;
    repeated string group = 2;
    repeated int64 visible_biz_ids = 3;
  }
  ExactConditions exact_include_conditions = 3;

  message FuzzyConditions {
    repeated string name = 1;
    repeated string pkg_name = 2;
  }
  FuzzyConditions fuzzy_include_conditions = 4;
}

// PluginListResp describes the plugin list response.
message PluginListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Plugin {
    optional string tenant_id = 1;
    optional string name = 2;
    optional string group = 3;
    optional string pkg_name = 4;
    optional string memo = 5;
    repeated string visible_biz_ids = 6;
  }

  message Data {
    int64 total = 1;
    repeated Plugin items = 2;
  }
  Data data = 5;
}

// PluginSetMemoReq describes the plugin set memo request.
message PluginSetMemoReq {
  string plugin_name = 1;
  string memo = 2;
}

// PluginSetMemoResp describes the plugin set memo response.
message PluginSetMemoResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;
}

// PluginRestartReq describes the plugin restart request.
message PluginRestartReq { repeated PluginOperateBasicInfo plugin = 1; }

// PluginRestartResp describes the plugin restart response.
message PluginRestartResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginStopReq describes the plugin stop request.
message PluginStopReq { repeated PluginOperateBasicInfo plugin = 1; }

// PluginStopResp describes the plugin stop response.
message PluginStopResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// PluginMigrateFromV2Req describes the plugin migrate from v2 request.
message PluginMigrateFromV2Req { repeated PluginOperateBasicInfo plugin = 1; }

// PluginMigrateFromV2Resp describes the plugin migrate from v2 response.
message PluginMigrateFromV2Resp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

service Plugin {
  // InstallPlugin installs a plugin on specified hosts.
  rpc InstallPlugin(PluginInstallReq) returns (PluginInstallResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/install"
      body : "*"
    };
  }

  // UpgradePlugin upgrades a plugin on specified hosts.
  rpc UpgradePlugin(PluginUpgradeReq) returns (PluginUpgradeResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/upgrade"
      body : "*"
    };
  }

  // UninstallPlugin uninstalls a plugin on specified hosts.
  rpc UninstallPlugin(PluginUninstallReq) returns (PluginUninstallResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/uninstall"
      body : "*"
    };
  }

  // ApplyPluginSubConfig apply sub-configuration for a plugin on specified
  // hosts.
  rpc ApplyPluginSubConfig(PluginApplySubConfigReq)
      returns (PluginApplySubConfigResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/apply_subconfig"
      body : "*"
    };
  }

  // ListPlugins lists plugins based on the given conditions.
  rpc ListPlugins(PluginListReq) returns (PluginListResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/list"
      body : "*"
    };
  }

  // SetPluginMemo sets the memo for a plugin.
  rpc SetPluginMemo(PluginSetMemoReq) returns (PluginSetMemoResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/set_memo"
      body : "*"
    };
  }

  // RestartPlugin restarts the plugin process on specified hosts.
  rpc RestartPlugin(PluginRestartReq) returns (PluginRestartResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/restart"
      body : "*"
    };
  }

  // StopPlugin stops the plugin process on specified hosts.
  rpc StopPlugin(PluginStopReq) returns (PluginStopResp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/stop"
      body : "*"
    };
  }

  // MigratePluginFromV2 migrates plugin process from v2 on specified hosts.
  rpc MigratePluginFromV2(PluginMigrateFromV2Req)
      returns (PluginMigrateFromV2Resp) {
    option (google.api.http) = {
      post : "/api/v3/plugin/migrate_from_v2"
      body : "*"
    };
  }
}
