syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// PluginOfficialInstallReq describes the plugin official install request.
message PluginOfficialInstallReq {
  message Plugin {
    optional int64 bk_host_id = 1;
    string name = 2;
    string version = 3;
  }

  repeated Plugin plugin = 1;
  message TargetVersion {
    string version = 1;
    string cpu_arch = 2;
    string os_type = 3;
  }

  repeated TargetVersion target_version = 2;
  bool disable_default_target_version = 3;
}

// PluginOfficialInstallResp describes the plugin official install response.
message PluginOfficialInstallResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data { string workflow_id = 1; }
  Data data = 5;
}