syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";

message ProcessExactConditions {
  repeated int64 bk_host_id = 1;
  repeated string plugin_group = 3;
  repeated string node_generation = 4;
  repeated string platform_os = 5;
  repeated string platform_arch = 6;
  repeated string status = 7;
  repeated string agent_id = 8;
  repeated string version = 9;
  repeated string plugin_name = 10;
  repeated string plugin_pkg_name = 11;
}

message ProcessFuzzyConditions {
  repeated string name = 1;
  repeated string plugin_pkg_name = 2;
}

// ProcessListReq describes the process list request.
message ProcessListReq {
  Page page = 1;
  bool only_count = 2;

  ProcessExactConditions exact_include_conditions = 3;

  ProcessFuzzyConditions fuzzy_include_conditions = 4;
}

// ProcessInfo describes the process information.
message ProcessInfo {
  optional int32 pid = 1;
  optional string version = 2;
  optional string agent_id = 3;
  optional bool auto_start = 4;
  optional string status = 5;
}

// ProcessIdentity describes the process identity.
message ProcessIdentity {
  optional string name = 1;
  optional string setup_path = 2;
  optional string pid_path = 3;
  optional string config_path = 4;
  optional string log_path = 5;
  optional string user = 6;
}

// ProcessController describes the process controller.
message ProcessController {
  optional string start_cmd = 1;
  optional string stop_cmd = 2;
  optional string restart_cmd = 3;
  optional string reload_cmd = 4;
  optional string kill_cmd = 5;
  optional string version_cmd = 6;
  optional string health_cmd = 7;
}

// ProcessResource describes the process resource.
message ProcessResource {
  optional double cpu_limit_percent = 1;
  optional double mem_limit_percent = 2;
}

// ProcessMonitorPolicy describes the process monitor policy.
message ProcessMonitorPolicy {
  optional string auto_type = 1;
  optional int64 start_check_seconds = 2;
  optional int64 stop_check_seconds = 3;
  optional int64 operate_timeout_seconds = 4;
}

// ProcessListResp describes the process list response.
message ProcessListResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Process {
    optional string tenant_id = 1;
    optional int64 bk_host_id = 2;
    optional string plugin_name = 3;
    optional string plugin_pkg_name = 4;
    optional string plugin_group = 5;
    optional Platform platform = 6;
    optional int64 generation = 7;
    optional ProcessInfo process_info = 8;
    optional ProcessIdentity process_identity = 9;
    optional ProcessController process_controller = 10;
    optional ProcessResource process_resource = 11;
    optional ProcessMonitorPolicy process_monitor_policy = 12;
  }

  message Data {
    int64 total = 1;
    repeated Process items = 2;
  }
  Data data = 5;
}

// GetProcessDistributionByHostIDReq describes the process statistics request.
message GetProcessDistributionByHostIDReq {
  ProcessExactConditions exact_include_conditions = 1;
  ProcessFuzzyConditions fuzzy_include_conditions = 2;
}

// GetProcessDistributionByHostIDResp describes the process statistics response.
message GetProcessDistributionByHostIDResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  map<int64, int64> data = 5;
}

// GetProcessDistributionByPluginNameReq describes the process statistics
// request.
message GetProcessDistributionByPluginNameReq {
  ProcessExactConditions exact_include_conditions = 1;
  ProcessFuzzyConditions fuzzy_include_conditions = 2;
}

// GetProcessDistributionByPluginNameResp describes the process statistics
// response.
message GetProcessDistributionByPluginNameResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  map<string, int64> data = 5;
}

service Process {
  // ListProcesses lists the processes.
  rpc ListProcesses(ProcessListReq) returns (ProcessListResp) {
    option (google.api.http) = {
      post : "/api/v3/process/list"
      body : "*"
    };
  }

  // GetProcessDistributionByHostID describes the process statistics request.
  rpc GetProcessDistributionByHostID(GetProcessDistributionByHostIDReq)
      returns (GetProcessDistributionByHostIDResp) {
    option (google.api.http) = {
      post : "/api/v3/process/get_distribution_by_host_id"
      body : "*"
    };
  }

  // GetProcessDistributionByPluginName describes the process statistics
  // request.
  rpc GetProcessDistributionByPluginName(GetProcessDistributionByPluginNameReq)
      returns (GetProcessDistributionByPluginNameResp) {
    option (google.api.http) = {
      post : "/api/v3/process/get_distribution_by_plugin_name"
      body : "*"
    };
  }
}