syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// SyncCmdbHostReq describes the HTTP request body when sync cmdb host.
message SyncCmdbHostReq {}

// SyncCmdbHostResp describes the HTTP response body when sync cmdb host.
message SyncCmdbHostResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// SyncCmdbNetworkAreaReq describes the HTTP request body when sync cmdb
// networkarea.
message SyncCmdbNetworkAreaReq {}

// SyncCmdbNetworkAreaResp describes the HTTP response body when sync cmdb
// networkarea.
message SyncCmdbNetworkAreaResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// SyncCmdbConstantsReq describes the HTTP request body when sync cmdb
// constants.
message SyncCmdbConstantsReq {}

// SyncCmdbConstantsResp describes the HTTP response body when sync cmdb
// constants.
message SyncCmdbConstantsResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string workflow_id = 1; }
  Data data = 5;
}

// SyncAgentStateReq describes the HTTP request body when sync agent state.
message SyncAgentStateReq { repeated int64 host_ids = 1; }

// SyncAgentStateResp describes the HTTP response body when sync agent state.
message SyncAgentStateResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// SyncAllAgentStateReq describes the HTTP request body when sync all agent
// state.
message SyncAllAgentStateReq {}

// SyncAllAgentStateResp describes the HTTP response body when sync all agent
// state.
message SyncAllAgentStateResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// SyncAgentInfoReq describes the HTTP request body when sync agent info.
message SyncAgentInfoReq { repeated int64 host_ids = 1; }

// SyncAgentInfoResp describes the HTTP response body when sync agent info.
message SyncAgentInfoResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// SyncCorrectAgentIDReq describes the HTTP request body when correct agent id.
message SyncCorrectAgentIDReq { repeated int64 host_ids = 1; }

// SyncCorrectAgentIDResp describes the HTTP response body when correct agent
// id.
message SyncCorrectAgentIDResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// SyncAliveHostAgentInfoReq describes the HTTP request body when sync alive
// host agent info.
message SyncAliveHostAgentInfoReq {}

// SyncAliveHostAgentInfoResp describes the HTTP response body when sync alive
// host agent info.
message SyncAliveHostAgentInfoResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// SyncAlivePluginProcessInfoReq describes the HTTP request body when sync alive
message SyncAlivePluginProcessInfoReq { repeated int64 host_ids = 1; }

// SyncAlivePluginProcessInfoResp describes the HTTP response body when sync
// alive
message SyncAlivePluginProcessInfoResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// SyncAllAlivePluginProcessInfoReq describes the HTTP request body when sync
// all alive
message SyncAllAlivePluginProcessInfoReq {}

// SyncAllAlivePluginProcessInfoResp describes the HTTP response body when sync
// all alive
message SyncAllAlivePluginProcessInfoResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;
  Permission permission = 6;

  message Data { string trigger_id = 1; }
  Data data = 5;
}

// sync service.
service Sync {
  // SyncCmdbHost provides syncing cmdb host.
  rpc SyncCmdbHost(SyncCmdbHostReq) returns (SyncCmdbHostResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/cmdb/host"
      body : "*"
    };
  }

  // SyncCmdbNetworkArea provides syncing cmdb networkarea.
  rpc SyncCmdbNetworkArea(SyncCmdbNetworkAreaReq)
      returns (SyncCmdbNetworkAreaResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/cmdb/networkarea"
      body : "*"
    };
  }

  // SyncCmdbConstants provides syncing cmdb constants.
  rpc SyncCmdbConstants(SyncCmdbConstantsReq) returns (SyncCmdbConstantsResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/cmdb/constants"
      body : "*"
    };
  }

  rpc SyncAgentState(SyncAgentStateReq) returns (SyncAgentStateResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/agent/state"
      body : "*"
    };
  }

  rpc SyncAllAgentState(SyncAllAgentStateReq) returns (SyncAllAgentStateResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/agent/state/all"
      body : "*"
    };
  }

  rpc SyncAgentInfo(SyncAgentInfoReq) returns (SyncAgentInfoResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/agent/info"
      body : "*"
    };
  }

  rpc SyncCorrectAgentID(SyncCorrectAgentIDReq)
      returns (SyncCorrectAgentIDResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/agent/id/correct"
      body : "*"
    };
  }

  rpc SyncAliveHostAgentInfo(SyncAliveHostAgentInfoReq)
      returns (SyncAliveHostAgentInfoResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/agent/info/alive"
      body : "*"
    };
  }

  rpc SyncAlivePluginProcessInfo(SyncAlivePluginProcessInfoReq)
      returns (SyncAlivePluginProcessInfoResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/plugin/process/info"
      body : "*"
    };
  }

  rpc SyncAllAlivePluginProcessInfo(SyncAllAlivePluginProcessInfoReq)
      returns (SyncAllAlivePluginProcessInfoResp) {
    option (google.api.http) = {
      post : "/api/v3/sync/gse/plugin/process/info/all"
      body : "*"
    };
  }
}