syntax = "proto3";
package v3;
option go_package = "github.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3";

import "common.proto";

import "google/api/annotations.proto";

// OperationRetryReq describes the operation retry request.
message OperationRetryReq {
  string operation_id = 1;
  string action_name = 2;
}

// OperationRetryResp describes the operation retry response.
message OperationRetryResp {
  int32 code = 1;
  string message = 2;
  string request_id = 3;
  Error error = 4;

  message Data {
    string workflow_id = 1;
    string operation_id = 2;
    string action_name = 3;
  }
  Data data = 5;
}
