{{- if .Values.apigwSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-apigw-sync
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    values-hash: "{{ toYaml .Values.apigwSync | sha256sum | trunc 63 }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.apigwSync.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.apigwSync.backoffLimit }}
  parallelism: {{ .Values.apigwSync.parallelism }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app: nodemgr-apigw-sync
    spec:
      {{- include "bk-nodemgr.apiManagerImagePullSecrets" . | nindent 6 }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.hostAliases }}
      # yamllint disable rule:indentation
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      # yamllint enable rule:indentation
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" (merge .Values.apigwSync.nodeSelector .Values.nodeSelector) "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "bk-nodemgr.fullname" . }}-apigw-sync
          {{- $apigwTag := default .Values.image.tag .Values.apiManagerImage.tag }}
          {{- if .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.apiManagerImage.repository }}:{{ $apigwTag }}
          {{- else }}
          image: {{ .Values.apiManagerImage.registry }}/{{ .Values.apiManagerImage.repository }}:{{ $apigwTag }}
          {{- end }}
          imagePullPolicy: {{ .Values.apiManagerImage.pullPolicy | quote }}
          volumeMounts:
            - name: apigw-sync-config
              mountPath: "/data/definition.yaml"
              subPath: definition.yaml
          command:
            - bash
          args:
            - bin/sync-apigateway.sh
          env:
          {{- $extraEnvVars := list }}
          {{- range .Values.apigwSync.extraEnvVars }}
          {{- if ne .name "BK_APP_TENANT_ID" }}
          {{- $extraEnvVars = append $extraEnvVars . }}
          {{- end }}
          {{- end }}
          {{- with $extraEnvVars }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: BK_APP_TENANT_ID
              value: {{ ternary "default" "system" (eq .Values.backend.config.tenantMode "single") | quote }}
          resources: {{- toYaml .Values.initContainerResources | nindent 12 }}
      volumes:
      - name: apigw-sync-config
        configMap:
          name: {{ template "bk-nodemgr.fullname" . }}-apigw-sync-definition
      restartPolicy: Never
{{- end }}
