{{- if .Values.application.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-application
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodemgr-application
    metric: nodemgr-application-metric
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: nodemgr-application
  ports:
    - name: info-http
      port: {{ .Values.application.config.infoServer.port }}
      targetPort: info-http
    - name: admin-http
      port: {{ .Values.application.config.adminServer.port }}
      targetPort: admin-http
    - name: basic-http
      port: {{ .Values.application.config.basicServer.port }}
      targetPort: basic-http
{{- end }}
