{{- if .Values.application.enabled }}
{{- if .Values.application.ingress.enabled }}
{{- if not .Values.application.ingress.className }}
apiVersion: networkextension.bkbcs.tencent.com/v1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-application
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or (not .Values.application.ingress.className) .Values.commonAnnotations }}
  annotations:
    {{- if not .Values.application.ingress.className }}
    networkextension.bkbcs.tencent.com/lbids: {{ .Values.application.ingress.lbid }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.application.ingress.className }}
  rules:
  {{- if len .Values.application.ingress.certID }}
  - port: 443
    protocol: HTTPS
    certificate:
      mode: UNIDIRECTIONAL
      certID: {{ .Values.application.ingress.certID }}
  {{- else }}
  - port: 80
    protocol: HTTP
  {{- end }}
    listenerAttribute:
      lbPolicy: {{ .Values.application.ingress.lbPolicy }}
    layer7Routes:
    - domain: {{ .Values.application.ingress.domain }}
      path: {{ .Values.application.ingress.path }}
      services:
      - serviceName: {{ template "bk-nodemgr.fullname" . }}-application
        serviceNamespace: {{ .Release.Namespace | quote }}
        servicePort: {{ .Values.application.config.basicServer.port }}
        isDirectConnect: {{ .Values.application.ingress.isDirectConnect }}
  {{- else }}
  ingressClassName: {{ .Values.application.ingress.className }}
  {{- if .Values.application.ingress.tlsSecretName }}
  tls:
  - hosts:
    - {{ .Values.application.ingress.domain }}
    secretName: {{ .Values.application.ingress.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .Values.application.ingress.domain }}
    http:
      paths:
      - path: {{ .Values.application.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "bk-nodemgr.fullname" . }}-application
            port:
              number: {{ .Values.application.config.basicServer.port }}
  {{- end }}
{{- end }}
{{- end }}
