{{- if .Values.application.enabled }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-application
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    values-hash: "{{ toYaml .Values.application.config | sha256sum | trunc 63 }}"
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "bk-nodemgr.replicaCount" ( dict "root" .Values "module" .Values.application ) }}
  {{- if .Values.updateStrategy }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.updateStrategy.type) }}
    rollingUpdate: null
    {{- else }}
    rollingUpdate: {{ .Values.updateStrategy.rollingUpdate | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: nodemgr-application
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app: nodemgr-application
      {{- if .Values.application.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.application.podAnnotations "context" $) | nindent 8 }}
      {{- else if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "bk-nodemgr.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.hostAliases }}
      # yamllint disable rule:indentation
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      # yamllint enable rule:indentation
      {{- end }}
      {{- if or .Values.nodeSelector .Values.application.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" (merge .Values.application.nodeSelector .Values.nodeSelector) "context" $) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.application.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" (concat .Values.tolerations .Values.application.tolerations) "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      {{- if .Values.application.hostNetwork }}
                      - nodemgr-application
                      {{- else }}
                      - nodemgr-no-affinity
                    {{- end }}
              topologyKey: kubernetes.io/hostname
              namespaces: []
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.application.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ template "bk-nodemgr.fullname" . }}-application
          {{- if len .Values.application.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.application.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.application.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodemgr.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - {{ .Values.common.binPath }}/bk-nodemgr-application
          args:
            - webserver
            - -f
            - {{ .Values.common.etcPath }}/application_conf.yaml
          env:
            - name: NODEMAN-MODULE
              value: application
            - name: BK_NODEMGR_TRACING_INSTANCEID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: info-http
              containerPort: {{ .Values.application.config.infoServer.port }}
            - name: basic-http
              containerPort: {{ .Values.application.config.basicServer.port }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: info-http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- else if .Values.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 10 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: info-http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- else if .Values.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: nodemgr-cert
              mountPath: {{ .Values.common.certPath }}
            - name: nodemgr-etc
              mountPath: {{ .Values.common.etcPath }}
            {{- if .Values.application.config.configPolicyOption.agentOption }}
            - name: {{ template "bk-nodemgr.fullname" . }}-application-config
              mountPath: {{ printf "%s/%s" .Values.application.config.configPolicyOption.filePath "agent_option.json" | quote }}
              subPath: agent_option.json
            {{- end }}
            {{- if .Values.application.config.configPolicyOption.proxyOption }}
            - name: {{ template "bk-nodemgr.fullname" . }}-application-config
              mountPath: {{ printf "%s/%s" .Values.application.config.configPolicyOption.filePath "proxy_option.json" | quote }}
              subPath: proxy_option.json
            {{- end }}
            {{- if .Values.application.config.configPolicyOption.pluginOption }}
            - name: {{ template "bk-nodemgr.fullname" . }}-application-config
              mountPath: {{ printf "%s/%s" .Values.application.config.configPolicyOption.filePath "plugin_option.json" | quote }}
              subPath: plugin_option.json
            {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources: {{- toYaml .Values.application.resources | nindent 12 }}
          {{- end }}

      initContainers:
        - name: {{ template "bk-nodemgr.fullname" . }}-application-check-mongodb
          {{- if len .Values.application.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.application.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.application.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodemgr.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["sh", "-c"]
          args:
          - |
            /bin/sh <<'EOF'

            mongobin="mongo"

            # check mongodb.
            try_times=1
            ret=1
            sleep_time=1
            while [ ${ret} -ne 0 ]
            do
                {{- if .Values.mongodb.enabled }}
                ${mongobin} {{ template "bk-nodemgr.fullname" . }}-mongodb-headless:{{ .Values.mongodb.service.port }}/{{ .Values.mongodb.auth.database }} -u {{ .Values.mongodb.auth.username }} -p {{ .Values.mongodb.auth.password }} --eval "db.runCommand({ping: 1})"
                {{- else }}
                ${mongobin} {{ join "," .Values.externalMongodb.hosts }}/{{ .Values.externalMongodb.database }} --authenticationDatabase {{ .Values.mongodb.auth.authSource }} -u {{ .Values.externalMongodb.username }} -p {{ .Values.externalMongodb.password }} --eval "db.runCommand({ping: 1})"
                {{- end }}

                ret=$?
                echo try to check ${try_times} times
                try_times=$((try_times+1))
                sleep ${sleep_time}
            done

            echo "check mongodb done"
            EOF
          resources: {{- toYaml .Values.initContainerResources | nindent 12 }}
        - name: {{ template "bk-nodemgr.fullname" . }}-application-init
          {{- if len .Values.application.imageTag }}
          {{- if len .Values.global.imageRegistry }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.application.imageTag }}
          {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.application.imageTag }}
          {{- end }}
          {{- else }}
          image: {{ template "bk-nodemgr.image" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["sh", "-c"]
          args:
          - |
            /bin/sh <<'EOF'

            # for service api advertise ip, it may be ipv4 or ipv6 value which base on k8s node settings.
            ADVERTISE_IP=${POD_IP}

            # for agent schedule advertise ip, parsing ipv4 and ipv6 value which base on k8s node settings.
            ips=$(echo "${POD_IPS}" | sed 's/,/ /g')
            for ip in $ips; do
              echo "$ip" | grep -q : 2>/dev/null
              if [ $? -eq 0 ]; then
                ADVERTISE_IPV6=$ip
              else
                ADVERTISE_IPV4=$ip
              fi
            done

            if [ -n "{{ .Values.application.config.advertiseIPV4 }}" ]; then
              ADVERTISE_IPV4={{ .Values.application.config.advertiseIPV4 }}
            fi
            if [ -n "{{ .Values.application.config.advertiseIPV6 }}" ]; then
              ADVERTISE_IPV6={{ .Values.application.config.advertiseIPV6 }}
            fi

            # sed local config file.
            cp /tmp/application_conf.yaml {{ .Values.common.etcPath }}/application_conf.yaml
            sed -i "s/__ADVERTISE_IPV4__/${ADVERTISE_IPV4}/g" {{ .Values.common.etcPath }}/application_conf.yaml
            sed -i "s/__ADVERTISE_IPV6__/${ADVERTISE_IPV6}/g" {{ .Values.common.etcPath }}/application_conf.yaml

            echo "local module init done"
            EOF
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_IPS
            valueFrom:
              fieldRef:
                fieldPath: status.podIPs
          volumeMounts:
            - name: {{ template "bk-nodemgr.fullname" . }}-application-config
              mountPath: /tmp
            - name: nodemgr-etc
              mountPath: {{ .Values.common.etcPath }}
          resources: {{- toYaml .Values.initContainerResources | nindent 12 }}
      hostNetwork: {{ .Values.application.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: nodemgr-cert
        configMap:
          name: {{ template "bk-nodemgr.fullname" . }}-certs
      - name: {{ template "bk-nodemgr.fullname" . }}-application-config
        configMap:
          name: {{ template "bk-nodemgr.fullname" . }}-application-config
      - name: nodemgr-etc
        emptyDir: {}
{{- end }}
