{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodemgr-backend
    metric: nodemgr-backend-metric
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: nodemgr-backend
  ports:
    - name: info-http
      port: {{ .Values.backend.config.infoServer.port }}
      targetPort: info-http
    - name: admin-http
      port: {{ .Values.backend.config.adminServer.port }}
      targetPort: admin-http
    - name: basic-http
      port: {{ .Values.backend.config.basicServer.port }}
      targetPort: basic-http
    - name: callback-http
      port: {{ .Values.backend.config.callbackServer.port }}
      targetPort: callback-http
    - name: proxy-http
      port: {{ .Values.backend.config.proxyServer.port }}
      targetPort: proxy-http
{{- end }}
