{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-backend-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  backend_conf.yaml: |
    runMode: {{ .Values.backend.config.runMode }}

    tenantMode: {{ .Values.backend.config.tenantMode }}

    system: {{ .Values.backend.config.system | toYaml | nindent 6 }}

    encryptKey: {{ .Values.backend.config.encryptKey | quote }}

    infoServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.backend.config.infoServer "terminationGracePeriodSeconds" (.Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    adminServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.backend.config.adminServer "terminationGracePeriodSeconds" (.Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    basicServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.backend.config.basicServer "terminationGracePeriodSeconds" (.Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    callbackServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.backend.config.callbackServer "terminationGracePeriodSeconds" (.Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    proxyServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.backend.config.proxyServer "terminationGracePeriodSeconds" (.Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    workflow: {{ include "bk-nodemgr.workflowConfig" (dict "config" .Values.backend.config.workflow "terminationGracePeriodSeconds" (.Values.backend.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}

    cmdb: {{ .Values.backend.config.cmdb | toYaml | nindent 6 }}

    gse: {{ .Values.backend.config.gse | toYaml | nindent 6 }}

    userManager: {{ .Values.backend.config.userManager | toYaml | nindent 6 }}
    
    creditVault: {{ .Values.backend.config.creditVault | toYaml | nindent 6 }}

    log: {{ .Values.backend.config.log | toYaml | nindent 6 }}

    iamV3: {{ .Values.backend.config.iamV3 | toYaml | nindent 6 }}

    file: {{ .Values.backend.config.file | toYaml | nindent 6 }}

    etcd:
      {{- if .Values.etcd.enabled }}
      endpoints:
        - {{ template "bk-nodemgr.fullname" . }}-etcd-headless:2379
      {{- else }}
      endpoints: {{ .Values.externalEtcd.endpoints | toYaml | nindent 6 }}
      username: {{ .Values.externalEtcd.username }}
      password: {{ .Values.externalEtcd.password }}
      tls:
        {{- if len .Values.externalEtcd.tls.ca }}
        caFile: {{ .Values.common.certPath }}/etcdca.crt
        certFile: {{ .Values.common.certPath }}/etcd.crt
        keyFile: {{ .Values.common.certPath }}/etcd.key
        password: {{ .Values.externalEtcd.tls.password }}
        {{- else if len .Values.externalEtcd.tls.secretName }}
        "caFile": "{{ .Values.common.certPath }}/{{ .Values.externalEtcd.tls.secretCaFileName }}",
        "certFile": "{{ .Values.common.certPath }}/{{ .Values.externalEtcd.tls.secretCertFileName }}",
        "keyFile": "{{ .Values.common.certPath }}/{{ .Values.externalEtcd.tls.secretKeyFileName }}",
        {{- end}}
      {{- end}}

    redis:
      {{- if .Values.redis.enabled }}
      type: standalone
      addrs:
        - "{{ template "bk-nodemgr.fullname" . }}-redis-headless:{{ .Values.redis.service.ports.redis }}"
      password: {{ .Values.redis.auth.password }}
      db: 0
      {{- else }}
      type: {{ .Values.externalRedis.type }}
      addrs: {{ .Values.externalRedis.addrs | toYaml | nindent 8 }}
      password: {{ .Values.externalRedis.password }}
      db: {{ .Values.externalRedis.db }}
      {{- if eq .Values.externalRedis.type "sentinel" }}
      masterName: {{ .Values.externalRedis.masterName }}
      {{- end }}
      tls:
        {{- if len .Values.externalRedis.tls.ca }}
        caFile: {{ .Values.common.certPath }}/redisca.crt
        certFile: {{ .Values.common.certPath }}/redis.crt
        keyFile: {{ .Values.common.certPath }}/redis.key
        password: {{ .Values.externalRedis.tls.password }}
        {{- else if len .Values.externalRedis.tls.secretName }}
        "caFile": "{{ .Values.common.certPath }}/{{ .Values.externalRedis.tls.secretCaFileName }}",
        "certFile": "{{ .Values.common.certPath }}/{{ .Values.externalRedis.tls.secretCertFileName }}",
        "keyFile": "{{ .Values.common.certPath }}/{{ .Values.externalRedis.tls.secretKeyFileName }}",
        {{- end}}
      {{- end}}
      traceServiceName: {{ .Values.backend.config.redis.traceServiceName }}
      traceSampleRate: {{ .Values.backend.config.redis.traceSampleRate }}

    mongodb:
      appName: {{ template "bk-nodemgr.fullname" . }}-backend
      {{- if .Values.mongodb.enabled }}
      replicaSet: {{ .Values.mongodb.replicaSetName }}
      hosts:
        - {{ template "bk-nodemgr.fullname" . }}-mongodb-headless
      username: {{ .Values.mongodb.auth.username }}
      password: {{ .Values.mongodb.auth.password }}
      database: {{ .Values.mongodb.auth.database }}
      authSource: {{ .Values.mongodb.auth.database }}
      authMechanism: SCRAM-SHA-256
      {{- else }}
      replicaSet: {{ .Values.externalMongodb.replicaSetName }}
      hosts: {{ .Values.externalMongodb.hosts | toYaml | nindent 6}}
      username: {{ .Values.externalMongodb.username }}
      password: {{ .Values.externalMongodb.password }}
      database: {{ .Values.externalMongodb.database }}
      authSource: {{ .Values.externalMongodb.authSource }}
      authMechanism: {{ .Values.externalMongodb.authMechanism }}
      tls:
        {{- if len .Values.externalMongodb.tls.ca }}
        caFile: {{ .Values.common.certPath }}/mongoca.crt
        certFile: {{ .Values.common.certPath }}/mongo.crt
        keyFile: {{ .Values.common.certPath }}/mongo.key
        password: {{ .Values.externalMongodb.tls.password }}
        {{- else if len .Values.externalMongodb.tls.secretName }}
        "caFile": "{{ .Values.common.certPath }}/{{ .Values.externalMongodb.tls.secretCaFileName }}",
        "certFile": "{{ .Values.common.certPath }}/{{ .Values.externalMongodb.tls.secretCertFileName }}",
        "keyFile": "{{ .Values.common.certPath }}/{{ .Values.externalMongodb.tls.secretKeyFileName }}",
        {{- end}}
      {{- end}}
      traceServiceName: {{ .Values.backend.config.mongodb.traceServiceName }}
      traceSampleRate: {{ .Values.backend.config.mongodb.traceSampleRate }}

    installerFileGroup: {{ .Values.backend.config.installerFileGroup | toYaml | nindent 6 }}

    fileCache: {{ .Values.backend.config.fileCache | toYaml | nindent 6 }}

    gseDeployConfs: {{ .Values.backend.config.gseDeployConfs | toYaml | nindent 6 }}

    access: {{ .Values.backend.config.access | toYaml | nindent 6 }}

    tracing:
      {{- omit .Values.backend.config.tracing "instanceID" | toYaml | nindent 6 }}
      instanceID: "__TRACING_INSTANCEID__"
{{- end }}