{{- if .Values.backend.enabled }}
{{- if .Values.backend.ingress.enabled }}
apiVersion: networkextension.bkbcs.tencent.com/v1
kind: Ingress
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    networkextension.bkbcs.tencent.com/lbids: {{ .Values.backend.ingress.lbid }}
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  rules:
  - port: {{ .Values.backend.config.basicServer.port }}
    protocol: TCP
    listenerAttribute:
      lbPolicy: {{ .Values.backend.ingress.lbPolicy }}
    services:
    - serviceName: {{ template "bk-nodemgr.fullname" . }}-backend
      serviceNamespace: {{ .Release.Namespace | quote }}
      servicePort: {{ .Values.backend.config.basicServer.port }}
      isDirectConnect: {{ .Values.backend.ingress.isDirectConnect }}
  - port: {{ .Values.backend.config.proxyServer.port }}
    protocol: TCP
    listenerAttribute:
      lbPolicy: {{ .Values.backend.ingress.lbPolicy }}
    services:
    - serviceName: {{ template "bk-nodemgr.fullname" . }}-backend
      serviceNamespace: {{ .Release.Namespace | quote }}
      servicePort: {{ .Values.backend.config.proxyServer.port }}
      isDirectConnect: {{ .Values.backend.ingress.isDirectConnect }}
{{- end }}
{{- end }}
