{{- if .Values.file.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-file-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  file_conf.yaml: |
    runMode: {{ .Values.file.config.runMode }}

    tenantMode: {{ .Values.file.config.tenantMode }}

    infoServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.file.config.infoServer "terminationGracePeriodSeconds" (.Values.file.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    adminServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.file.config.adminServer "terminationGracePeriodSeconds" (.Values.file.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    basicServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.file.config.basicServer "terminationGracePeriodSeconds" (.Values.file.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    downloadServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.file.config.downloadServer "terminationGracePeriodSeconds" (.Values.file.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    exportServer: {{ include "bk-nodemgr.httpServerConfig" (dict "config" .Values.file.config.exportServer "terminationGracePeriodSeconds" (.Values.file.terminationGracePeriodSeconds | default .Values.terminationGracePeriodSeconds)) | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    downloader: {{ .Values.file.config.downloader | toYaml | nindent 6 }}

    workspaceFileGroup: {{ .Values.file.config.workspaceFileGroup | toYaml | nindent 6 }}

    fileCache: {{ .Values.file.config.fileCache | toYaml | nindent 6 }}

    tempFile: {{ .Values.file.config.tempFile | toYaml | nindent 6 }}

    mountHostDir: {{ .Values.file.config.mountHostDir | toYaml | nindent 6 }}

    gse: {{ .Values.file.config.gse | toYaml | nindent 6 }}

    log: {{ .Values.file.config.log | toYaml | nindent 6 }}

    etcd:
      {{- if .Values.etcd.enabled }}
      endpoints:
        - {{ include "bk-nodemgr.etcd.fullname" . }}-headless:{{ include "bk-nodemgr.etcd.clientPort" . }}
      {{- else }}
      endpoints: {{ .Values.externalEtcd.endpoints | toYaml | nindent 6 }}
      username: {{ .Values.externalEtcd.username }}
      password: {{ .Values.externalEtcd.password }}
      tls:
        {{- if len .Values.externalEtcd.tls.ca }}
        caFile: {{ .Values.common.certPath }}/etcdca.crt
        certFile: {{ .Values.common.certPath }}/etcd.crt
        keyFile: {{ .Values.common.certPath }}/etcd.key
        password: {{ .Values.externalEtcd.tls.password }}
        {{- else if len .Values.externalEtcd.tls.secretName }}
        "caFile": "{{ .Values.common.certPath }}/{{ .Values.externalEtcd.tls.secretCaFileName }}",
        "certFile": "{{ .Values.common.certPath }}/{{ .Values.externalEtcd.tls.secretCertFileName }}",
        "keyFile": "{{ .Values.common.certPath }}/{{ .Values.externalEtcd.tls.secretKeyFileName }}",
        {{- end}}
      {{- end}}

    mongodb:
      appName: {{ template "bk-nodemgr.fullname" . }}-file
      {{- if .Values.mongodb.enabled }}
      replicaSet: {{ .Values.mongodb.replicaSetName }}
      hosts:
        - {{ template "bk-nodemgr.fullname" . }}-mongodb-headless
      username: {{ .Values.mongodb.auth.username }}
      password: {{ .Values.mongodb.auth.password }}
      database: {{ .Values.mongodb.auth.database }}
      authSource: {{ .Values.mongodb.auth.database }}
      authMechanism: SCRAM-SHA-256
      {{- else }}
      replicaSet: {{ .Values.externalMongodb.replicaSetName }}
      hosts: {{ .Values.externalMongodb.hosts | toYaml | nindent 6}}
      username: {{ .Values.externalMongodb.username }}
      password: {{ .Values.externalMongodb.password }}
      database: {{ .Values.externalMongodb.database }}
      authSource: {{ .Values.externalMongodb.authSource }}
      authMechanism: {{ .Values.externalMongodb.authMechanism }}
      tls:
        {{- if len .Values.externalMongodb.tls.ca }}
        caFile: {{ .Values.common.certPath }}/mongoca.crt
        certFile: {{ .Values.common.certPath }}/mongo.crt
        keyFile: {{ .Values.common.certPath }}/mongo.key
        password: {{ .Values.externalMongodb.tls.password }}
        {{- else if len .Values.externalMongodb.tls.secretName }}
        "caFile": "{{ .Values.common.certPath }}/{{ .Values.externalMongodb.tls.secretCaFileName }}",
        "certFile": "{{ .Values.common.certPath }}/{{ .Values.externalMongodb.tls.secretCertFileName }}",
        "keyFile": "{{ .Values.common.certPath }}/{{ .Values.externalMongodb.tls.secretKeyFileName }}",
        {{- end}}
      {{- end}}
      traceServiceName: {{ .Values.file.config.mongodb.traceServiceName }}
      traceSampleRate: {{ .Values.file.config.mongodb.traceSampleRate }}

    tracing:
      {{- include "bk-nodemgr.tracingConfig" (dict "config" .Values.file.config.tracing "context" $) | nindent 6 }}
      instanceID: "__TRACING_INSTANCEID__"

    repo: {{ .Values.file.config.repo | toYaml | nindent 6 }}
{{- end }}
