{{- if .Values.file.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-file-config
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  file_conf.yaml: |
    runMode: {{ .Values.file.config.runMode }}

    tenantMode: {{ .Values.file.config.tenantMode }}

    infoServer: {{ .Values.file.config.infoServer | toYaml | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    adminServer: {{ .Values.file.config.adminServer | toYaml | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    basicServer: {{ .Values.file.config.basicServer | toYaml | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    downloadServer: {{ .Values.file.config.downloadServer | toYaml | nindent 6 }}
      advertiseIPV4: __ADVERTISE_IPV4__
      advertiseIPV6: __ADVERTISE_IPV6__

    workspaceFileGroup: {{ .Values.file.config.workspaceFileGroup | toYaml | nindent 6 }}

    mountHostDir: {{ .Values.file.config.mountHostDir | toYaml | nindent 6 }}

    gse: {{ .Values.file.config.gse | toYaml | nindent 6 }}

    log: {{ .Values.file.config.log | toYaml | nindent 6 }}

    etcd:
      {{- if .Values.etcd.enabled }}
      endpoints:
        - {{ template "bk-nodemgr.fullname" . }}-etcd-headless:2379
      {{- else }}
      endpoints: {{ .Values.externalEtcd.endpoints | toYaml | nindent 6 }}
      username: {{ .Values.externalEtcd.username }}
      password: {{ .Values.externalEtcd.password }}
      ca: {{ .Values.externalEtcd.ca }}
      cert: {{ .Values.externalEtcd.cert }}
      key: {{ .Values.externalEtcd.key }}
      {{- end}}

    mongodb:
      {{- if .Values.mongodb.enabled }}
      hosts:
        - {{ template "bk-nodemgr.fullname" . }}-mongodb-headless
      username: {{ .Values.mongodb.auth.username }}
      password: {{ .Values.mongodb.auth.password }}
      database: {{ .Values.mongodb.auth.database }}
      authSource: {{ .Values.mongodb.auth.database }}
      authMechanism: SCRAM-SHA-256
      {{- else }}
      hosts:
        - {{ .Values.externalMongodb.hosts }}
      username: {{ .Values.externalMongodb.username }}
      password: {{ .Values.externalMongodb.password }}
      database: {{ .Values.externalMongodb.database }}
      authSource: {{ .Values.externalMongodb.authSource }}
      authMechanism: {{ .Values.externalMongodb.authMechanism }}
      {{- end}}

    repo: {{ .Values.file.config.repo | toYaml | nindent 6 }}
{{- end }}