{{- if .Values.grafana.enabled }}
{{- if not (or .Values.tempo.enabled .Values.prometheus.enabled .Values.loki.enabled .Values.pyroscope.enabled) }}
{{- fail "grafana.enabled requires tempo.enabled=true, prometheus.enabled=true, loki.enabled=true, or pyroscope.enabled=true" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" .Subcharts.grafana }}-datasources
  namespace: {{ include "grafana.namespace" .Subcharts.grafana | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      {{- if .Values.tempo.enabled }}
      - name: Tempo
        uid: bk-nodemgr-tempo
        type: tempo
        access: proxy
        url: http://{{ include "bk-nodemgr.tempo.fullname" . }}.{{ .Release.Namespace }}.svc:{{ dig "tempo" "server" "http_listen_port" 3200 .Values.tempo }}
        isDefault: {{ not .Values.prometheus.enabled }}
        editable: false
      {{- end }}
      {{- if .Values.prometheus.enabled }}
      - name: Prometheus
        uid: bk-nodemgr-prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "bk-nodemgr.prometheus.server.fullname" . }}.{{ .Release.Namespace }}.svc:{{ dig "server" "service" "servicePort" 80 .Values.prometheus }}
        isDefault: true
        editable: false
      {{- end }}
      {{- if .Values.loki.enabled }}
      - name: Loki
        uid: bk-nodemgr-loki
        type: loki
        access: proxy
        url: {{ include "bk-nodemgr.loki.httpEndpoint" . }}
        isDefault: {{ not (or .Values.prometheus.enabled .Values.tempo.enabled) }}
        editable: false
      {{- end }}
      {{- if .Values.pyroscope.enabled }}
      - name: Pyroscope
        uid: bk-nodemgr-pyroscope
        type: grafana-pyroscope-datasource
        access: proxy
        url: {{ include "bk-nodemgr.pyroscope.httpEndpoint" . }}
        isDefault: {{ not (or .Values.prometheus.enabled .Values.tempo.enabled .Values.loki.enabled) }}
        editable: false
      {{- end }}
{{- end }}
