{{- if .Values.opentelemetryGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-opentelemetry-gateway
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodemgr-opentelemetry-gateway
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: nodemgr-opentelemetry-gateway
  ports:
    - name: otlp-grpc
      port: {{ .Values.opentelemetryGateway.service.ports.otlpGrpc }}
      targetPort: otlp-grpc
    - name: otlp-http
      port: {{ .Values.opentelemetryGateway.service.ports.otlpHttp }}
      targetPort: otlp-http
    - name: metrics
      port: {{ .Values.opentelemetryGateway.service.ports.metrics }}
      targetPort: metrics
{{- end }}
