{{- if .Values.prometheus.enabled }}
{{- $prometheusServerFiles := default dict .Values.prometheus.serverFiles }}
{{- $prometheusConfig := default dict (index $prometheusServerFiles "prometheus.yml") }}
{{- $global := default (dict "scrape_interval" "1m") (get $prometheusConfig "global") }}
{{- $scrapeNamespaces := default dict .Values.prometheus.nodemgrScrape.namespaces }}
{{- $applicationNamespace := default .Release.Namespace $scrapeNamespaces.application }}
{{- $backendNamespace := default .Release.Namespace $scrapeNamespaces.backend }}
{{- $fileNamespace := default .Release.Namespace $scrapeNamespaces.file }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bk-nodemgr.prometheus.server.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      {{- toYaml $global | nindent 6 }}
    scrape_configs:
      - job_name: bk-nodemgr-application
        metrics_path: /metrics
        static_configs:
          - targets:
              - {{ template "bk-nodemgr.fullname" . }}-application.{{ $applicationNamespace }}.svc:{{ .Values.application.config.infoServer.port }}
            labels:
              namespace: {{ $applicationNamespace | quote }}
              service: application
      - job_name: bk-nodemgr-backend
        metrics_path: /metrics
        static_configs:
          - targets:
              - {{ template "bk-nodemgr.fullname" . }}-backend.{{ $backendNamespace }}.svc:{{ .Values.backend.config.infoServer.port }}
            labels:
              namespace: {{ $backendNamespace | quote }}
              service: backend
      - job_name: bk-nodemgr-file
        metrics_path: /metrics
        static_configs:
          - targets:
              - {{ template "bk-nodemgr.fullname" . }}-file.{{ $fileNamespace }}.svc:{{ .Values.file.config.infoServer.port }}
            labels:
              namespace: {{ $fileNamespace | quote }}
              service: file
{{- end }}
