{{- if and .Values.tempo.enabled .Values.tempo.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-tempo
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodemgr-tempo
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes: {{- range .Values.tempo.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.tempo.persistence "global" .Values.global) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.tempo.persistence.size | quote }}
{{- end }}
