{{- if .Values.tempo.enabled }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-tempo
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodemgr-tempo
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.tempo.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.updateStrategy.type) }}
    rollingUpdate: null
    {{- else }}
    rollingUpdate: {{ .Values.updateStrategy.rollingUpdate | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: nodemgr-tempo
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
        app: nodemgr-tempo
      annotations:
        values-hash: "{{ toYaml .Values.tempo.config | sha256sum | trunc 63 }}"
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "bk-nodemgr.tempo.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.hostAliases }}
      # yamllint disable rule:indentation
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      # yamllint enable rule:indentation
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "bk-nodemgr.fullname" . }}-tempo
          image: {{ template "bk-nodemgr.tempo.image" . }}
          imagePullPolicy: {{ .Values.tempo.image.pullPolicy | quote }}
          args:
            - --config.file=/etc/tempo/tempo.yaml
          ports:
            - name: http
              containerPort: {{ .Values.tempo.service.ports.http }}
            - name: otlp-grpc
              containerPort: {{ .Values.tempo.service.ports.otlpGrpc }}
            - name: otlp-http
              containerPort: {{ .Values.tempo.service.ports.otlpHttp }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /var/tempo
          resources: {{- toYaml .Values.tempo.resources | nindent 12 }}
      volumes:
        - name: tempo-config
          configMap:
            name: {{ template "bk-nodemgr.fullname" . }}-tempo-config
        - name: tempo-data
          {{- if .Values.tempo.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "bk-nodemgr.fullname" . }}-tempo
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
