{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-nodemgr.fullname" . }}-tempo-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app: nodemgr-tempo
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  tempo.yaml: |
    {{- include "common.tplvalues.render" (dict "value" .Values.tempo.config "context" $) | nindent 4 }}
{{- end }}
