// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: upload.proto

package v3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadAgentReq is the request for upload agent pkg.
type UploadAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsType        string                 `protobuf:"bytes,1,opt,name=os_type,json=osType,proto3" json:"os_type"`
	CpuArch       string                 `protobuf:"bytes,2,opt,name=cpu_arch,json=cpuArch,proto3" json:"cpu_arch"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version"`
	Overwrite     bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAgentReq) Reset() {
	*x = UploadAgentReq{}
	mi := &file_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAgentReq) ProtoMessage() {}

func (x *UploadAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAgentReq.ProtoReflect.Descriptor instead.
func (*UploadAgentReq) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadAgentReq) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *UploadAgentReq) GetCpuArch() string {
	if x != nil {
		return x.CpuArch
	}
	return ""
}

func (x *UploadAgentReq) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UploadAgentReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadAgentReq) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// UploadAgentResp is the response for upload agent pkg.
type UploadAgentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAgentResp) Reset() {
	*x = UploadAgentResp{}
	mi := &file_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAgentResp) ProtoMessage() {}

func (x *UploadAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAgentResp.ProtoReflect.Descriptor instead.
func (*UploadAgentResp) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAgentResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadAgentResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadAgentResp) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// UploadProxyReq is the request for upload proxy pkg.
type UploadProxyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OsType        string                 `protobuf:"bytes,1,opt,name=os_type,json=osType,proto3" json:"os_type"`
	CpuArch       string                 `protobuf:"bytes,2,opt,name=cpu_arch,json=cpuArch,proto3" json:"cpu_arch"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version"`
	Overwrite     bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProxyReq) Reset() {
	*x = UploadProxyReq{}
	mi := &file_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProxyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProxyReq) ProtoMessage() {}

func (x *UploadProxyReq) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProxyReq.ProtoReflect.Descriptor instead.
func (*UploadProxyReq) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{2}
}

func (x *UploadProxyReq) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *UploadProxyReq) GetCpuArch() string {
	if x != nil {
		return x.CpuArch
	}
	return ""
}

func (x *UploadProxyReq) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UploadProxyReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadProxyReq) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// UploadProxyResp is the response for upload proxy pkg.
type UploadProxyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProxyResp) Reset() {
	*x = UploadProxyResp{}
	mi := &file_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProxyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProxyResp) ProtoMessage() {}

func (x *UploadProxyResp) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProxyResp.ProtoReflect.Descriptor instead.
func (*UploadProxyResp) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{3}
}

func (x *UploadProxyResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadProxyResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadProxyResp) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// UploadOriginAgentReq is the request for upload origin agent pkg.
type UploadOriginAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation"`
	Overwrite     bool                   `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOriginAgentReq) Reset() {
	*x = UploadOriginAgentReq{}
	mi := &file_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOriginAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOriginAgentReq) ProtoMessage() {}

func (x *UploadOriginAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOriginAgentReq.ProtoReflect.Descriptor instead.
func (*UploadOriginAgentReq) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{4}
}

func (x *UploadOriginAgentReq) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UploadOriginAgentReq) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// UploadOriginAgentResp is the response for upload origin agent pkg.
type UploadOriginAgentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOriginAgentResp) Reset() {
	*x = UploadOriginAgentResp{}
	mi := &file_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOriginAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOriginAgentResp) ProtoMessage() {}

func (x *UploadOriginAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOriginAgentResp.ProtoReflect.Descriptor instead.
func (*UploadOriginAgentResp) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{5}
}

func (x *UploadOriginAgentResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadOriginAgentResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadOriginAgentResp) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// UploadOriginServerReq is the request for upload origin server pkg.
type UploadOriginServerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation"`
	Overwrite     bool                   `protobuf:"varint,2,opt,name=overwrite,proto3" json:"overwrite"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOriginServerReq) Reset() {
	*x = UploadOriginServerReq{}
	mi := &file_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOriginServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOriginServerReq) ProtoMessage() {}

func (x *UploadOriginServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOriginServerReq.ProtoReflect.Descriptor instead.
func (*UploadOriginServerReq) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{6}
}

func (x *UploadOriginServerReq) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UploadOriginServerReq) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

// UploadOriginServerResp is the response for upload origin server pkg.
type UploadOriginServerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOriginServerResp) Reset() {
	*x = UploadOriginServerResp{}
	mi := &file_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOriginServerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOriginServerResp) ProtoMessage() {}

func (x *UploadOriginServerResp) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOriginServerResp.ProtoReflect.Descriptor instead.
func (*UploadOriginServerResp) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{7}
}

func (x *UploadOriginServerResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadOriginServerResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadOriginServerResp) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

var File_upload_proto protoreflect.FileDescriptor

const file_upload_proto_rawDesc = "" +
	"\n" +
	"\fupload.proto\x12\x02v3\x1a\x1cgoogle/api/annotations.proto\"\x9c\x01\n" +
	"\x0eUploadAgentReq\x12\x17\n" +
	"\aos_type\x18\x01 \x01(\tR\x06osType\x12\x19\n" +
	"\bcpu_arch\x18\x02 \x01(\tR\acpuArch\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\"K\n" +
	"\x0fUploadAgentResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\"\x9c\x01\n" +
	"\x0eUploadProxyReq\x12\x17\n" +
	"\aos_type\x18\x01 \x01(\tR\x06osType\x12\x19\n" +
	"\bcpu_arch\x18\x02 \x01(\tR\acpuArch\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\"K\n" +
	"\x0fUploadProxyResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\"T\n" +
	"\x14UploadOriginAgentReq\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x12\x1c\n" +
	"\toverwrite\x18\x02 \x01(\bR\toverwrite\"Q\n" +
	"\x15UploadOriginAgentResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\"U\n" +
	"\x15UploadOriginServerReq\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x12\x1c\n" +
	"\toverwrite\x18\x02 \x01(\bR\toverwrite\"R\n" +
	"\x16UploadOriginServerResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5BCZAgithub.com/TencentBlueKing/bk-nodemgr/pkg/protocol/backend/api/v3b\x06proto3"

var (
	file_upload_proto_rawDescOnce sync.Once
	file_upload_proto_rawDescData []byte
)

func file_upload_proto_rawDescGZIP() []byte {
	file_upload_proto_rawDescOnce.Do(func() {
		file_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_proto_rawDesc), len(file_upload_proto_rawDesc)))
	})
	return file_upload_proto_rawDescData
}

var file_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_upload_proto_goTypes = []any{
	(*UploadAgentReq)(nil),         // 0: v3.UploadAgentReq
	(*UploadAgentResp)(nil),        // 1: v3.UploadAgentResp
	(*UploadProxyReq)(nil),         // 2: v3.UploadProxyReq
	(*UploadProxyResp)(nil),        // 3: v3.UploadProxyResp
	(*UploadOriginAgentReq)(nil),   // 4: v3.UploadOriginAgentReq
	(*UploadOriginAgentResp)(nil),  // 5: v3.UploadOriginAgentResp
	(*UploadOriginServerReq)(nil),  // 6: v3.UploadOriginServerReq
	(*UploadOriginServerResp)(nil), // 7: v3.UploadOriginServerResp
}
var file_upload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upload_proto_init() }
func file_upload_proto_init() {
	if File_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_proto_rawDesc), len(file_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upload_proto_goTypes,
		DependencyIndexes: file_upload_proto_depIdxs,
		MessageInfos:      file_upload_proto_msgTypes,
	}.Build()
	File_upload_proto = out.File
	file_upload_proto_goTypes = nil
	file_upload_proto_depIdxs = nil
}
