apiVersion: v2
appVersion: 2.3.1
dependencies:
- alias: agent
  condition: agent.enabled
  name: grafana-agent
  repository: https://grafana.github.io/helm-charts
  version: 0.44.2
- alias: alloy
  condition: alloy.enabled
  name: alloy
  repository: https://grafana.github.io/helm-charts
  version: 1.5.2
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 4.1.0
description: A horizontally scalable, highly available, multi-tenant continuous profiling
  database.
home: https://grafana.com/oss/pyroscope/
name: pyroscope
sources:
- https://github.com/grafana/pyroscope
- https://github.com/grafana/pyroscope/tree/main/operations/pyroscope/helm/pyroscope
type: application
version: 2.3.1
