name: "Issue Product Label Management"
on:
  issues:
    types: [opened, reopened, closed]

jobs:
  manage-issue:
    runs-on: self-hosted
    permissions:
      issues: write
    steps:
      # 新建或重开 issue 时添加 todo 标签
      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          (github.event.action == 'opened' || github.event.action == 'reopened') &&
          contains(github.event.issue.title, '[FEATURE]')
        with:
          labels: product/todo

      # 新建或重开 issue 时设置负责人
      - uses: actions-ecosystem/action-add-assignees@v1
        if: |
          (github.event.action == 'opened' || github.event.action == 'reopened') &&
          (github.event.issue.assignees == null || github.event.issue.assignees[0] == null)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.issue.user.login }}

      # 关闭 issue 时移除 todo 标签
      - uses: actions-ecosystem/action-remove-labels@v1
        if: |
          github.event.action == 'closed' &&
          contains(github.event.issue.labels.*.name, 'product/todo')
        with:
          labels: product/todo

      # 关闭 issue 时添加 done 标签
      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          github.event.action == 'closed' &&
          contains(github.event.issue.labels.*.name, 'product/todo')
        with:
          labels: product/done