name: "Issue Todo Labeler"
on:
  issues:
    types: [opened,reopened] # 当issue被创建或重新打开时触发

jobs:
  set-issue:
    runs-on: self-hosted
    permissions:
      issues: write
    steps:
      # 步骤1: 检查标题并添加标签
      - name: Check Issue Title and Add Label
        if: contains(github.event.issue.title, '[FEATURE]')
        run: gh issue edit "$NUMBER" --add-label "product/todo"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}

      # 步骤2: 检查是否有分配人，如果没有则分配给创建者
      - name: Check and Set Assignee
        if: ${{ github.event.issue.assignees == null || github.event.issue.assignees[0] == null }}
        run: |
          gh issue edit "$NUMBER" --add-assignee "$CREATOR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          CREATOR: ${{ github.event.issue.user.login }}